/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG JSE (https://www.swig.org).
 * Version 5.0.6
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package js.octra.joctra;

public class DPair {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected DPair(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DPair obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(DPair obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        octraJNI.delete_DPair(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public DPair() {
    this(octraJNI.new_DPair__SWIG_0(), true);
  }

  public DPair(double first, double second) {
    this(octraJNI.new_DPair__SWIG_1(first, second), true);
  }

  public DPair(DPair other) {
    this(octraJNI.new_DPair__SWIG_2(DPair.getCPtr(other), other), true);
  }

  public void setFirst(double value) {
    octraJNI.DPair_first_set(swigCPtr, this, value);
  }

  public double getFirst() {
    return octraJNI.DPair_first_get(swigCPtr, this);
  }

  public void setSecond(double value) {
    octraJNI.DPair_second_set(swigCPtr, this, value);
  }

  public double getSecond() {
    return octraJNI.DPair_second_get(swigCPtr, this);
  }
}
