/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG JSE (https://www.swig.org).
 * Version 5.0.6
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package js.octra.joctra;

public class IPair {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected IPair(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IPair obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(IPair obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        octraJNI.delete_IPair(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public IPair() {
    this(octraJNI.new_IPair__SWIG_0(), true);
  }

  public IPair(int first, int second) {
    this(octraJNI.new_IPair__SWIG_1(first, second), true);
  }

  public IPair(IPair other) {
    this(octraJNI.new_IPair__SWIG_2(IPair.getCPtr(other), other), true);
  }

  public void setFirst(int value) {
    octraJNI.IPair_first_set(swigCPtr, this, value);
  }

  public int getFirst() {
    return octraJNI.IPair_first_get(swigCPtr, this);
  }

  public void setSecond(int value) {
    octraJNI.IPair_second_set(swigCPtr, this, value);
  }

  public int getSecond() {
    return octraJNI.IPair_second_get(swigCPtr, this);
  }
}
