/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG JSE (https://www.swig.org).
 * Version 5.0.6
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package js.octra.joctra;

public class IVector extends java.util.AbstractList<Integer> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected IVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(IVector obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        octraJNI.delete_IVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  @SuppressWarnings("this-escape")
  public IVector(int[] initialElements) {
    this();
    doReserve(initialElements.length);

    for (int element : initialElements) {
      doAdd(element);
    }
  }

  @SuppressWarnings("this-escape")
  public IVector(Iterable<Integer> initialElements) {
    this();
    for (int element : initialElements) {
      doAdd(element);
    }
  }

  public Integer get(int index) {
    return doGet(index);
  }

  public Integer set(int index, Integer e) {
    return doSet(index, e);
  }

  public boolean add(Integer e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, Integer e) {
    modCount++;
    doAdd(index, e);
  }

  public Integer remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public int capacity() {
    return doCapacity();
  }

  public void reserve(int n) {
    doReserve(n);
  }

  public IVector() {
    this(octraJNI.new_IVector__SWIG_0(), true);
  }

  public IVector(IVector other) {
    this(octraJNI.new_IVector__SWIG_1(IVector.getCPtr(other), other), true);
  }

  public boolean isEmpty() {
    return octraJNI.IVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    octraJNI.IVector_clear(swigCPtr, this);
  }

  public IVector(int count, int value) {
    this(octraJNI.new_IVector__SWIG_2(count, value), true);
  }

  private int doCapacity() {
    return octraJNI.IVector_doCapacity(swigCPtr, this);
  }

  private void doReserve(int n) {
    octraJNI.IVector_doReserve(swigCPtr, this, n);
  }

  private int doSize() {
    return octraJNI.IVector_doSize(swigCPtr, this);
  }

  private void doAdd(int x) {
    octraJNI.IVector_doAdd__SWIG_0(swigCPtr, this, x);
  }

  private void doAdd(int index, int x) {
    octraJNI.IVector_doAdd__SWIG_1(swigCPtr, this, index, x);
  }

  private int doRemove(int index) {
    return octraJNI.IVector_doRemove(swigCPtr, this, index);
  }

  private int doGet(int index) {
    return octraJNI.IVector_doGet(swigCPtr, this, index);
  }

  private int doSet(int index, int val) {
    return octraJNI.IVector_doSet(swigCPtr, this, index, val);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    octraJNI.IVector_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }
}
