/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG JSE (https://www.swig.org).
 * Version 5.0.6
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package js.octra.joctra;

public class octra {
  static { System.loadLibrary("octra_jni"); }
  public static void hello() {
    octraJNI.hello();
  }

  public static double call_with_callback(double x, Callback cb) {
    return octraJNI.call_with_callback(x, Callback.getCPtr(cb), cb);
  }

  public static DVector map_dvector_with_callback(DVector values, Callback cb) {
    return new DVector(octraJNI.map_dvector_with_callback(DVector.getCPtr(values), values, Callback.getCPtr(cb), cb), true);
  }

  public static DVector make_dvector(double a, double b, double c) {
    return new DVector(octraJNI.make_dvector(a, b, c), true);
  }

  public static double sum_dvector(DVector values) {
    return octraJNI.sum_dvector(DVector.getCPtr(values), values);
  }

  public static DPair make_dpair(double a, double b) {
    return new DPair(octraJNI.make_dpair(a, b), true);
  }

  public static double sum_dpair(DPair values) {
    return octraJNI.sum_dpair(DPair.getCPtr(values), values);
  }

}
