/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG JSE (https://www.swig.org).
 * Version 5.0.6
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package js.octra.joctra;

public class SizeVector extends java.util.AbstractList<Long> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SizeVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SizeVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(SizeVector obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        octraJNI.delete_SizeVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  @SuppressWarnings("this-escape")
  public SizeVector(long[] initialElements) {
    this();
    doReserve(initialElements.length);

    for (long element : initialElements) {
      doAdd(element);
    }
  }

  @SuppressWarnings("this-escape")
  public SizeVector(Iterable<Long> initialElements) {
    this();
    for (long element : initialElements) {
      doAdd(element);
    }
  }

  public Long get(int index) {
    return doGet(index);
  }

  public Long set(int index, Long e) {
    return doSet(index, e);
  }

  public boolean add(Long e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, Long e) {
    modCount++;
    doAdd(index, e);
  }

  public Long remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public int capacity() {
    return doCapacity();
  }

  public void reserve(int n) {
    doReserve(n);
  }

  public SizeVector() {
    this(octraJNI.new_SizeVector__SWIG_0(), true);
  }

  public SizeVector(SizeVector other) {
    this(octraJNI.new_SizeVector__SWIG_1(SizeVector.getCPtr(other), other), true);
  }

  public boolean isEmpty() {
    return octraJNI.SizeVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    octraJNI.SizeVector_clear(swigCPtr, this);
  }

  public SizeVector(int count, long value) {
    this(octraJNI.new_SizeVector__SWIG_2(count, value), true);
  }

  private int doCapacity() {
    return octraJNI.SizeVector_doCapacity(swigCPtr, this);
  }

  private void doReserve(int n) {
    octraJNI.SizeVector_doReserve(swigCPtr, this, n);
  }

  private int doSize() {
    return octraJNI.SizeVector_doSize(swigCPtr, this);
  }

  private void doAdd(long x) {
    octraJNI.SizeVector_doAdd__SWIG_0(swigCPtr, this, x);
  }

  private void doAdd(int index, long x) {
    octraJNI.SizeVector_doAdd__SWIG_1(swigCPtr, this, index, x);
  }

  private long doRemove(int index) {
    return octraJNI.SizeVector_doRemove(swigCPtr, this, index);
  }

  private long doGet(int index) {
    return octraJNI.SizeVector_doGet(swigCPtr, this, index);
  }

  private long doSet(int index, long val) {
    return octraJNI.SizeVector_doSet(swigCPtr, this, index, val);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    octraJNI.SizeVector_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }
}
