/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_octra_WRAP_H_
#define SWIG_octra_WRAP_H_

class SwigDirector_Callback : public octra::Callback, public Swig::Director {

public:
    SwigDirector_Callback();
    virtual ~SwigDirector_Callback();
    virtual double call(double x);

    typedef double (* SWIG_Callback0_t)(void *dobj, double);
    void swig_connect_director(void* dobj, SWIG_Callback0_t callbackcall);

private:
    void swig_init_callbacks();
    void *d_object;
    SWIG_Callback0_t swig_callback_call;
};


#endif
