/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


#define SWIG_VERSION 0x040301
#define SWIGOCAML
#define SWIG_MODULE "octra"

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif

#if defined(__cplusplus) && __cplusplus >=201103L
# define SWIG_NULLPTR nullptr
#else
# define SWIG_NULLPTR NULL
#endif 

/* -----------------------------------------------------------------------------
 * swigcompat.swg
 *
 * Macros to provide support compatibility with older C and C++ standards.
 *
 * Note that SWIG expects __cplusplus to be defined to the appropriate C++ standard.
 * MSVC users are urged to check and examine the /Zc:__cplusplus compiler option.
 * See https://learn.microsoft.com/en-us/cpp/build/reference/zc-cplusplus.
 * ----------------------------------------------------------------------------- */

/* C99 and C++11 should provide snprintf, but define SWIG_NO_SNPRINTF
 * if you're missing it.
 */
#if ((defined __STDC_VERSION__ && __STDC_VERSION__ >= 199901L) || \
     (defined __cplusplus && __cplusplus >= 201103L) || \
     defined SWIG_HAVE_SNPRINTF) && \
    !defined SWIG_NO_SNPRINTF
# define SWIG_snprintf(O,S,F,A) snprintf(O,S,F,A)
# define SWIG_snprintf2(O,S,F,A,B) snprintf(O,S,F,A,B)
#else
/* Fallback versions ignore the buffer size, but most of our uses either have a
 * fixed maximum possible size or dynamically allocate a buffer that's large
 * enough.
 */
# define SWIG_snprintf(O,S,F,A) sprintf(O,F,A)
# define SWIG_snprintf2(O,S,F,A,B) sprintf(O,F,A,B)
#endif

/* -----------------------------------------------------------------------------
 * swigrun.swg
 *
 * This file contains generic C API SWIG runtime support for pointer
 * type checking.
 * ----------------------------------------------------------------------------- */

/* This should only be incremented when either the layout of swig_type_info changes,
   or for whatever reason, the runtime changes incompatibly */
#define SWIG_RUNTIME_VERSION "4"

/* define SWIG_TYPE_TABLE_NAME as "SWIG_TYPE_TABLE" */
#ifdef SWIG_TYPE_TABLE
# define SWIG_QUOTE_STRING(x) #x
# define SWIG_EXPAND_AND_QUOTE_STRING(x) SWIG_QUOTE_STRING(x)
# define SWIG_TYPE_TABLE_NAME SWIG_EXPAND_AND_QUOTE_STRING(SWIG_TYPE_TABLE)
#else
# define SWIG_TYPE_TABLE_NAME
#endif

/*
  You can use the SWIGRUNTIME and SWIGRUNTIMEINLINE macros for
  creating a static or dynamic library from the SWIG runtime code.
  In 99.9% of the cases, SWIG just needs to declare them as 'static'.

  But only do this if strictly necessary, ie, if you have problems
  with your compiler or suchlike.
*/

#ifndef SWIGRUNTIME
# define SWIGRUNTIME SWIGINTERN
#endif

#ifndef SWIGRUNTIMEINLINE
# define SWIGRUNTIMEINLINE SWIGRUNTIME SWIGINLINE
#endif

/*  Generic buffer size */
#ifndef SWIG_BUFFER_SIZE
# define SWIG_BUFFER_SIZE 1024
#endif

/* Flags for pointer conversions */
#define SWIG_POINTER_DISOWN        0x1
#define SWIG_CAST_NEW_MEMORY       0x2
#define SWIG_POINTER_NO_NULL       0x4
#define SWIG_POINTER_CLEAR         0x8
#define SWIG_POINTER_RELEASE       (SWIG_POINTER_CLEAR | SWIG_POINTER_DISOWN)

/* Flags for new pointer objects */
#define SWIG_POINTER_OWN           0x1


/*
   Flags/methods for returning states.

   The SWIG conversion methods, as ConvertPtr, return an integer
   that tells if the conversion was successful or not. And if not,
   an error code can be returned (see swigerrors.swg for the codes).

   Use the following macros/flags to set or process the returning
   states.

   In old versions of SWIG, code such as the following was usually written:

     if (SWIG_ConvertPtr(obj,vptr,ty.flags) != -1) {
       // success code
     } else {
       //fail code
     }

   Now you can be more explicit:

    int res = SWIG_ConvertPtr(obj,vptr,ty.flags);
    if (SWIG_IsOK(res)) {
      // success code
    } else {
      // fail code
    }

   which is the same really, but now you can also do

    Type *ptr;
    int res = SWIG_ConvertPtr(obj,(void **)(&ptr),ty.flags);
    if (SWIG_IsOK(res)) {
      // success code
      if (SWIG_IsNewObj(res) {
        ...
	delete *ptr;
      } else {
        ...
      }
    } else {
      // fail code
    }

   I.e., now SWIG_ConvertPtr can return new objects and you can
   identify the case and take care of the deallocation. Of course that
   also requires SWIG_ConvertPtr to return new result values, such as

      int SWIG_ConvertPtr(obj, ptr,...) {
        if (<obj is ok>) {
          if (<need new object>) {
            *ptr = <ptr to new allocated object>;
            return SWIG_NEWOBJ;
          } else {
            *ptr = <ptr to old object>;
            return SWIG_OLDOBJ;
          }
        } else {
          return SWIG_BADOBJ;
        }
      }

   Of course, returning the plain '0(success)/-1(fail)' still works, but you can be
   more explicit by returning SWIG_BADOBJ, SWIG_ERROR or any of the
   SWIG errors code.

   Finally, if the SWIG_CASTRANK_MODE is enabled, the result code
   allows returning the 'cast rank', for example, if you have this

       int food(double)
       int fooi(int);

   and you call

      food(1)   // cast rank '1'  (1 -> 1.0)
      fooi(1)   // cast rank '0'

   just use the SWIG_AddCast()/SWIG_CheckState()
*/

#define SWIG_OK                    (0)
/* Runtime errors are < 0 */
#define SWIG_ERROR                 (-1)
/* Errors in range -1 to -99 are in swigerrors.swg (errors for all languages including those not using the runtime) */
/* Errors in range -100 to -199 are language specific errors defined in *errors.swg */
/* Errors < -200 are generic runtime specific errors */
#define SWIG_ERROR_RELEASE_NOT_OWNED (-200)

#define SWIG_IsOK(r)               (r >= 0)
#define SWIG_ArgError(r)           ((r != SWIG_ERROR) ? r : SWIG_TypeError)

/* The CastRankLimit says how many bits are used for the cast rank */
#define SWIG_CASTRANKLIMIT         (1 << 8)
/* The NewMask denotes the object was created (using new/malloc) */
#define SWIG_NEWOBJMASK            (SWIG_CASTRANKLIMIT  << 1)
/* The TmpMask is for in/out typemaps that use temporary objects */
#define SWIG_TMPOBJMASK            (SWIG_NEWOBJMASK << 1)
/* Simple returning values */
#define SWIG_BADOBJ                (SWIG_ERROR)
#define SWIG_OLDOBJ                (SWIG_OK)
#define SWIG_NEWOBJ                (SWIG_OK | SWIG_NEWOBJMASK)
#define SWIG_TMPOBJ                (SWIG_OK | SWIG_TMPOBJMASK)
/* Check, add and del object mask methods */
#define SWIG_AddNewMask(r)         (SWIG_IsOK(r) ? (r | SWIG_NEWOBJMASK) : r)
#define SWIG_DelNewMask(r)         (SWIG_IsOK(r) ? (r & ~SWIG_NEWOBJMASK) : r)
#define SWIG_IsNewObj(r)           (SWIG_IsOK(r) && (r & SWIG_NEWOBJMASK))
#define SWIG_AddTmpMask(r)         (SWIG_IsOK(r) ? (r | SWIG_TMPOBJMASK) : r)
#define SWIG_DelTmpMask(r)         (SWIG_IsOK(r) ? (r & ~SWIG_TMPOBJMASK) : r)
#define SWIG_IsTmpObj(r)           (SWIG_IsOK(r) && (r & SWIG_TMPOBJMASK))

/* Cast-Rank Mode */
#if defined(SWIG_CASTRANK_MODE)
#  ifndef SWIG_TypeRank
#    define SWIG_TypeRank             unsigned long
#  endif
#  ifndef SWIG_MAXCASTRANK            /* Default cast allowed */
#    define SWIG_MAXCASTRANK          (2)
#  endif
#  define SWIG_CASTRANKMASK          ((SWIG_CASTRANKLIMIT) -1)
#  define SWIG_CastRank(r)           (r & SWIG_CASTRANKMASK)
SWIGINTERNINLINE int SWIG_AddCast(int r) {
  return SWIG_IsOK(r) ? ((SWIG_CastRank(r) < SWIG_MAXCASTRANK) ? (r + 1) : SWIG_ERROR) : r;
}
SWIGINTERNINLINE int SWIG_CheckState(int r) {
  return SWIG_IsOK(r) ? SWIG_CastRank(r) + 1 : 0;
}
#else /* no cast-rank mode */
#  define SWIG_AddCast(r) (r)
#  define SWIG_CheckState(r) (SWIG_IsOK(r) ? 1 : 0)
#endif


#include <string.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef void *(*swig_converter_func)(void *, int *);
typedef struct swig_type_info *(*swig_dycast_func)(void **);

/* Structure to store information on one type */
typedef struct swig_type_info {
  const char             *name;			/* mangled name of this type */
  const char             *str;			/* human readable name of this type */
  swig_dycast_func        dcast;		/* dynamic cast function down a hierarchy */
  struct swig_cast_info  *cast;			/* linked list of types that can cast into this type */
  void                   *clientdata;		/* language specific type data */
  int                    owndata;		/* flag if the structure owns the clientdata */
} swig_type_info;

/* Structure to store a type and conversion function used for casting */
typedef struct swig_cast_info {
  swig_type_info         *type;			/* pointer to type that is equivalent to this type */
  swig_converter_func     converter;		/* function to cast the void pointers */
  struct swig_cast_info  *next;			/* pointer to next cast in linked list */
  struct swig_cast_info  *prev;			/* pointer to the previous cast */
} swig_cast_info;

/* Structure used to store module information
 * Each module generates one structure like this, and the runtime collects
 * all of these structures and stores them in a circularly linked list.*/
typedef struct swig_module_info {
  swig_type_info         **types;		/* Array of pointers to swig_type_info structures that are in this module */
  size_t                 size;		        /* Number of types in this module */
  struct swig_module_info *next;		/* Pointer to next element in circularly linked list */
  swig_type_info         **type_initial;	/* Array of initially generated type structures */
  swig_cast_info         **cast_initial;	/* Array of initially generated casting structures */
  void                    *clientdata;		/* Language specific module data */
} swig_module_info;

/*
  Compare two type names skipping the space characters, therefore
  "char*" == "char *" and "Class<int>" == "Class<int >", etc.

  Return 0 when the two name types are equivalent, as in
  strncmp, but skipping ' '.
*/
SWIGRUNTIME int
SWIG_TypeNameComp(const char *f1, const char *l1,
		  const char *f2, const char *l2) {
  for (;(f1 != l1) && (f2 != l2); ++f1, ++f2) {
    while ((*f1 == ' ') && (f1 != l1)) ++f1;
    while ((*f2 == ' ') && (f2 != l2)) ++f2;
    if (*f1 != *f2) return (*f1 > *f2) ? 1 : -1;
  }
  return (int)((l1 - f1) - (l2 - f2));
}

/*
  Check type equivalence in a name list like <name1>|<name2>|...
  Return 0 if equal, -1 if nb < tb, 1 if nb > tb
*/
SWIGRUNTIME int
SWIG_TypeCmp(const char *nb, const char *tb) {
  int equiv = 1;
  const char* te = tb + strlen(tb);
  const char* ne = nb;
  while (equiv != 0 && *ne) {
    for (nb = ne; *ne; ++ne) {
      if (*ne == '|') break;
    }
    equiv = SWIG_TypeNameComp(nb, ne, tb, te);
    if (*ne) ++ne;
  }
  return equiv;
}

/*
  Check type equivalence in a name list like <name1>|<name2>|...
  Return 0 if not equal, 1 if equal
*/
SWIGRUNTIME int
SWIG_TypeEquiv(const char *nb, const char *tb) {
  return SWIG_TypeCmp(nb, tb) == 0 ? 1 : 0;
}

/*
  Check the typename
*/
SWIGRUNTIME swig_cast_info *
SWIG_TypeCheck(const char *c, swig_type_info *ty) {
  if (ty) {
    swig_cast_info *iter = ty->cast;
    while (iter) {
      if (strcmp(iter->type->name, c) == 0) {
        if (iter == ty->cast)
          return iter;
        /* Move iter to the top of the linked list */
        iter->prev->next = iter->next;
        if (iter->next)
          iter->next->prev = iter->prev;
        iter->next = ty->cast;
        iter->prev = 0;
        if (ty->cast) ty->cast->prev = iter;
        ty->cast = iter;
        return iter;
      }
      iter = iter->next;
    }
  }
  return 0;
}

/*
  Identical to SWIG_TypeCheck, except strcmp is replaced with a pointer comparison
*/
SWIGRUNTIME swig_cast_info *
SWIG_TypeCheckStruct(const swig_type_info *from, swig_type_info *ty) {
  if (ty) {
    swig_cast_info *iter = ty->cast;
    while (iter) {
      if (iter->type == from) {
        if (iter == ty->cast)
          return iter;
        /* Move iter to the top of the linked list */
        iter->prev->next = iter->next;
        if (iter->next)
          iter->next->prev = iter->prev;
        iter->next = ty->cast;
        iter->prev = 0;
        if (ty->cast) ty->cast->prev = iter;
        ty->cast = iter;
        return iter;
      }
      iter = iter->next;
    }
  }
  return 0;
}

/*
  Cast a pointer up an inheritance hierarchy
*/
SWIGRUNTIMEINLINE void *
SWIG_TypeCast(swig_cast_info *ty, void *ptr, int *newmemory) {
  return ((!ty) || (!ty->converter)) ? ptr : (*ty->converter)(ptr, newmemory);
}

/*
   Dynamic pointer casting. Down an inheritance hierarchy
*/
SWIGRUNTIME swig_type_info *
SWIG_TypeDynamicCast(swig_type_info *ty, void **ptr) {
  swig_type_info *lastty = ty;
  if (!ty || !ty->dcast) return ty;
  while (ty && (ty->dcast)) {
    ty = (*ty->dcast)(ptr);
    if (ty) lastty = ty;
  }
  return lastty;
}

/*
  Return the name associated with this type
*/
SWIGRUNTIMEINLINE const char *
SWIG_TypeName(const swig_type_info *ty) {
  return ty->name;
}

/*
  Return the pretty name associated with this type,
  that is an unmangled type name in a form presentable to the user.
*/
SWIGRUNTIME const char *
SWIG_TypePrettyName(const swig_type_info *type) {
  /* The "str" field contains the equivalent pretty names of the
     type, separated by vertical-bar characters.  Choose the last
     name. It should be the most specific; a fully resolved name
     but not necessarily with default template parameters expanded. */
  if (!type) return NULL;
  if (type->str != NULL) {
    const char *last_name = type->str;
    const char *s;
    for (s = type->str; *s; s++)
      if (*s == '|') last_name = s+1;
    return last_name;
  }
  else
    return type->name;
}

/*
   Set the clientdata field for a type
*/
SWIGRUNTIME void
SWIG_TypeClientData(swig_type_info *ti, void *clientdata) {
  swig_cast_info *cast = ti->cast;
  /* if (ti->clientdata == clientdata) return; */
  ti->clientdata = clientdata;

  while (cast) {
    if (!cast->converter) {
      swig_type_info *tc = cast->type;
      if (!tc->clientdata) {
	SWIG_TypeClientData(tc, clientdata);
      }
    }
    cast = cast->next;
  }
}
SWIGRUNTIME void
SWIG_TypeNewClientData(swig_type_info *ti, void *clientdata) {
  SWIG_TypeClientData(ti, clientdata);
  ti->owndata = 1;
}

/*
  Search for a swig_type_info structure only by mangled name
  Search is a O(log #types)

  We start searching at module start, and finish searching when start == end.
  Note: if start == end at the beginning of the function, we go all the way around
  the circular list.
*/
SWIGRUNTIME swig_type_info *
SWIG_MangledTypeQueryModule(swig_module_info *start,
                            swig_module_info *end,
		            const char *name) {
  swig_module_info *iter = start;
  do {
    if (iter->size) {
      size_t l = 0;
      size_t r = iter->size - 1;
      do {
	/* since l+r >= 0, we can (>> 1) instead (/ 2) */
	size_t i = (l + r) >> 1;
	const char *iname = iter->types[i]->name;
	if (iname) {
	  int compare = strcmp(name, iname);
	  if (compare == 0) {
	    return iter->types[i];
	  } else if (compare < 0) {
	    if (i) {
	      r = i - 1;
	    } else {
	      break;
	    }
	  } else if (compare > 0) {
	    l = i + 1;
	  }
	} else {
	  break; /* should never happen */
	}
      } while (l <= r);
    }
    iter = iter->next;
  } while (iter != end);
  return 0;
}

/*
  Search for a swig_type_info structure for either a mangled name or a human readable name.
  It first searches the mangled names of the types, which is a O(log #types)
  If a type is not found it then searches the human readable names, which is O(#types).

  We start searching at module start, and finish searching when start == end.
  Note: if start == end at the beginning of the function, we go all the way around
  the circular list.
*/
SWIGRUNTIME swig_type_info *
SWIG_TypeQueryModule(swig_module_info *start,
                     swig_module_info *end,
		     const char *name) {
  /* STEP 1: Search the name field using binary search */
  swig_type_info *ret = SWIG_MangledTypeQueryModule(start, end, name);
  if (ret) {
    return ret;
  } else {
    /* STEP 2: If the type hasn't been found, do a complete search
       of the str field (the human readable name) */
    swig_module_info *iter = start;
    do {
      size_t i = 0;
      for (; i < iter->size; ++i) {
	if (iter->types[i]->str && (SWIG_TypeEquiv(iter->types[i]->str, name)))
	  return iter->types[i];
      }
      iter = iter->next;
    } while (iter != end);
  }

  /* neither found a match */
  return 0;
}

/*
   Pack binary data into a string
*/
SWIGRUNTIME char *
SWIG_PackData(char *c, void *ptr, size_t sz) {
  static const char hex[17] = "0123456789abcdef";
  const unsigned char *u = (unsigned char *) ptr;
  const unsigned char *eu =  u + sz;
  for (; u != eu; ++u) {
    unsigned char uu = *u;
    *(c++) = hex[(uu & 0xf0) >> 4];
    *(c++) = hex[uu & 0xf];
  }
  return c;
}

/*
   Unpack binary data from a string
*/
SWIGRUNTIME const char *
SWIG_UnpackData(const char *c, void *ptr, size_t sz) {
  unsigned char *u = (unsigned char *) ptr;
  const unsigned char *eu = u + sz;
  for (; u != eu; ++u) {
    char d = *(c++);
    unsigned char uu;
    if ((d >= '0') && (d <= '9'))
      uu = (unsigned char)((d - '0') << 4);
    else if ((d >= 'a') && (d <= 'f'))
      uu = (unsigned char)((d - ('a'-10)) << 4);
    else
      return (char *) 0;
    d = *(c++);
    if ((d >= '0') && (d <= '9'))
      uu |= (unsigned char)(d - '0');
    else if ((d >= 'a') && (d <= 'f'))
      uu |= (unsigned char)(d - ('a'-10));
    else
      return (char *) 0;
    *u = uu;
  }
  return c;
}

/*
   Pack 'void *' into a string buffer.
*/
SWIGRUNTIME char *
SWIG_PackVoidPtr(char *buff, void *ptr, const char *name, size_t bsz) {
  char *r = buff;
  if ((2*sizeof(void *) + 2) > bsz) return 0;
  *(r++) = '_';
  r = SWIG_PackData(r,&ptr,sizeof(void *));
  if (strlen(name) + 1 > (bsz - (r - buff))) return 0;
  strcpy(r,name);
  return buff;
}

SWIGRUNTIME const char *
SWIG_UnpackVoidPtr(const char *c, void **ptr, const char *name) {
  if (*c != '_') {
    if (strcmp(c,"NULL") == 0) {
      *ptr = (void *) 0;
      return name;
    } else {
      return 0;
    }
  }
  return SWIG_UnpackData(++c,ptr,sizeof(void *));
}

SWIGRUNTIME char *
SWIG_PackDataName(char *buff, void *ptr, size_t sz, const char *name, size_t bsz) {
  char *r = buff;
  size_t lname = (name ? strlen(name) : 0);
  if ((2*sz + 2 + lname) > bsz) return 0;
  *(r++) = '_';
  r = SWIG_PackData(r,ptr,sz);
  if (lname) {
    strncpy(r,name,lname+1);
  } else {
    *r = 0;
  }
  return buff;
}

SWIGRUNTIME const char *
SWIG_UnpackDataName(const char *c, void *ptr, size_t sz, const char *name) {
  if (*c != '_') {
    if (strcmp(c,"NULL") == 0) {
      memset(ptr,0,sz);
      return name;
    } else {
      return 0;
    }
  }
  return SWIG_UnpackData(++c,ptr,sz);
}

#ifdef __cplusplus
}
#endif

/* -----------------------------------------------------------------------------
 * ocamlrundec.swg
 *
 * Ocaml runtime code -- declarations
 * ----------------------------------------------------------------------------- */

#include <stdio.h>
#include <string.h>
#include <stdlib.h>

#ifdef __cplusplus
#define SWIGEXT extern "C"
SWIGEXT {
#else
#define SWIGEXT 
#endif
#define CAML_NAME_SPACE
#include <caml/alloc.h>
#include <caml/custom.h>
#include <caml/mlvalues.h>
#include <caml/memory.h>
#include <caml/callback.h>
#include <caml/fail.h>
#include <caml/misc.h>

#if defined(CAMLassert)
/* Both this macro and version.h were introduced in version 4.02.0 */
#include <caml/version.h>
#else
#define OCAML_VERSION 0 /* Unknown, but < 40200 */
#endif

#define caml_array_set swig_caml_array_set

#define SWIG_NewPointerObj(p,type,flags) caml_val_ptr(p,type)
#define SWIG_GetModule(clientdata) SWIG_Ocaml_GetModule(clientdata)
#define SWIG_SetModule(clientdata, pointer) SWIG_Ocaml_SetModule(pointer)

typedef enum {
  SWIG_OCamlArithmeticException,
  SWIG_OCamlDirectorPureVirtual,
  SWIG_OCamlOutOfMemoryError,
  SWIG_OCamlOverflowException,
  SWIG_OCamlIllegalArgumentException,
  SWIG_OCamlIndexOutOfBoundsException,
  SWIG_OCamlRuntimeException,
  SWIG_OCamlSystemException,
  SWIG_OCamlNullReferenceException,
  SWIG_OCamlUnknownError
} SWIG_OCamlExceptionCodes;

SWIGINTERN void SWIG_OCamlThrowException(SWIG_OCamlExceptionCodes code, const char *msg) {
  CAMLparam0();
  CAMLlocal1(str);

  switch (code) {
  case SWIG_OCamlIllegalArgumentException:
  case SWIG_OCamlNullReferenceException:
    caml_invalid_argument(msg);
    break;
  case SWIG_OCamlSystemException:
    str = caml_copy_string(msg);
    caml_raise_sys_error(str);
    break;
  case SWIG_OCamlArithmeticException:
  case SWIG_OCamlIndexOutOfBoundsException:
  case SWIG_OCamlOutOfMemoryError:
  case SWIG_OCamlOverflowException:
  case SWIG_OCamlRuntimeException:
  case SWIG_OCamlUnknownError:
  default:
    caml_failwith(msg);
    break;
  }
  CAMLreturn0;
}

#define SWIG_contract_assert(expr, msg) do { if(!(expr)) {SWIG_OCamlThrowException(SWIG_OCamlRuntimeException, msg);} } while (0)

    SWIGINTERN int
    SWIG_GetPtr(void *source, void **result, swig_type_info *type, swig_type_info *result_type);

    SWIGINTERN value caml_list_nth( value lst, int n );
    SWIGINTERN value caml_list_append( value lst, value elt );
    SWIGINTERN int caml_list_length( value lst );
    SWIGINTERN value caml_array_new( int n );
    SWIGINTERN void caml_array_set( value arr, int n, value item );
    SWIGINTERN value caml_array_nth( value arr, int n );
    SWIGINTERN int caml_array_len( value arr );

    SWIGINTERN value caml_val_char( char c );
    SWIGINTERN value caml_val_uchar( unsigned char c );

    SWIGINTERN value caml_val_short( short s );
    SWIGINTERN value caml_val_ushort( unsigned short s );
    
    SWIGINTERN value caml_val_int( int x );
    SWIGINTERN value caml_val_uint( unsigned int x );

    SWIGINTERN value caml_val_long( long x );
    SWIGINTERN value caml_val_ulong( unsigned long x );

    SWIGINTERN value caml_val_float( float f );
    SWIGINTERN value caml_val_double( double d );

    SWIGINTERN value caml_val_ptr( void *p, swig_type_info *descriptor );

    SWIGINTERN value caml_val_string( const char *str );
    SWIGINTERN value caml_val_string_len( const char *str, int len );

    SWIGINTERN long caml_long_val( value v );
    SWIGINTERN double caml_double_val( value v );

    SWIGINTERN int caml_ptr_val_internal( value v, void **out,
				      swig_type_info *descriptor );
    SWIGINTERN void *caml_ptr_val( value v, swig_type_info *descriptor );

    SWIGINTERN char *caml_string_val( value v );
    SWIGINTERN int caml_string_len( value v );

#ifdef __cplusplus
}
#endif

/* -*-c-*- */

/* SWIG pointer structure */

#include <string.h>
#include <assert.h>

#ifdef __cplusplus
extern "C" {
#endif

#define C_bool 0
#define C_char 1
#define C_uchar 2
#define C_short 3
#define C_ushort 4
#define C_int 5
#define C_uint 6
#define C_int32 7
#define C_int64 8
#define C_float 9
#define C_double 10
#define C_ptr 11
#define C_array 12
#define C_list 13
#define C_obj 14
#define C_string 15
#define C_enum 16
#define C_director_core 17


/* Cast a pointer if possible; returns 1 if successful */
    
    SWIGINTERN int
    SWIG_Cast (void *source, swig_type_info *source_type,
	       void **ptr, swig_type_info *dest_type)
    {
	if( !source ) { /* Special case for NULL.  This is a popular question
	     for other modules on the list, so I want an easy way out... */
	    *ptr = 0;
	    return 0;
	}

#ifdef TYPE_CAST_VERBOSE
	fprintf( stderr, "Trying to cast %s to %s\n", 
		 source_type ? source_type->str : "<none>",
		 dest_type ? dest_type->str : "<none>" );
#endif
	if (dest_type != source_type) {
	    /* We have a type mismatch.  Will have to look through our type
	       mapping table to figure out whether or not we can accept this
	       datatype. 
	       --
	       Ignore typechecks for void *.  Allow any conversion. */
	    if( !dest_type || !source_type || 
		!strcmp(dest_type->name,"_p_void") ||
		!strcmp(source_type->name,"_p_void") ) {
		*ptr = source;
		return 0;
	    } else {
		swig_cast_info *tc = 
		    SWIG_TypeCheckStruct(source_type, dest_type );
#ifdef TYPE_CAST_VERBOSE
		fprintf( stderr, "Typecheck -> %s\n",
			 tc ? tc->type->str : "<none>" );
#endif
		if( tc ) {
		    int newmemory = 0;
		    *ptr = SWIG_TypeCast(tc, source, &newmemory);
		    assert(!newmemory); /* newmemory handling not yet implemented */
		    return 0;
		} else
		    return -1;
	    }
	} else {
	    *ptr = source;
	    return 0;
	}
    }

/* Return 0 if successful. */
    SWIGINTERN int
    SWIG_GetPtr(void *inptr, void **outptr, 
		swig_type_info *intype, swig_type_info *outtype) {
	if (intype) {
	    return SWIG_Cast(inptr, intype,
			     outptr, outtype) == -1;
	} else {
	    *outptr = inptr;
	    return 0;
	}
    }

    SWIGINTERN void caml_print_list( value v );

    SWIGINTERN void caml_print_val( value v ) {
	switch( Tag_val(v) ) {
	case C_bool:
	    if( Bool_val(Field(v,0)) ) fprintf( stderr, "true " );
	    else fprintf( stderr, "false " );
	    break;
	case C_char:
	case C_uchar:
	    fprintf( stderr, "'%c' (\\%03d) ", 
		     (Int_val(Field(v,0)) >= ' ' &&
		      Int_val(Field(v,0)) < 127) ? Int_val(Field(v,0)) : '.',
		     Int_val(Field(v,0)) );
	    break;
	case C_short:
	case C_ushort:
	case C_int:
	    fprintf( stderr, "%d ", (int)caml_long_val(v) );
	    break;

	case C_uint:
	case C_int32:
	    fprintf( stderr, "%ud ", (unsigned int)caml_long_val(v) );
	    break;
	case C_int64:
	    fprintf( stderr, "%ld ", caml_long_val(v) );
	    break;
	case C_float:
	case C_double:
	    fprintf( stderr, "%f ", caml_double_val(v) );
	    break;

	case C_ptr:
	{
	    void *vout = 0;
	    swig_type_info *ty = (swig_type_info *)(long)Int64_val(Field(v,1));
	    caml_ptr_val_internal(v,&vout,0);
	    fprintf( stderr, "PTR(%p,%s) ", 
		     vout,
		     ty ? ty->name : "(null)" );
	}
	break;
	case C_array:
	{
	    unsigned int i;
	    for( i = 0; i < Wosize_val( Field(v,0) ); i++ )
		caml_print_val( Field(Field(v,0),i) );
	}
	break;
	case C_list:
	    caml_print_list( Field(v,0) );
	    break;
	case C_obj:
	    fprintf( stderr, "OBJ(%p) ", (void *)Field(v,0) );
	    break;
	case C_string:
	{
	    void *cout;
	    caml_ptr_val_internal(v,&cout,0);
	    fprintf( stderr, "'%s' ", (char *)cout );
	} 
	break;
	}
    }

    SWIGINTERN void caml_print_list( value v ) {
	CAMLparam1(v);
	while( v && Is_block(v) ) {
	    fprintf( stderr, "[ " );
	    caml_print_val( Field(v,0) );
	    fprintf( stderr, "]\n" );
	    v = Field(v,1);
	}
	CAMLreturn0;
    }

    SWIGINTERN value caml_list_nth( value lst, int n ) {
	CAMLparam1(lst);
	int i = 0;
	while( i < n && lst && Is_block(lst) ) {
	    i++; lst = Field(lst,1);
	}
	if( lst == Val_unit ) CAMLreturn(Val_unit);
	else CAMLreturn(Field(lst,0));
    }
    
    SWIGINTERN value caml_list_append( value lst, value elt ) {
	CAMLparam2(lst,elt);
	CAMLlocal3(v,vt,lh);
	lh = Val_unit;
	v = Val_unit;

	/* Appending C_void should have no effect */
	if( !Is_block(elt) ) return lst;

	while( lst && Is_block(lst) ) {
	    if( v && v != Val_unit ) {
		vt = caml_alloc_tuple(2);
		Store_field(v,1,vt);
		v = vt;
	    } else {
		v = lh = caml_alloc_tuple(2);
	    }
	    Store_field(v,0,Field(lst,0));
	    lst = Field(lst,1);
	}

	if( v && Is_block(v) ) {
	    vt = caml_alloc_tuple(2);
	    Store_field(v,1,vt);
	    v = vt;
	} else {
	    v = lh = caml_alloc_tuple(2);
	}
	Store_field(v,0,elt);
	Store_field(v,1,Val_unit);

	CAMLreturn(lh);
    }

    SWIGINTERN int caml_list_length( value lst ) {
	CAMLparam1(lst);
	int i = 0;
	while( lst && Is_block(lst) ) { i++; lst = Field(lst,1); }
	CAMLreturn(i);
    }

    SWIGINTERN void caml_array_set( value arr, int n, value item ) {
	CAMLparam2(arr,item);
	Store_field(Field(arr,0),n,item);
	CAMLreturn0;
    }

    SWIGINTERN value caml_array_nth( value arr, int n ) {
	CAMLparam1(arr);
	if( Tag_val(arr) == C_array )
	    CAMLreturn(Field(Field(arr,0),n));
	else if( Tag_val(arr) == C_list )
	    CAMLreturn(caml_list_nth(arr,0));
	else
	    caml_failwith("Need array or list");
    }

    SWIGINTERN int caml_array_len( value arr ) {
	CAMLparam1(arr);
	if( Tag_val(arr) == C_array )
	    CAMLreturn(Wosize_val(Field(arr,0)));
	else if( Tag_val(arr) == C_list )
	    CAMLreturn(caml_list_length(arr));
	else
	    caml_failwith("Need array or list");
    }

    SWIGINTERN value caml_swig_alloc(int x,int y) {
	return caml_alloc(x,y);
    }

    SWIGINTERN value caml_array_new( int n ) {
	CAMLparam0();
	CAMLlocal1(vv);
	vv = caml_swig_alloc(1,C_array);
	Store_field(vv,0,caml_alloc_tuple(n));
	CAMLreturn(vv);
    }
    
    SWIGINTERN value caml_val_bool( int b ) {
	CAMLparam0();
	CAMLlocal1(bv);
	bv = caml_swig_alloc(1,C_bool);
	Store_field(bv,0,Val_bool(b));
	CAMLreturn(bv);
    }

    SWIGINTERN value caml_val_char( char c ) {
	CAMLparam0();
	CAMLlocal1(cv);
	cv = caml_swig_alloc(1,C_char);
	Store_field(cv,0,Val_int(c));
	CAMLreturn(cv);
    }

    SWIGINTERN value caml_val_uchar( unsigned char uc ) {
	CAMLparam0();
	CAMLlocal1(ucv);
	ucv = caml_swig_alloc(1,C_uchar);
	Store_field(ucv,0,Val_int(uc));
	CAMLreturn(ucv);
    }

    SWIGINTERN value caml_val_short( short s ) {
	CAMLparam0();
	CAMLlocal1(sv);
	sv = caml_swig_alloc(1,C_short);
	Store_field(sv,0,Val_int(s));
	CAMLreturn(sv);
    }

    SWIGINTERN value caml_val_ushort( unsigned short us ) {
	CAMLparam0();
	CAMLlocal1(usv);
	usv = caml_swig_alloc(1,C_ushort);
	Store_field(usv,0,Val_int(us));
	CAMLreturn(usv);
    }

    SWIGINTERN value caml_val_int( int i ) {
	CAMLparam0();
	CAMLlocal1(iv);
	iv = caml_swig_alloc(1,C_int);
	Store_field(iv,0,Val_int(i));
	CAMLreturn(iv);
    }

    SWIGINTERN value caml_val_uint( unsigned int ui ) {
	CAMLparam0();
	CAMLlocal1(uiv);
	uiv = caml_swig_alloc(1,C_int);
	Store_field(uiv,0,Val_int(ui));
	CAMLreturn(uiv);
    }

    SWIGINTERN value caml_val_long( long l ) {
	CAMLparam0();
	CAMLlocal1(lv);
	lv = caml_swig_alloc(1,C_int64);
	Store_field(lv,0,caml_copy_int64(l));
	CAMLreturn(lv);
    }

    SWIGINTERN value caml_val_ulong( unsigned long ul ) {
	CAMLparam0();
	CAMLlocal1(ulv);
	ulv = caml_swig_alloc(1,C_int64);
	Store_field(ulv,0,caml_copy_int64(ul));
	CAMLreturn(ulv);
    }

    SWIGINTERN value caml_val_float( float f ) {
	CAMLparam0();
	CAMLlocal1(fv);
	fv = caml_swig_alloc(1,C_float);
	Store_field(fv,0,caml_copy_double((double)f));
	CAMLreturn(fv);
    }

    SWIGINTERN value caml_val_double( double d ) {
	CAMLparam0();
	CAMLlocal1(fv);
	fv = caml_swig_alloc(1,C_double);
	Store_field(fv,0,caml_copy_double(d));
	CAMLreturn(fv);
    }

    SWIGINTERN value caml_val_ptr( void *p, swig_type_info *info ) {
	CAMLparam0();
	CAMLlocal1(vv);
	vv = caml_swig_alloc(2,C_ptr);
	Store_field(vv,0,caml_copy_int64((long)p));
	Store_field(vv,1,caml_copy_int64((long)info));
	CAMLreturn(vv);
    }

    SWIGINTERN value caml_val_string( const char *p ) {
	CAMLparam0();
	CAMLlocal1(vv);
	if( !p ) CAMLreturn(caml_val_ptr( (void *)p, 0 ));
	vv = caml_swig_alloc(1,C_string);
	Store_field(vv,0,caml_copy_string(p));
	CAMLreturn(vv);
    }

    SWIGINTERN value caml_val_string_len( const char *p, int len ) {
	CAMLparam0();
	CAMLlocal1(vv);
	if( !p || len < 0 ) CAMLreturn(caml_val_ptr( (void *)p, 0 ));
	vv = caml_swig_alloc(1,C_string);
	Store_field(vv,0,caml_alloc_string(len));
	memcpy(Bp_val(Field(vv,0)),p,len);
	CAMLreturn(vv);
    }

    #define caml_val_obj(v, name) caml_val_obj_helper(v, SWIG_TypeQuery((name)), name)
    SWIGINTERN value caml_val_obj_helper( void *v, swig_type_info *type, char *name) {
	CAMLparam0();
	CAMLreturn(caml_callback2(*caml_named_value("caml_create_object_fn"),
			     caml_val_ptr(v,type),
			     caml_copy_string(name)));
    }

    SWIGINTERN long caml_long_val_full( value v, const char *name ) {
	CAMLparam1(v);
	if( !Is_block(v) ) return 0;

	switch( Tag_val(v) ) {
	case C_bool:
	case C_char:
	case C_uchar:
	case C_short:
	case C_ushort:
	case C_int:
	    CAMLreturn(Int_val(Field(v,0)));
	case C_uint:
	case C_int32:
	    CAMLreturn(Int32_val(Field(v,0)));
	case C_int64:
	    CAMLreturn((long)Int64_val(Field(v,0)));
	case C_float:
	case C_double:
	    CAMLreturn((long)Double_val(Field(v,0)));
	case C_string:
	    CAMLreturn((long)String_val(Field(v,0)));
	case C_ptr:
	    CAMLreturn((long)Int64_val(Field(Field(v,0),0)));
	case C_enum: {
	    CAMLlocal1(ret);
	    const value *enum_to_int = caml_named_value(SWIG_MODULE "_enum_to_int");
	    if( !name ) caml_failwith( "Not an enum conversion" );
	    ret = caml_callback2(*enum_to_int,*caml_named_value(name),v);
	    CAMLreturn(caml_long_val(ret));
	}
	default:
	    caml_failwith("No conversion to int");
	}
    }

    SWIGINTERN long caml_long_val( value v ) {
	return caml_long_val_full(v,0);
    }

    SWIGINTERN double caml_double_val( value v ) {
	CAMLparam1(v);
	if( !Is_block(v) ) return 0.0;
	switch( Tag_val(v) ) {
	case C_bool:
	case C_char:
	case C_uchar:
	case C_short:
	case C_ushort:
	case C_int:
	    CAMLreturnT(double, Int_val(Field(v,0)));
	case C_uint:
	case C_int32:
	    CAMLreturnT(double, Int32_val(Field(v,0)));
	case C_int64:
	    CAMLreturnT(double, Int64_val(Field(v,0)));
	case C_float:
	case C_double:
	    CAMLreturnT(double, Double_val(Field(v,0)));
	default:
	    fprintf( stderr, "Unknown block tag %d\n", Tag_val(v) );
	    caml_failwith("No conversion to double");
	}
    }

    SWIGINTERN int caml_ptr_val_internal( value v, void **out,
					  swig_type_info *descriptor ) {
	CAMLparam1(v);
	void *outptr = NULL;
        swig_type_info *outdescr = NULL;
        static const value *func_val = NULL;

	if( v == Val_unit ) {
	    *out = 0;
	    CAMLreturnT(int, 0);
	}
	if( !Is_block(v) ) return -1;
	switch( Tag_val(v) ) {
	case C_obj:
	    if (!func_val) {
	        func_val = caml_named_value("caml_obj_ptr");
	    }
	    CAMLreturnT(int, caml_ptr_val_internal(caml_callback(*func_val, v), out, descriptor));
	case C_string:
	    outptr = (void *)String_val(Field(v,0));
	    break;
	case C_ptr:
	    outptr = (void *)(long)Int64_val(Field(v,0));
	    outdescr = (swig_type_info *)(long)Int64_val(Field(v,1));
	    break;
	default:
	    *out = 0;
	    CAMLreturnT(int, 1);
	    break;
	}

	CAMLreturnT(int, SWIG_GetPtr(outptr, out, outdescr, descriptor));
    }

    SWIGINTERN void *caml_ptr_val( value v, swig_type_info *descriptor ) {
        CAMLparam0();
#ifdef TYPE_CAST_VERBOSE
	caml_print_val( v );
#endif
	void *out = NULL;
	if( !caml_ptr_val_internal( v, &out, descriptor ) )
	    CAMLreturnT(void*, out);
	else
	    caml_failwith( "No appropriate conversion found." );
    }

    SWIGINTERN char *caml_string_val( value v ) {
	return (char *)caml_ptr_val( v, 0 );
    }

    SWIGINTERN int caml_string_len( value v ) {
	switch( Tag_val(v) ) {
	case C_string:
	    return caml_string_length(Field(v,0));
	default:
	    return strlen((char *)caml_ptr_val(v,0));
	}
    }

    SWIGINTERN int caml_bool_check( value v ) {
	CAMLparam1(v);
	
	if( !Is_block(v) ) return 0;
	
	switch( Tag_val(v) ) {
	case C_bool:
	case C_ptr:
	case C_string:
	    CAMLreturn(1);
	default:
	    CAMLreturn(0);
	}
    }

    SWIGINTERN int caml_int_check( value v ) {
	CAMLparam1(v);
	
	if( !Is_block(v) ) return 0;
	
	switch( Tag_val(v) ) {
	case C_char:
	case C_uchar:
	case C_short:
	case C_ushort:
	case C_int:
	case C_uint:
	case C_int32:
	case C_int64:
	    CAMLreturn(1);

	default:
	    CAMLreturn(0);
	}
    }

    SWIGINTERN int caml_float_check( value v ) {
	CAMLparam1(v);
	if( !Is_block(v) ) return 0;

	switch( Tag_val(v) ) {
	case C_float:
	case C_double:
	    CAMLreturn(1);

	default:
	    CAMLreturn(0);
	}	
    }

    SWIGINTERN int caml_ptr_check( value v ) {
	CAMLparam1(v);
	if( !Is_block(v) ) return 0;

	switch( Tag_val(v) ) {
	case C_string:
	case C_ptr:
	case C_int64:
	    CAMLreturn(1);

	default:
	    CAMLreturn(0);
	}	
    }

    SWIGINTERN value SWIG_Ocaml_ptr_to_val(const char *name, void *ptr, swig_type_info *descriptor) {
        CAMLparam0();
        CAMLlocal1(result);

        const value *fromval = caml_named_value(name);
        if (fromval) {
            result = caml_callback(*fromval, caml_val_ptr(ptr, descriptor));
        } else {
            result = caml_val_ptr(ptr, descriptor);
        }
        CAMLreturn(result);
    }

    static swig_module_info *SWIG_Ocaml_GetModule(void *SWIGUNUSEDPARM(clientdata)) {
      value pointer;

      pointer = caml_callback(*caml_named_value("swig_find_type_info"), caml_val_int(0));
      if (Is_block(pointer) && Tag_val(pointer) == C_ptr) {
        return (swig_module_info *)(void *)(long)Int64_val(Field(pointer,0));
      }
      return 0;
    }

    static void SWIG_Ocaml_SetModule(swig_module_info *pointer) {
      value mod_pointer;

      mod_pointer = caml_val_ptr(pointer, NULL);
      caml_callback(*caml_named_value("swig_set_type_info"), mod_pointer);
    }

#ifdef __cplusplus
}
#endif

/* SWIG Errors applicable to all language modules, values are reserved from -1 to -99 */
#define  SWIG_UnknownError    	   -1
#define  SWIG_IOError        	   -2
#define  SWIG_RuntimeError   	   -3
#define  SWIG_IndexError     	   -4
#define  SWIG_TypeError      	   -5
#define  SWIG_DivisionByZero 	   -6
#define  SWIG_OverflowError  	   -7
#define  SWIG_SyntaxError    	   -8
#define  SWIG_ValueError     	   -9
#define  SWIG_SystemError    	   -10
#define  SWIG_AttributeError 	   -11
#define  SWIG_MemoryError    	   -12
#define  SWIG_NullReferenceError   -13



/* -------- TYPES TABLE (BEGIN) -------- */

#define SWIGTYPE_p_double swig_types[0]
#define SWIGTYPE_p_std__pairT_double_double_t swig_types[1]
#define SWIGTYPE_p_std__vectorT_double_t swig_types[2]
static swig_type_info *swig_types[4];
static swig_module_info swig_module = {swig_types, 3, 0, 0, 0, 0};
#define SWIG_TypeQuery(name) SWIG_TypeQueryModule(&swig_module, &swig_module, name)
#define SWIG_MangledTypeQuery(name) SWIG_MangledTypeQueryModule(&swig_module, &swig_module, name)

/* -------- TYPES TABLE (END) -------- */


#ifdef __cplusplus
#include <utility>
/* SwigValueWrapper is described in swig.swg */
template<typename T> class SwigValueWrapper {
  struct SwigSmartPointer {
    T *ptr;
    SwigSmartPointer(T *p) : ptr(p) { }
    ~SwigSmartPointer() { delete ptr; }
    SwigSmartPointer& operator=(SwigSmartPointer& rhs) { T* oldptr = ptr; ptr = 0; delete oldptr; ptr = rhs.ptr; rhs.ptr = 0; return *this; }
    void reset(T *p) { T* oldptr = ptr; ptr = 0; delete oldptr; ptr = p; }
  } pointer;
  SwigValueWrapper& operator=(const SwigValueWrapper<T>& rhs);
  SwigValueWrapper(const SwigValueWrapper<T>& rhs);
public:
  SwigValueWrapper() : pointer(0) { }
  SwigValueWrapper& operator=(const T& t) { SwigSmartPointer tmp(new T(t)); pointer = tmp; return *this; }
#if __cplusplus >=201103L
  SwigValueWrapper& operator=(T&& t) { SwigSmartPointer tmp(new T(std::move(t))); pointer = tmp; return *this; }
  operator T&&() const { return std::move(*pointer.ptr); }
#else
  operator T&() const { return *pointer.ptr; }
#endif
  T *operator&() const { return pointer.ptr; }
  static void reset(SwigValueWrapper& t, T *p) { t.pointer.reset(p); }
};

/*
 * SwigValueInit() is a generic initialisation solution as the following approach:
 * 
 *       T c_result = T();
 * 
 * doesn't compile for all types for example:
 * 
 *       unsigned int c_result = unsigned int();
 */
template <typename T> T SwigValueInit() {
  return T();
}

#if __cplusplus >=201103L
# define SWIG_STD_MOVE(OBJ) std::move(OBJ)
#else
# define SWIG_STD_MOVE(OBJ) OBJ
#endif

#endif


SWIGINTERN void SWIG_OCamlException(int code, const char *msg) {
  CAMLparam0();

  SWIG_OCamlExceptionCodes exception_code = SWIG_OCamlUnknownError;
  switch (code) {
  case SWIG_DivisionByZero:
    exception_code = SWIG_OCamlArithmeticException;
    break;
  case SWIG_IndexError:
    exception_code = SWIG_OCamlIndexOutOfBoundsException;
    break;
  case SWIG_IOError:
  case SWIG_SystemError:
    exception_code = SWIG_OCamlSystemException;
    break;
  case SWIG_MemoryError:
    exception_code = SWIG_OCamlOutOfMemoryError;
    break;
  case SWIG_OverflowError:
    exception_code = SWIG_OCamlOverflowException;
    break;
  case SWIG_RuntimeError:
    exception_code = SWIG_OCamlRuntimeException;
    break;
  case SWIG_SyntaxError:
  case SWIG_TypeError:
  case SWIG_ValueError:
    exception_code = SWIG_OCamlIllegalArgumentException;
    break;
  case SWIG_NullReferenceError:
    exception_code = SWIG_OCamlNullReferenceException;
    break;
  case SWIG_UnknownError:
  default:
    exception_code = SWIG_OCamlUnknownError;
    break;
  }
  SWIG_OCamlThrowException(exception_code, msg);
  CAMLreturn0;
}
#define SWIG_exception(code, msg) SWIG_OCamlException(code, msg)


#include <typeinfo>
#include <stdexcept>


#include <typeinfo>
#include <stdexcept>


#include <string>
SWIGINTERNINLINE
value SwigString_FromString(const std::string &s) {
  return caml_val_string((char *)s.c_str());
}

SWIGINTERNINLINE
std::string SwigString_AsString(value o) {
  return std::string((char *)caml_ptr_val(o,0));
}


#include <vector>
#include <algorithm>
#include <stdexcept>


#include <utility>

SWIGINTERN void std_vector_Sl_double_Sg__set(std::vector< double > *self,int i,double const &x){
		self->resize(i+1);
		(*self)[i] = x;
	    }
SWIGINTERN double *std_vector_Sl_double_Sg__to_array(std::vector< double > *self){
		double *array = new double[self->size() + 1];
		for( int i = 0; i < self->size(); i++ ) 
		    array[i] = (*self)[i];
		return array;
	    }

  #include "octra/octra.hpp"

SWIGEXT value _wrap_new_DPair__SWIG_0octra (value args)
{
  CAMLparam1(args);
  CAMLlocal2(swig_result,rv);
  std::pair< double,double > *result = 0 ;
  
  swig_result = Val_unit;
  result = (std::pair< double,double > *)new std::pair< double,double >();
  {
    rv = SWIG_Ocaml_ptr_to_val("create_std::pair< double,double >_from_ptr", (void *)result, SWIGTYPE_p_std__pairT_double_double_t);
  }
  swig_result = caml_list_append(swig_result,rv);
  CAMLreturn(swig_result);
}


SWIGEXT value _wrap_new_DPair__SWIG_1octra (value args)
{
  CAMLparam1(args);
  CAMLlocal2(swig_result,rv);
  double arg1 ;
  double arg2 ;
  std::pair< double,double > *result = 0 ;
  
  swig_result = Val_unit;
  {
    arg1 = caml_double_val(caml_list_nth(args,0));
  }
  {
    arg2 = caml_double_val(caml_list_nth(args,1));
  }
  result = (std::pair< double,double > *)new std::pair< double,double >(arg1,arg2);
  {
    rv = SWIG_Ocaml_ptr_to_val("create_std::pair< double,double >_from_ptr", (void *)result, SWIGTYPE_p_std__pairT_double_double_t);
  }
  swig_result = caml_list_append(swig_result,rv);
  CAMLreturn(swig_result);
}


SWIGEXT value _wrap_new_DPair__SWIG_2octra (value args)
{
  CAMLparam1(args);
  CAMLlocal2(swig_result,rv);
  std::pair< double,double > *arg1 = 0 ;
  std::pair< double,double > *result = 0 ;
  
  swig_result = Val_unit;
  {
    arg1 = (std::pair< double,double > *) caml_ptr_val(caml_list_nth(args,0),SWIGTYPE_p_std__pairT_double_double_t);
  }
  result = (std::pair< double,double > *)new std::pair< double,double >((std::pair< double,double > const &)*arg1);
  {
    rv = SWIG_Ocaml_ptr_to_val("create_std::pair< double,double >_from_ptr", (void *)result, SWIGTYPE_p_std__pairT_double_double_t);
  }
  swig_result = caml_list_append(swig_result,rv);
  CAMLreturn(swig_result);
}


SWIGEXT value _wrap_new_DPairoctra(value args) {
  CAMLparam1(args);
  int i;
  int argc = caml_list_length(args);
  
  value *argv;
  
  argv = (value *)malloc( argc * sizeof( value ) );
  for( i = 0; i < argc; i++ ) {
    argv[i] = caml_list_nth(args,i);
  }
  if (argc == 0) {
    free(argv);
    CAMLreturn(_wrap_new_DPair__SWIG_0octra(args));
  }
  if (argc == 1) {
    int _v = 0;
    {
      if (!Is_block(argv[0]) || !(Tag_val(argv[0]) == C_obj || Tag_val(argv[0]) == C_ptr)) {
        _v = 0;
      } else {
        void *ptr;
        _v = !caml_ptr_val_internal(argv[0], &ptr, SWIGTYPE_p_std__pairT_double_double_t);
      }
    }
    if (_v) {
      free(argv);
      CAMLreturn(_wrap_new_DPair__SWIG_2octra(args));
    }
  }
  if (argc == 2) {
    int _v = 0;
    {
      if( !Is_block(argv[0]) ) _v = 0;
      else {
        switch( Tag_val(argv[0]) ) {
          case C_double: _v = 1; break;
          default: _v = 0; break;
        }
      }  
    }
    if (_v) {
      {
        if( !Is_block(argv[1]) ) _v = 0;
        else {
          switch( Tag_val(argv[1]) ) {
            case C_double: _v = 1; break;
            default: _v = 0; break;
          }
        }  
      }
      if (_v) {
        free(argv);
        CAMLreturn(_wrap_new_DPair__SWIG_1octra(args));
      }
    }
  }
  
  free(argv);
  caml_failwith("Wrong number or type of arguments for overloaded function 'new_DPair'.\n"
    "  Possible C/C++ prototypes are:\n"
    "    std::pair< double,double >::pair()\n"
    "    std::pair< double,double >::pair(double,double)\n"
    "    std::pair< double,double >::pair(std::pair< double,double > const &)\n");
}


SWIGEXT value _wrap_DPair_first_setoctra (value args)
{
  CAMLparam1(args);
  CAMLlocal2(swig_result,rv);
  std::pair< double,double > *arg1 = (std::pair< double,double > *) 0 ;
  double arg2 ;
  
  if (caml_list_length(args) < 2 || caml_list_length(args) > 2) {
    caml_invalid_argument("Incorrect number of arguments passed to 'DPair_first_set'");
  }
  swig_result = Val_unit;
  {
    arg1 = (std::pair< double,double > *)caml_ptr_val(caml_list_nth(args,0),SWIGTYPE_p_std__pairT_double_double_t);
  }
  {
    arg2 = caml_double_val(caml_list_nth(args,1));
  }
  if (arg1) (arg1)->first = arg2;
  rv = Val_unit;
  swig_result = caml_list_append(swig_result,rv);
  CAMLreturn(swig_result);
}


SWIGEXT value _wrap_DPair_first_getoctra (value args)
{
  CAMLparam1(args);
  CAMLlocal2(swig_result,rv);
  std::pair< double,double > *arg1 = (std::pair< double,double > *) 0 ;
  double result;
  
  if (caml_list_length(args) < 1 || caml_list_length(args) > 1) {
    caml_invalid_argument("Incorrect number of arguments passed to 'DPair_first_get'");
  }
  swig_result = Val_unit;
  {
    arg1 = (std::pair< double,double > *)caml_ptr_val(caml_list_nth(args,0),SWIGTYPE_p_std__pairT_double_double_t);
  }
  result = (double) ((arg1)->first);
  {
    rv = caml_val_double(result);
  }
  swig_result = caml_list_append(swig_result,rv);
  CAMLreturn(swig_result);
}


SWIGEXT value _wrap_DPair_second_setoctra (value args)
{
  CAMLparam1(args);
  CAMLlocal2(swig_result,rv);
  std::pair< double,double > *arg1 = (std::pair< double,double > *) 0 ;
  double arg2 ;
  
  if (caml_list_length(args) < 2 || caml_list_length(args) > 2) {
    caml_invalid_argument("Incorrect number of arguments passed to 'DPair_second_set'");
  }
  swig_result = Val_unit;
  {
    arg1 = (std::pair< double,double > *)caml_ptr_val(caml_list_nth(args,0),SWIGTYPE_p_std__pairT_double_double_t);
  }
  {
    arg2 = caml_double_val(caml_list_nth(args,1));
  }
  if (arg1) (arg1)->second = arg2;
  rv = Val_unit;
  swig_result = caml_list_append(swig_result,rv);
  CAMLreturn(swig_result);
}


SWIGEXT value _wrap_DPair_second_getoctra (value args)
{
  CAMLparam1(args);
  CAMLlocal2(swig_result,rv);
  std::pair< double,double > *arg1 = (std::pair< double,double > *) 0 ;
  double result;
  
  if (caml_list_length(args) < 1 || caml_list_length(args) > 1) {
    caml_invalid_argument("Incorrect number of arguments passed to 'DPair_second_get'");
  }
  swig_result = Val_unit;
  {
    arg1 = (std::pair< double,double > *)caml_ptr_val(caml_list_nth(args,0),SWIGTYPE_p_std__pairT_double_double_t);
  }
  result = (double) ((arg1)->second);
  {
    rv = caml_val_double(result);
  }
  swig_result = caml_list_append(swig_result,rv);
  CAMLreturn(swig_result);
}


SWIGEXT value _wrap_delete_DPairoctra (value args)
{
  CAMLparam1(args);
  CAMLlocal2(swig_result,rv);
  std::pair< double,double > *arg1 = (std::pair< double,double > *) 0 ;
  
  if (caml_list_length(args) < 1 || caml_list_length(args) > 1) {
    caml_invalid_argument("Incorrect number of arguments passed to 'delete_DPair'");
  }
  swig_result = Val_unit;
  {
    arg1 = (std::pair< double,double > *)caml_ptr_val(caml_list_nth(args,0),SWIGTYPE_p_std__pairT_double_double_t);
  }
  delete arg1;
  rv = Val_unit;
  swig_result = caml_list_append(swig_result,rv);
  CAMLreturn(swig_result);
}


SWIGEXT value _wrap_new_DVector__SWIG_0octra (value args)
{
  CAMLparam1(args);
  CAMLlocal2(swig_result,rv);
  unsigned int arg1 ;
  std::vector< double > *result = 0 ;
  
  swig_result = Val_unit;
  {
    arg1 = caml_long_val(caml_list_nth(args,0));
  }
  result = (std::vector< double > *)new std::vector< double >(arg1);
  {
    rv = SWIG_Ocaml_ptr_to_val("create_std::vector< double >_from_ptr", (void *)result, SWIGTYPE_p_std__vectorT_double_t);
  }
  swig_result = caml_list_append(swig_result,rv);
  CAMLreturn(swig_result);
}


SWIGEXT value _wrap_new_DVector__SWIG_1octra (value args)
{
  CAMLparam1(args);
  CAMLlocal2(swig_result,rv);
  std::vector< double > *result = 0 ;
  
  swig_result = Val_unit;
  result = (std::vector< double > *)new std::vector< double >();
  {
    rv = SWIG_Ocaml_ptr_to_val("create_std::vector< double >_from_ptr", (void *)result, SWIGTYPE_p_std__vectorT_double_t);
  }
  swig_result = caml_list_append(swig_result,rv);
  CAMLreturn(swig_result);
}


SWIGEXT value _wrap_new_DVector__SWIG_2octra (value args)
{
  CAMLparam1(args);
  CAMLlocal2(swig_result,rv);
  unsigned int arg1 ;
  double *arg2 = 0 ;
  double temp2 ;
  std::vector< double > *result = 0 ;
  
  swig_result = Val_unit;
  {
    arg1 = caml_long_val(caml_list_nth(args,0));
  }
  {
    temp2 = (double) caml_double_val(caml_list_nth(args,1));
    arg2 = &temp2;
  }
  result = (std::vector< double > *)new std::vector< double >(arg1,(double const &)*arg2);
  {
    rv = SWIG_Ocaml_ptr_to_val("create_std::vector< double >_from_ptr", (void *)result, SWIGTYPE_p_std__vectorT_double_t);
  }
  swig_result = caml_list_append(swig_result,rv);
  CAMLreturn(swig_result);
}


SWIGEXT value _wrap_new_DVector__SWIG_3octra (value args)
{
  CAMLparam1(args);
  CAMLlocal2(swig_result,rv);
  std::vector< double > *arg1 = 0 ;
  std::vector< double > *result = 0 ;
  
  swig_result = Val_unit;
  {
    arg1 = (std::vector< double > *) caml_ptr_val(caml_list_nth(args,0),SWIGTYPE_p_std__vectorT_double_t);
  }
  result = (std::vector< double > *)new std::vector< double >((std::vector< double > const &)*arg1);
  {
    rv = SWIG_Ocaml_ptr_to_val("create_std::vector< double >_from_ptr", (void *)result, SWIGTYPE_p_std__vectorT_double_t);
  }
  swig_result = caml_list_append(swig_result,rv);
  CAMLreturn(swig_result);
}


SWIGEXT value _wrap_new_DVectoroctra(value args) {
  CAMLparam1(args);
  int i;
  int argc = caml_list_length(args);
  
  value *argv;
  
  argv = (value *)malloc( argc * sizeof( value ) );
  for( i = 0; i < argc; i++ ) {
    argv[i] = caml_list_nth(args,i);
  }
  if (argc == 0) {
    free(argv);
    CAMLreturn(_wrap_new_DVector__SWIG_1octra(args));
  }
  if (argc == 1) {
    int _v = 0;
    {
      if (!Is_block(argv[0]) || !(Tag_val(argv[0]) == C_obj || Tag_val(argv[0]) == C_ptr)) {
        _v = 0;
      } else {
        void *ptr;
        _v = !caml_ptr_val_internal(argv[0], &ptr, SWIGTYPE_p_std__vectorT_double_t);
      }
    }
    if (_v) {
      free(argv);
      CAMLreturn(_wrap_new_DVector__SWIG_3octra(args));
    }
  }
  if (argc == 1) {
    int _v = 0;
    {
      if( !Is_block(argv[0]) ) _v = 0;
      else {
        switch( Tag_val(argv[0]) ) {
          case C_uint: _v = 1; break;
          case C_int32: _v = 1; break;
          default: _v = 0; break;
        }
      }
    }
    if (_v) {
      free(argv);
      CAMLreturn(_wrap_new_DVector__SWIG_0octra(args));
    }
  }
  if (argc == 2) {
    int _v = 0;
    {
      if( !Is_block(argv[0]) ) _v = 0;
      else {
        switch( Tag_val(argv[0]) ) {
          case C_uint: _v = 1; break;
          case C_int32: _v = 1; break;
          default: _v = 0; break;
        }
      }
    }
    if (_v) {
      {
        if( !Is_block(argv[1]) ) _v = 0;
        else {
          switch( Tag_val(argv[1]) ) {
            case C_double: _v = 1; break;
            default: _v = 0; break;
          }
        }  
      }
      if (_v) {
        free(argv);
        CAMLreturn(_wrap_new_DVector__SWIG_2octra(args));
      }
    }
  }
  
  free(argv);
  caml_failwith("Wrong number or type of arguments for overloaded function 'new_DVector'.\n"
    "  Possible C/C++ prototypes are:\n"
    "    std::vector< double >::vector(unsigned int)\n"
    "    std::vector< double >::vector()\n"
    "    std::vector< double >::vector(unsigned int,double const &)\n"
    "    std::vector< double >::vector(std::vector< double > const &)\n");
}


SWIGEXT value _wrap_DVector_sizeoctra (value args)
{
  CAMLparam1(args);
  CAMLlocal2(swig_result,rv);
  std::vector< double > *arg1 = (std::vector< double > *) 0 ;
  unsigned int result;
  
  if (caml_list_length(args) < 1 || caml_list_length(args) > 1) {
    caml_invalid_argument("Incorrect number of arguments passed to 'DVector_size'");
  }
  swig_result = Val_unit;
  {
    arg1 = (std::vector< double > *)caml_ptr_val(caml_list_nth(args,0),SWIGTYPE_p_std__vectorT_double_t);
  }
  result = (unsigned int)((std::vector< double > const *)arg1)->size();
  {
    rv = caml_val_uint(result);
  }
  swig_result = caml_list_append(swig_result,rv);
  CAMLreturn(swig_result);
}


SWIGEXT value _wrap_DVector_emptyoctra (value args)
{
  CAMLparam1(args);
  CAMLlocal2(swig_result,rv);
  std::vector< double > *arg1 = (std::vector< double > *) 0 ;
  bool result;
  
  if (caml_list_length(args) < 1 || caml_list_length(args) > 1) {
    caml_invalid_argument("Incorrect number of arguments passed to 'DVector_empty'");
  }
  swig_result = Val_unit;
  {
    arg1 = (std::vector< double > *)caml_ptr_val(caml_list_nth(args,0),SWIGTYPE_p_std__vectorT_double_t);
  }
  result = (bool)((std::vector< double > const *)arg1)->empty();
  {
    rv = caml_val_bool(result);
  }
  swig_result = caml_list_append(swig_result,rv);
  CAMLreturn(swig_result);
}


SWIGEXT value _wrap_DVector_clearoctra (value args)
{
  CAMLparam1(args);
  CAMLlocal2(swig_result,rv);
  std::vector< double > *arg1 = (std::vector< double > *) 0 ;
  
  if (caml_list_length(args) < 1 || caml_list_length(args) > 1) {
    caml_invalid_argument("Incorrect number of arguments passed to 'DVector_clear'");
  }
  swig_result = Val_unit;
  {
    arg1 = (std::vector< double > *)caml_ptr_val(caml_list_nth(args,0),SWIGTYPE_p_std__vectorT_double_t);
  }
  (arg1)->clear();
  rv = Val_unit;
  swig_result = caml_list_append(swig_result,rv);
  CAMLreturn(swig_result);
}


SWIGEXT value _wrap_DVector_push_backoctra (value args)
{
  CAMLparam1(args);
  CAMLlocal2(swig_result,rv);
  std::vector< double > *arg1 = (std::vector< double > *) 0 ;
  double *arg2 = 0 ;
  double temp2 ;
  
  if (caml_list_length(args) < 2 || caml_list_length(args) > 2) {
    caml_invalid_argument("Incorrect number of arguments passed to 'DVector_push_back'");
  }
  swig_result = Val_unit;
  {
    arg1 = (std::vector< double > *)caml_ptr_val(caml_list_nth(args,0),SWIGTYPE_p_std__vectorT_double_t);
  }
  {
    temp2 = (double) caml_double_val(caml_list_nth(args,1));
    arg2 = &temp2;
  }
  (arg1)->push_back((double const &)*arg2);
  rv = Val_unit;
  swig_result = caml_list_append(swig_result,rv);
  CAMLreturn(swig_result);
}


SWIGEXT value _wrap_DVector_operator_bB___octra (value args)
{
  CAMLparam1(args);
  CAMLlocal2(swig_result,rv);
  std::vector< double > *arg1 = (std::vector< double > *) 0 ;
  int arg2 ;
  double result;
  
  if (caml_list_length(args) < 2 || caml_list_length(args) > 2) {
    caml_invalid_argument("Incorrect number of arguments passed to 'DVector_operator []'");
  }
  swig_result = Val_unit;
  {
    arg1 = (std::vector< double > *)caml_ptr_val(caml_list_nth(args,0),SWIGTYPE_p_std__vectorT_double_t);
  }
  {
    arg2 = caml_long_val(caml_list_nth(args,1));
  }
  result = (double)(arg1)->operator [](arg2);
  {
    rv = caml_val_double(result);
  }
  swig_result = caml_list_append(swig_result,rv);
  CAMLreturn(swig_result);
}


SWIGEXT value _wrap_DVector_operator_e___octra (value args)
{
  CAMLparam1(args);
  CAMLlocal2(swig_result,rv);
  std::vector< double > *arg1 = (std::vector< double > *) 0 ;
  std::vector< double > *arg2 = 0 ;
  std::vector< double > *result = 0 ;
  
  if (caml_list_length(args) < 2 || caml_list_length(args) > 2) {
    caml_invalid_argument("Incorrect number of arguments passed to 'DVector_operator ='");
  }
  swig_result = Val_unit;
  {
    arg1 = (std::vector< double > *)caml_ptr_val(caml_list_nth(args,0),SWIGTYPE_p_std__vectorT_double_t);
  }
  {
    arg2 = (std::vector< double > *) caml_ptr_val(caml_list_nth(args,1),SWIGTYPE_p_std__vectorT_double_t);
  }
  result = (std::vector< double > *) &(arg1)->operator =(*arg2);
  {
    rv = SWIG_Ocaml_ptr_to_val("create_std::vector< double >_from_ptr", (void *)result, SWIGTYPE_p_std__vectorT_double_t);
  }
  swig_result = caml_list_append(swig_result,rv);
  CAMLreturn(swig_result);
}


SWIGEXT value _wrap_DVector_setoctra (value args)
{
  CAMLparam1(args);
  CAMLlocal2(swig_result,rv);
  std::vector< double > *arg1 = (std::vector< double > *) 0 ;
  int arg2 ;
  double *arg3 = 0 ;
  double temp3 ;
  
  if (caml_list_length(args) < 3 || caml_list_length(args) > 3) {
    caml_invalid_argument("Incorrect number of arguments passed to 'DVector_set'");
  }
  swig_result = Val_unit;
  {
    arg1 = (std::vector< double > *)caml_ptr_val(caml_list_nth(args,0),SWIGTYPE_p_std__vectorT_double_t);
  }
  {
    arg2 = caml_long_val(caml_list_nth(args,1));
  }
  {
    temp3 = (double) caml_double_val(caml_list_nth(args,2));
    arg3 = &temp3;
  }
  std_vector_Sl_double_Sg__set(arg1,arg2,(double const &)*arg3);
  rv = Val_unit;
  swig_result = caml_list_append(swig_result,rv);
  CAMLreturn(swig_result);
}


SWIGEXT value _wrap_DVector_to_arrayoctra (value args)
{
  CAMLparam1(args);
  CAMLlocal2(swig_result,rv);
  std::vector< double > *arg1 = (std::vector< double > *) 0 ;
  double *result = 0 ;
  
  if (caml_list_length(args) < 1 || caml_list_length(args) > 1) {
    caml_invalid_argument("Incorrect number of arguments passed to 'DVector_to_array'");
  }
  swig_result = Val_unit;
  {
    arg1 = (std::vector< double > *)caml_ptr_val(caml_list_nth(args,0),SWIGTYPE_p_std__vectorT_double_t);
  }
  result = (double *)std_vector_Sl_double_Sg__to_array(arg1);
  {
    rv = SWIG_Ocaml_ptr_to_val("create_double_from_ptr", (void *)result, SWIGTYPE_p_double);
  }
  swig_result = caml_list_append(swig_result,rv);
  CAMLreturn(swig_result);
}


SWIGEXT value _wrap_delete_DVectoroctra (value args)
{
  CAMLparam1(args);
  CAMLlocal2(swig_result,rv);
  std::vector< double > *arg1 = (std::vector< double > *) 0 ;
  
  if (caml_list_length(args) < 1 || caml_list_length(args) > 1) {
    caml_invalid_argument("Incorrect number of arguments passed to 'delete_DVector'");
  }
  swig_result = Val_unit;
  {
    arg1 = (std::vector< double > *)caml_ptr_val(caml_list_nth(args,0),SWIGTYPE_p_std__vectorT_double_t);
  }
  delete arg1;
  rv = Val_unit;
  swig_result = caml_list_append(swig_result,rv);
  CAMLreturn(swig_result);
}


SWIGEXT value _wrap_hellooctra (value args)
{
  CAMLparam1(args);
  CAMLlocal2(swig_result,rv);
  
  if (caml_list_length(args) > 0) caml_invalid_argument("'hello' takes no arguments");
  swig_result = Val_unit;
  octra::hello();
  rv = Val_unit;
  swig_result = caml_list_append(swig_result,rv);
  CAMLreturn(swig_result);
}


SWIGEXT value _wrap_make_dvectoroctra (value args)
{
  CAMLparam1(args);
  CAMLlocal2(swig_result,rv);
  double arg1 ;
  double arg2 ;
  double arg3 ;
  std::vector< double > result;
  
  if (caml_list_length(args) < 3 || caml_list_length(args) > 3) {
    caml_invalid_argument("Incorrect number of arguments passed to 'make_dvector'");
  }
  swig_result = Val_unit;
  {
    arg1 = caml_double_val(caml_list_nth(args,0));
  }
  {
    arg2 = caml_double_val(caml_list_nth(args,1));
  }
  {
    arg3 = caml_double_val(caml_list_nth(args,2));
  }
  result = octra::make_dvector(arg1,arg2,arg3);
  {
    std::vector< double > * temp = new std::vector< double >(result);
    rv = SWIG_Ocaml_ptr_to_val("create_std::vector< double >_from_ptr", (void *)temp, SWIGTYPE_p_std__vectorT_double_t);
  }
  swig_result = caml_list_append(swig_result,rv);
  CAMLreturn(swig_result);
}


SWIGEXT value _wrap_sum_dvectoroctra (value args)
{
  CAMLparam1(args);
  CAMLlocal2(swig_result,rv);
  std::vector< double > *arg1 = 0 ;
  double result;
  
  if (caml_list_length(args) < 1 || caml_list_length(args) > 1) {
    caml_invalid_argument("Incorrect number of arguments passed to 'sum_dvector'");
  }
  swig_result = Val_unit;
  {
    arg1 = (std::vector< double > *) caml_ptr_val(caml_list_nth(args,0),SWIGTYPE_p_std__vectorT_double_t);
  }
  result = (double)octra::sum_dvector((std::vector< double > const &)*arg1);
  {
    rv = caml_val_double(result);
  }
  swig_result = caml_list_append(swig_result,rv);
  CAMLreturn(swig_result);
}


SWIGEXT value _wrap_make_dpairoctra (value args)
{
  CAMLparam1(args);
  CAMLlocal2(swig_result,rv);
  double arg1 ;
  double arg2 ;
  std::pair< double,double > result;
  
  if (caml_list_length(args) < 2 || caml_list_length(args) > 2) {
    caml_invalid_argument("Incorrect number of arguments passed to 'make_dpair'");
  }
  swig_result = Val_unit;
  {
    arg1 = caml_double_val(caml_list_nth(args,0));
  }
  {
    arg2 = caml_double_val(caml_list_nth(args,1));
  }
  result = octra::make_dpair(arg1,arg2);
  {
    std::pair< double,double > * temp = new std::pair< double,double >(result);
    rv = SWIG_Ocaml_ptr_to_val("create_std::pair< double,double >_from_ptr", (void *)temp, SWIGTYPE_p_std__pairT_double_double_t);
  }
  swig_result = caml_list_append(swig_result,rv);
  CAMLreturn(swig_result);
}


SWIGEXT value _wrap_sum_dpairoctra (value args)
{
  CAMLparam1(args);
  CAMLlocal2(swig_result,rv);
  std::pair< double,double > *arg1 = 0 ;
  double result;
  
  if (caml_list_length(args) < 1 || caml_list_length(args) > 1) {
    caml_invalid_argument("Incorrect number of arguments passed to 'sum_dpair'");
  }
  swig_result = Val_unit;
  {
    arg1 = (std::pair< double,double > *) caml_ptr_val(caml_list_nth(args,0),SWIGTYPE_p_std__pairT_double_double_t);
  }
  result = (double)octra::sum_dpair((std::pair< double,double > const &)*arg1);
  {
    rv = caml_val_double(result);
  }
  swig_result = caml_list_append(swig_result,rv);
  CAMLreturn(swig_result);
}



/* -------- TYPE CONVERSION AND EQUIVALENCE RULES (BEGIN) -------- */

static swig_type_info _swigt__p_double = {"_p_double", "double *", 0, 0, (void*)0, 0};
static swig_type_info _swigt__p_std__pairT_double_double_t = {"_p_std__pairT_double_double_t", "std::pair< double,double > *", 0, 0, (void*)0, 0};
static swig_type_info _swigt__p_std__vectorT_double_t = {"_p_std__vectorT_double_t", "std::vector< double > *", 0, 0, (void*)0, 0};

static swig_type_info *swig_type_initial[] = {
  &_swigt__p_double,
  &_swigt__p_std__pairT_double_double_t,
  &_swigt__p_std__vectorT_double_t,
};

static swig_cast_info _swigc__p_double[] = {  {&_swigt__p_double, 0, 0, 0},{0, 0, 0, 0}};
static swig_cast_info _swigc__p_std__pairT_double_double_t[] = {  {&_swigt__p_std__pairT_double_double_t, 0, 0, 0},{0, 0, 0, 0}};
static swig_cast_info _swigc__p_std__vectorT_double_t[] = {  {&_swigt__p_std__vectorT_double_t, 0, 0, 0},{0, 0, 0, 0}};

static swig_cast_info *swig_cast_initial[] = {
  _swigc__p_double,
  _swigc__p_std__pairT_double_double_t,
  _swigc__p_std__vectorT_double_t,
};


/* -------- TYPE CONVERSION AND EQUIVALENCE RULES (END) -------- */

#define SWIG_init f_octra_init
/* -----------------------------------------------------------------------------
 * Type initialization:
 * This problem is tough by the requirement that no dynamic
 * memory is used. Also, since swig_type_info structures store pointers to
 * swig_cast_info structures and swig_cast_info structures store pointers back
 * to swig_type_info structures, we need some lookup code at initialization.
 * The idea is that swig generates all the structures that are needed.
 * The runtime then collects these partially filled structures.
 * The SWIG_InitializeModule function takes these initial arrays out of
 * swig_module, and does all the lookup, filling in the swig_module.types
 * array with the correct data and linking the correct swig_cast_info
 * structures together.
 *
 * The generated swig_type_info structures are assigned statically to an initial
 * array. We just loop through that array, and handle each type individually.
 * First we lookup if this type has been already loaded, and if so, use the
 * loaded structure instead of the generated one. Then we have to fill in the
 * cast linked list. The cast data is initially stored in something like a
 * two-dimensional array. Each row corresponds to a type (there are the same
 * number of rows as there are in the swig_type_initial array). Each entry in
 * a column is one of the swig_cast_info structures for that type.
 * The cast_initial array is actually an array of arrays, because each row has
 * a variable number of columns. So to actually build the cast linked list,
 * we find the array of casts associated with the type, and loop through it
 * adding the casts to the list. The one last trick we need to do is making
 * sure the type pointer in the swig_cast_info struct is correct.
 *
 * First off, we lookup the cast->type name to see if it is already loaded.
 * There are three cases to handle:
 *  1) If the cast->type has already been loaded AND the type we are adding
 *     casting info to has not been loaded (it is in this module), THEN we
 *     replace the cast->type pointer with the type pointer that has already
 *     been loaded.
 *  2) If BOTH types (the one we are adding casting info to, and the
 *     cast->type) are loaded, THEN the cast info has already been loaded by
 *     the previous module so we just ignore it.
 *  3) Finally, if cast->type has not already been loaded, then we add that
 *     swig_cast_info to the linked list (because the cast->type) pointer will
 *     be correct.
 * ----------------------------------------------------------------------------- */

#ifdef __cplusplus
extern "C" {
#if 0
} /* c-mode */
#endif
#endif

#if 0
#define SWIGRUNTIME_DEBUG
#endif

#ifndef SWIG_INIT_CLIENT_DATA_TYPE
#define SWIG_INIT_CLIENT_DATA_TYPE void *
#endif

SWIGRUNTIME void
SWIG_InitializeModule(SWIG_INIT_CLIENT_DATA_TYPE clientdata) {
  size_t i;
  swig_module_info *module_head, *iter;
  int init;
  
  /* check to see if the circular list has been setup, if not, set it up */
  if (swig_module.next==0) {
    /* Initialize the swig_module */
    swig_module.type_initial = swig_type_initial;
    swig_module.cast_initial = swig_cast_initial;
    swig_module.next = &swig_module;
    init = 1;
  } else {
    init = 0;
  }
  
  /* Try and load any already created modules */
  module_head = SWIG_GetModule(clientdata);
  if (!module_head) {
    /* This is the first module loaded for this interpreter */
    /* so set the swig module into the interpreter */
    SWIG_SetModule(clientdata, &swig_module);
  } else {
    /* the interpreter has loaded a SWIG module, but has it loaded this one? */
    iter=module_head;
    do {
      if (iter==&swig_module) {
        /* Our module is already in the list, so there's nothing more to do. */
        return;
      }
      iter=iter->next;
    } while (iter!= module_head);
    
    /* otherwise we must add our module into the list */
    swig_module.next = module_head->next;
    module_head->next = &swig_module;
  }
  
  /* When multiple interpreters are used, a module could have already been initialized in
       a different interpreter, but not yet have a pointer in this interpreter.
       In this case, we do not want to continue adding types... everything should be
       set up already */
  if (init == 0) return;
  
  /* Now work on filling in swig_module.types */
#ifdef SWIGRUNTIME_DEBUG
  printf("SWIG_InitializeModule: size %lu\n", (unsigned long)swig_module.size);
#endif
  for (i = 0; i < swig_module.size; ++i) {
    swig_type_info *type = 0;
    swig_type_info *ret;
    swig_cast_info *cast;
    
#ifdef SWIGRUNTIME_DEBUG
    printf("SWIG_InitializeModule: type %lu %s\n", (unsigned long)i, swig_module.type_initial[i]->name);
#endif
    
    /* if there is another module already loaded */
    if (swig_module.next != &swig_module) {
      type = SWIG_MangledTypeQueryModule(swig_module.next, &swig_module, swig_module.type_initial[i]->name);
    }
    if (type) {
      /* Overwrite clientdata field */
#ifdef SWIGRUNTIME_DEBUG
      printf("SWIG_InitializeModule: found type %s\n", type->name);
#endif
      if (swig_module.type_initial[i]->clientdata) {
        type->clientdata = swig_module.type_initial[i]->clientdata;
#ifdef SWIGRUNTIME_DEBUG
        printf("SWIG_InitializeModule: found and overwrite type %s \n", type->name);
#endif
      }
    } else {
      type = swig_module.type_initial[i];
    }
    
    /* Insert casting types */
    cast = swig_module.cast_initial[i];
    while (cast->type) {
      /* Don't need to add information already in the list */
      ret = 0;
#ifdef SWIGRUNTIME_DEBUG
      printf("SWIG_InitializeModule: look cast %s\n", cast->type->name);
#endif
      if (swig_module.next != &swig_module) {
        ret = SWIG_MangledTypeQueryModule(swig_module.next, &swig_module, cast->type->name);
#ifdef SWIGRUNTIME_DEBUG
        if (ret) printf("SWIG_InitializeModule: found cast %s\n", ret->name);
#endif
      }
      if (ret) {
        if (type == swig_module.type_initial[i]) {
#ifdef SWIGRUNTIME_DEBUG
          printf("SWIG_InitializeModule: skip old type %s\n", ret->name);
#endif
          cast->type = ret;
          ret = 0;
        } else {
          /* Check for casting already in the list */
          swig_cast_info *ocast = SWIG_TypeCheck(ret->name, type);
#ifdef SWIGRUNTIME_DEBUG
          if (ocast) printf("SWIG_InitializeModule: skip old cast %s\n", ret->name);
#endif
          if (!ocast) ret = 0;
        }
      }
      
      if (!ret) {
#ifdef SWIGRUNTIME_DEBUG
        printf("SWIG_InitializeModule: adding cast %s\n", cast->type->name);
#endif
        if (type->cast) {
          type->cast->prev = cast;
          cast->next = type->cast;
        }
        type->cast = cast;
      }
      cast++;
    }
    /* Set entry in modules->types array equal to the type */
    swig_module.types[i] = type;
  }
  swig_module.types[i] = 0;
  
#ifdef SWIGRUNTIME_DEBUG
  printf("**** SWIG_InitializeModule: Cast List ******\n");
  for (i = 0; i < swig_module.size; ++i) {
    int j = 0;
    swig_cast_info *cast = swig_module.cast_initial[i];
    printf("SWIG_InitializeModule: type %lu %s\n", (unsigned long)i, swig_module.type_initial[i]->name);
    while (cast->type) {
      printf("SWIG_InitializeModule: cast type %s\n", cast->type->name);
      cast++;
      ++j;
    }
    printf("---- Total casts: %d\n",j);
  }
  printf("**** SWIG_InitializeModule: Cast List ******\n");
#endif
}

/* This function will propagate the clientdata field of type to
* any new swig_type_info structures that have been added into the list
* of equivalent types.  It is like calling
* SWIG_TypeClientData(type, clientdata) a second time.
*/
SWIGRUNTIME void
SWIG_PropagateClientData(void) {
  size_t i;
  swig_cast_info *equiv;
  static int init_run = 0;
  
  if (init_run) return;
  init_run = 1;
  
  for (i = 0; i < swig_module.size; i++) {
    if (swig_module.types[i]->clientdata) {
      equiv = swig_module.types[i]->cast;
      while (equiv) {
        if (!equiv->converter) {
          if (equiv->type && !equiv->type->clientdata)
          SWIG_TypeClientData(equiv->type, swig_module.types[i]->clientdata);
        }
        equiv = equiv->next;
      }
    }
  }
}

#ifdef __cplusplus
#if 0
{
  /* c-mode */
#endif
}
#endif

SWIGEXT void SWIG_init() {
  SWIG_InitializeModule(0);
  
}

