/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_Octruby_WRAP_H_
#define SWIG_Octruby_WRAP_H_

namespace Swig {
  class Director;
}


class SwigDirector_Callback : public octra::Callback, public Swig::Director {

public:
    SwigDirector_Callback(VALUE self);
    virtual ~SwigDirector_Callback();
    virtual double call(double x);
};


#endif
