//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG JSE (https://www.swig.org).
// Version 5.0.6
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class IPair : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal IPair(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(IPair obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(IPair obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~IPair() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          octraPINVOKE.delete_IPair(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public IPair() : this(octraPINVOKE.new_IPair__SWIG_0(), true) {
  }

  public IPair(int first, int second) : this(octraPINVOKE.new_IPair__SWIG_1(first, second), true) {
  }

  public IPair(IPair other) : this(octraPINVOKE.new_IPair__SWIG_2(IPair.getCPtr(other)), true) {
    if (octraPINVOKE.SWIGPendingException.Pending) throw octraPINVOKE.SWIGPendingException.Retrieve();
  }

  public int first {
    set {
      octraPINVOKE.IPair_first_set(swigCPtr, value);
    } 
    get {
      int ret = octraPINVOKE.IPair_first_get(swigCPtr);
      return ret;
    } 
  }

  public int second {
    set {
      octraPINVOKE.IPair_second_set(swigCPtr, value);
    } 
    get {
      int ret = octraPINVOKE.IPair_second_get(swigCPtr);
      return ret;
    } 
  }

}
