//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG JSE (https://www.swig.org).
// Version 5.0.6
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class SPair : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal SPair(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(SPair obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(SPair obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~SPair() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          octraPINVOKE.delete_SPair(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public SPair() : this(octraPINVOKE.new_SPair__SWIG_0(), true) {
  }

  public SPair(string first, string second) : this(octraPINVOKE.new_SPair__SWIG_1(first, second), true) {
    if (octraPINVOKE.SWIGPendingException.Pending) throw octraPINVOKE.SWIGPendingException.Retrieve();
  }

  public SPair(SPair other) : this(octraPINVOKE.new_SPair__SWIG_2(SPair.getCPtr(other)), true) {
    if (octraPINVOKE.SWIGPendingException.Pending) throw octraPINVOKE.SWIGPendingException.Retrieve();
  }

  public string first {
    set {
      octraPINVOKE.SPair_first_set(swigCPtr, value);
      if (octraPINVOKE.SWIGPendingException.Pending) throw octraPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = octraPINVOKE.SPair_first_get(swigCPtr);
      if (octraPINVOKE.SWIGPendingException.Pending) throw octraPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public string second {
    set {
      octraPINVOKE.SPair_second_set(swigCPtr, value);
      if (octraPINVOKE.SWIGPendingException.Pending) throw octraPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = octraPINVOKE.SPair_second_get(swigCPtr);
      if (octraPINVOKE.SWIGPendingException.Pending) throw octraPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

}
