# This file was automatically generated by SWIG JSE (https://www.swig.org).
# Version 5.0.6
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if getattr(globals().get("__spec__"), "parent", None) or __package__ or "." in __name__:
    from . import _octra
else:
    import _octra

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


SHARED_PTR_DISOWN = _octra.SHARED_PTR_DISOWN
class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _octra.delete_SwigPyIterator

    def value(self):
        return _octra.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _octra.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _octra.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _octra.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _octra.SwigPyIterator_equal(self, x)

    def copy(self):
        return _octra.SwigPyIterator_copy(self)

    def next(self):
        return _octra.SwigPyIterator_next(self)

    def __next__(self):
        return _octra.SwigPyIterator___next__(self)

    def previous(self):
        return _octra.SwigPyIterator_previous(self)

    def advance(self, n):
        return _octra.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _octra.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _octra.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _octra.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _octra.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _octra.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _octra.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _octra:
_octra.SwigPyIterator_swigregister(SwigPyIterator)
STD_STRINGS_BODY_SECTION = _octra.STD_STRINGS_BODY_SECTION
class IPair(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _octra.IPair_swiginit(self, _octra.new_IPair(*args))
    first = property(_octra.IPair_first_get, _octra.IPair_first_set)
    second = property(_octra.IPair_second_get, _octra.IPair_second_set)
    def __len__(self):
        return 2
    def __repr__(self):
        return str((self.first, self.second))
    def __getitem__(self, index): 
        if not (index % 2):
            return self.first
        else:
            return self.second
    def __setitem__(self, index, val):
        if not (index % 2):
            self.first = val
        else:
            self.second = val
    __swig_destroy__ = _octra.delete_IPair

# Register IPair in _octra:
_octra.IPair_swigregister(IPair)
class DPair(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _octra.DPair_swiginit(self, _octra.new_DPair(*args))
    first = property(_octra.DPair_first_get, _octra.DPair_first_set)
    second = property(_octra.DPair_second_get, _octra.DPair_second_set)
    def __len__(self):
        return 2
    def __repr__(self):
        return str((self.first, self.second))
    def __getitem__(self, index): 
        if not (index % 2):
            return self.first
        else:
            return self.second
    def __setitem__(self, index, val):
        if not (index % 2):
            self.first = val
        else:
            self.second = val
    __swig_destroy__ = _octra.delete_DPair

# Register DPair in _octra:
_octra.DPair_swigregister(DPair)
class SPair(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _octra.SPair_swiginit(self, _octra.new_SPair(*args))
    first = property(_octra.SPair_first_get, _octra.SPair_first_set)
    second = property(_octra.SPair_second_get, _octra.SPair_second_set)
    def __len__(self):
        return 2
    def __repr__(self):
        return str((self.first, self.second))
    def __getitem__(self, index): 
        if not (index % 2):
            return self.first
        else:
            return self.second
    def __setitem__(self, index, val):
        if not (index % 2):
            self.first = val
        else:
            self.second = val
    __swig_destroy__ = _octra.delete_SPair

# Register SPair in _octra:
_octra.SPair_swigregister(SPair)
class IVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _octra.IVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _octra.IVector___nonzero__(self)

    def __bool__(self):
        return _octra.IVector___bool__(self)

    def __len__(self):
        return _octra.IVector___len__(self)

    def __getslice__(self, i, j):
        return _octra.IVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _octra.IVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _octra.IVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _octra.IVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _octra.IVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _octra.IVector___setitem__(self, *args)

    def pop(self):
        return _octra.IVector_pop(self)

    def append(self, x):
        return _octra.IVector_append(self, x)

    def empty(self):
        return _octra.IVector_empty(self)

    def size(self):
        return _octra.IVector_size(self)

    def swap(self, v):
        return _octra.IVector_swap(self, v)

    def begin(self):
        return _octra.IVector_begin(self)

    def end(self):
        return _octra.IVector_end(self)

    def rbegin(self):
        return _octra.IVector_rbegin(self)

    def rend(self):
        return _octra.IVector_rend(self)

    def clear(self):
        return _octra.IVector_clear(self)

    def get_allocator(self):
        return _octra.IVector_get_allocator(self)

    def pop_back(self):
        return _octra.IVector_pop_back(self)

    def erase(self, *args):
        return _octra.IVector_erase(self, *args)

    def __init__(self, *args):
        _octra.IVector_swiginit(self, _octra.new_IVector(*args))

    def push_back(self, x):
        return _octra.IVector_push_back(self, x)

    def front(self):
        return _octra.IVector_front(self)

    def back(self):
        return _octra.IVector_back(self)

    def assign(self, n, x):
        return _octra.IVector_assign(self, n, x)

    def resize(self, *args):
        return _octra.IVector_resize(self, *args)

    def insert(self, *args):
        return _octra.IVector_insert(self, *args)

    def reserve(self, n):
        return _octra.IVector_reserve(self, n)

    def capacity(self):
        return _octra.IVector_capacity(self)
    __swig_destroy__ = _octra.delete_IVector

# Register IVector in _octra:
_octra.IVector_swigregister(IVector)
class DVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _octra.DVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _octra.DVector___nonzero__(self)

    def __bool__(self):
        return _octra.DVector___bool__(self)

    def __len__(self):
        return _octra.DVector___len__(self)

    def __getslice__(self, i, j):
        return _octra.DVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _octra.DVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _octra.DVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _octra.DVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _octra.DVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _octra.DVector___setitem__(self, *args)

    def pop(self):
        return _octra.DVector_pop(self)

    def append(self, x):
        return _octra.DVector_append(self, x)

    def empty(self):
        return _octra.DVector_empty(self)

    def size(self):
        return _octra.DVector_size(self)

    def swap(self, v):
        return _octra.DVector_swap(self, v)

    def begin(self):
        return _octra.DVector_begin(self)

    def end(self):
        return _octra.DVector_end(self)

    def rbegin(self):
        return _octra.DVector_rbegin(self)

    def rend(self):
        return _octra.DVector_rend(self)

    def clear(self):
        return _octra.DVector_clear(self)

    def get_allocator(self):
        return _octra.DVector_get_allocator(self)

    def pop_back(self):
        return _octra.DVector_pop_back(self)

    def erase(self, *args):
        return _octra.DVector_erase(self, *args)

    def __init__(self, *args):
        _octra.DVector_swiginit(self, _octra.new_DVector(*args))

    def push_back(self, x):
        return _octra.DVector_push_back(self, x)

    def front(self):
        return _octra.DVector_front(self)

    def back(self):
        return _octra.DVector_back(self)

    def assign(self, n, x):
        return _octra.DVector_assign(self, n, x)

    def resize(self, *args):
        return _octra.DVector_resize(self, *args)

    def insert(self, *args):
        return _octra.DVector_insert(self, *args)

    def reserve(self, n):
        return _octra.DVector_reserve(self, n)

    def capacity(self):
        return _octra.DVector_capacity(self)
    __swig_destroy__ = _octra.delete_DVector

# Register DVector in _octra:
_octra.DVector_swigregister(DVector)
class SizeVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _octra.SizeVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _octra.SizeVector___nonzero__(self)

    def __bool__(self):
        return _octra.SizeVector___bool__(self)

    def __len__(self):
        return _octra.SizeVector___len__(self)

    def __getslice__(self, i, j):
        return _octra.SizeVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _octra.SizeVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _octra.SizeVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _octra.SizeVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _octra.SizeVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _octra.SizeVector___setitem__(self, *args)

    def pop(self):
        return _octra.SizeVector_pop(self)

    def append(self, x):
        return _octra.SizeVector_append(self, x)

    def empty(self):
        return _octra.SizeVector_empty(self)

    def size(self):
        return _octra.SizeVector_size(self)

    def swap(self, v):
        return _octra.SizeVector_swap(self, v)

    def begin(self):
        return _octra.SizeVector_begin(self)

    def end(self):
        return _octra.SizeVector_end(self)

    def rbegin(self):
        return _octra.SizeVector_rbegin(self)

    def rend(self):
        return _octra.SizeVector_rend(self)

    def clear(self):
        return _octra.SizeVector_clear(self)

    def get_allocator(self):
        return _octra.SizeVector_get_allocator(self)

    def pop_back(self):
        return _octra.SizeVector_pop_back(self)

    def erase(self, *args):
        return _octra.SizeVector_erase(self, *args)

    def __init__(self, *args):
        _octra.SizeVector_swiginit(self, _octra.new_SizeVector(*args))

    def push_back(self, x):
        return _octra.SizeVector_push_back(self, x)

    def front(self):
        return _octra.SizeVector_front(self)

    def back(self):
        return _octra.SizeVector_back(self)

    def assign(self, n, x):
        return _octra.SizeVector_assign(self, n, x)

    def resize(self, *args):
        return _octra.SizeVector_resize(self, *args)

    def insert(self, *args):
        return _octra.SizeVector_insert(self, *args)

    def reserve(self, n):
        return _octra.SizeVector_reserve(self, n)

    def capacity(self):
        return _octra.SizeVector_capacity(self)
    __swig_destroy__ = _octra.delete_SizeVector

# Register SizeVector in _octra:
_octra.SizeVector_swigregister(SizeVector)
class SVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _octra.SVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _octra.SVector___nonzero__(self)

    def __bool__(self):
        return _octra.SVector___bool__(self)

    def __len__(self):
        return _octra.SVector___len__(self)

    def __getslice__(self, i, j):
        return _octra.SVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _octra.SVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _octra.SVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _octra.SVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _octra.SVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _octra.SVector___setitem__(self, *args)

    def pop(self):
        return _octra.SVector_pop(self)

    def append(self, x):
        return _octra.SVector_append(self, x)

    def empty(self):
        return _octra.SVector_empty(self)

    def size(self):
        return _octra.SVector_size(self)

    def swap(self, v):
        return _octra.SVector_swap(self, v)

    def begin(self):
        return _octra.SVector_begin(self)

    def end(self):
        return _octra.SVector_end(self)

    def rbegin(self):
        return _octra.SVector_rbegin(self)

    def rend(self):
        return _octra.SVector_rend(self)

    def clear(self):
        return _octra.SVector_clear(self)

    def get_allocator(self):
        return _octra.SVector_get_allocator(self)

    def pop_back(self):
        return _octra.SVector_pop_back(self)

    def erase(self, *args):
        return _octra.SVector_erase(self, *args)

    def __init__(self, *args):
        _octra.SVector_swiginit(self, _octra.new_SVector(*args))

    def push_back(self, x):
        return _octra.SVector_push_back(self, x)

    def front(self):
        return _octra.SVector_front(self)

    def back(self):
        return _octra.SVector_back(self)

    def assign(self, n, x):
        return _octra.SVector_assign(self, n, x)

    def resize(self, *args):
        return _octra.SVector_resize(self, *args)

    def insert(self, *args):
        return _octra.SVector_insert(self, *args)

    def reserve(self, n):
        return _octra.SVector_reserve(self, n)

    def capacity(self):
        return _octra.SVector_capacity(self)
    __swig_destroy__ = _octra.delete_SVector

# Register SVector in _octra:
_octra.SVector_swigregister(SVector)

def hello():
    return _octra.hello()

