/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG JSE (https://www.swig.org).
 * Version 5.0.6
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package js.octra.joctra;

public class octraJNI {
  public final static native long new_IPair__SWIG_0();
  public final static native long new_IPair__SWIG_1(int jarg1, int jarg2);
  public final static native long new_IPair__SWIG_2(long jarg1, IPair jarg1_);
  public final static native void IPair_first_set(long jarg1, IPair jarg1_, int jarg2);
  public final static native int IPair_first_get(long jarg1, IPair jarg1_);
  public final static native void IPair_second_set(long jarg1, IPair jarg1_, int jarg2);
  public final static native int IPair_second_get(long jarg1, IPair jarg1_);
  public final static native void delete_IPair(long jarg1);
  public final static native long new_DPair__SWIG_0();
  public final static native long new_DPair__SWIG_1(double jarg1, double jarg2);
  public final static native long new_DPair__SWIG_2(long jarg1, DPair jarg1_);
  public final static native void DPair_first_set(long jarg1, DPair jarg1_, double jarg2);
  public final static native double DPair_first_get(long jarg1, DPair jarg1_);
  public final static native void DPair_second_set(long jarg1, DPair jarg1_, double jarg2);
  public final static native double DPair_second_get(long jarg1, DPair jarg1_);
  public final static native void delete_DPair(long jarg1);
  public final static native long new_SPair__SWIG_0();
  public final static native long new_SPair__SWIG_1(String jarg1, String jarg2);
  public final static native long new_SPair__SWIG_2(long jarg1, SPair jarg1_);
  public final static native void SPair_first_set(long jarg1, SPair jarg1_, String jarg2);
  public final static native String SPair_first_get(long jarg1, SPair jarg1_);
  public final static native void SPair_second_set(long jarg1, SPair jarg1_, String jarg2);
  public final static native String SPair_second_get(long jarg1, SPair jarg1_);
  public final static native void delete_SPair(long jarg1);
  public final static native long new_IVector__SWIG_0();
  public final static native long new_IVector__SWIG_1(long jarg1, IVector jarg1_);
  public final static native boolean IVector_isEmpty(long jarg1, IVector jarg1_);
  public final static native void IVector_clear(long jarg1, IVector jarg1_);
  public final static native long new_IVector__SWIG_2(int jarg1, int jarg2);
  public final static native int IVector_doCapacity(long jarg1, IVector jarg1_);
  public final static native void IVector_doReserve(long jarg1, IVector jarg1_, int jarg2);
  public final static native int IVector_doSize(long jarg1, IVector jarg1_);
  public final static native void IVector_doAdd__SWIG_0(long jarg1, IVector jarg1_, int jarg2);
  public final static native void IVector_doAdd__SWIG_1(long jarg1, IVector jarg1_, int jarg2, int jarg3);
  public final static native int IVector_doRemove(long jarg1, IVector jarg1_, int jarg2);
  public final static native int IVector_doGet(long jarg1, IVector jarg1_, int jarg2);
  public final static native int IVector_doSet(long jarg1, IVector jarg1_, int jarg2, int jarg3);
  public final static native void IVector_doRemoveRange(long jarg1, IVector jarg1_, int jarg2, int jarg3);
  public final static native void delete_IVector(long jarg1);
  public final static native long new_DVector__SWIG_0();
  public final static native long new_DVector__SWIG_1(long jarg1, DVector jarg1_);
  public final static native boolean DVector_isEmpty(long jarg1, DVector jarg1_);
  public final static native void DVector_clear(long jarg1, DVector jarg1_);
  public final static native long new_DVector__SWIG_2(int jarg1, double jarg2);
  public final static native int DVector_doCapacity(long jarg1, DVector jarg1_);
  public final static native void DVector_doReserve(long jarg1, DVector jarg1_, int jarg2);
  public final static native int DVector_doSize(long jarg1, DVector jarg1_);
  public final static native void DVector_doAdd__SWIG_0(long jarg1, DVector jarg1_, double jarg2);
  public final static native void DVector_doAdd__SWIG_1(long jarg1, DVector jarg1_, int jarg2, double jarg3);
  public final static native double DVector_doRemove(long jarg1, DVector jarg1_, int jarg2);
  public final static native double DVector_doGet(long jarg1, DVector jarg1_, int jarg2);
  public final static native double DVector_doSet(long jarg1, DVector jarg1_, int jarg2, double jarg3);
  public final static native void DVector_doRemoveRange(long jarg1, DVector jarg1_, int jarg2, int jarg3);
  public final static native void delete_DVector(long jarg1);
  public final static native long new_SizeVector__SWIG_0();
  public final static native long new_SizeVector__SWIG_1(long jarg1, SizeVector jarg1_);
  public final static native boolean SizeVector_isEmpty(long jarg1, SizeVector jarg1_);
  public final static native void SizeVector_clear(long jarg1, SizeVector jarg1_);
  public final static native long new_SizeVector__SWIG_2(int jarg1, long jarg2);
  public final static native int SizeVector_doCapacity(long jarg1, SizeVector jarg1_);
  public final static native void SizeVector_doReserve(long jarg1, SizeVector jarg1_, int jarg2);
  public final static native int SizeVector_doSize(long jarg1, SizeVector jarg1_);
  public final static native void SizeVector_doAdd__SWIG_0(long jarg1, SizeVector jarg1_, long jarg2);
  public final static native void SizeVector_doAdd__SWIG_1(long jarg1, SizeVector jarg1_, int jarg2, long jarg3);
  public final static native long SizeVector_doRemove(long jarg1, SizeVector jarg1_, int jarg2);
  public final static native long SizeVector_doGet(long jarg1, SizeVector jarg1_, int jarg2);
  public final static native long SizeVector_doSet(long jarg1, SizeVector jarg1_, int jarg2, long jarg3);
  public final static native void SizeVector_doRemoveRange(long jarg1, SizeVector jarg1_, int jarg2, int jarg3);
  public final static native void delete_SizeVector(long jarg1);
  public final static native long new_SVector__SWIG_0();
  public final static native long new_SVector__SWIG_1(long jarg1, SVector jarg1_);
  public final static native boolean SVector_isEmpty(long jarg1, SVector jarg1_);
  public final static native void SVector_clear(long jarg1, SVector jarg1_);
  public final static native long new_SVector__SWIG_2(int jarg1, String jarg2);
  public final static native int SVector_doCapacity(long jarg1, SVector jarg1_);
  public final static native void SVector_doReserve(long jarg1, SVector jarg1_, int jarg2);
  public final static native int SVector_doSize(long jarg1, SVector jarg1_);
  public final static native void SVector_doAdd__SWIG_0(long jarg1, SVector jarg1_, String jarg2);
  public final static native void SVector_doAdd__SWIG_1(long jarg1, SVector jarg1_, int jarg2, String jarg3);
  public final static native String SVector_doRemove(long jarg1, SVector jarg1_, int jarg2);
  public final static native String SVector_doGet(long jarg1, SVector jarg1_, int jarg2);
  public final static native String SVector_doSet(long jarg1, SVector jarg1_, int jarg2, String jarg3);
  public final static native void SVector_doRemoveRange(long jarg1, SVector jarg1_, int jarg2, int jarg3);
  public final static native void delete_SVector(long jarg1);
}
