/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG JSE (https://www.swig.org).
 * Version 5.0.6
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

// source: src/gooctra/swig/gooctra.i

package octra

/*
#define intgo swig_intgo
typedef void *swig_voidp;

#include <stddef.h>
#include <stdint.h>


typedef long long intgo;
typedef unsigned long long uintgo;



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;


typedef _gostring_ swig_type_1;
typedef _gostring_ swig_type_2;
typedef _gostring_ swig_type_3;
typedef _gostring_ swig_type_4;
typedef _gostring_ swig_type_5;
typedef _gostring_ swig_type_6;
typedef long long swig_type_7;
typedef long long swig_type_8;
typedef long long swig_type_9;
typedef long long swig_type_10;
typedef long long swig_type_11;
typedef long long swig_type_12;
typedef long long swig_type_13;
typedef long long swig_type_14;
typedef long long swig_type_15;
typedef long long swig_type_16;
typedef long long swig_type_17;
typedef long long swig_type_18;
typedef long long swig_type_19;
typedef long long swig_type_20;
typedef long long swig_type_21;
typedef long long swig_type_22;
typedef long long swig_type_23;
typedef long long swig_type_24;
typedef long long swig_type_25;
typedef _gostring_ swig_type_26;
typedef _gostring_ swig_type_27;
typedef _gostring_ swig_type_28;
extern void _wrap_Swig_free_octra_edfc800af80047e0(uintptr_t arg1);
extern uintptr_t _wrap_Swig_malloc_octra_edfc800af80047e0(swig_intgo arg1);
extern uintptr_t _wrap_new_IPair__SWIG_0_octra_edfc800af80047e0(void);
extern uintptr_t _wrap_new_IPair__SWIG_1_octra_edfc800af80047e0(swig_intgo arg1, swig_intgo arg2);
extern uintptr_t _wrap_new_IPair__SWIG_2_octra_edfc800af80047e0(uintptr_t arg1);
extern void _wrap_IPair_first_set_octra_edfc800af80047e0(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_IPair_first_get_octra_edfc800af80047e0(uintptr_t arg1);
extern void _wrap_IPair_second_set_octra_edfc800af80047e0(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_IPair_second_get_octra_edfc800af80047e0(uintptr_t arg1);
extern void _wrap_delete_IPair_octra_edfc800af80047e0(uintptr_t arg1);
extern uintptr_t _wrap_new_DPair__SWIG_0_octra_edfc800af80047e0(void);
extern uintptr_t _wrap_new_DPair__SWIG_1_octra_edfc800af80047e0(double arg1, double arg2);
extern uintptr_t _wrap_new_DPair__SWIG_2_octra_edfc800af80047e0(uintptr_t arg1);
extern void _wrap_DPair_first_set_octra_edfc800af80047e0(uintptr_t arg1, double arg2);
extern double _wrap_DPair_first_get_octra_edfc800af80047e0(uintptr_t arg1);
extern void _wrap_DPair_second_set_octra_edfc800af80047e0(uintptr_t arg1, double arg2);
extern double _wrap_DPair_second_get_octra_edfc800af80047e0(uintptr_t arg1);
extern void _wrap_delete_DPair_octra_edfc800af80047e0(uintptr_t arg1);
extern uintptr_t _wrap_new_SPair__SWIG_0_octra_edfc800af80047e0(void);
extern uintptr_t _wrap_new_SPair__SWIG_1_octra_edfc800af80047e0(swig_type_1 arg1, swig_type_2 arg2);
extern uintptr_t _wrap_new_SPair__SWIG_2_octra_edfc800af80047e0(uintptr_t arg1);
extern void _wrap_SPair_first_set_octra_edfc800af80047e0(uintptr_t arg1, swig_type_3 arg2);
extern swig_type_4 _wrap_SPair_first_get_octra_edfc800af80047e0(uintptr_t arg1);
extern void _wrap_SPair_second_set_octra_edfc800af80047e0(uintptr_t arg1, swig_type_5 arg2);
extern swig_type_6 _wrap_SPair_second_get_octra_edfc800af80047e0(uintptr_t arg1);
extern void _wrap_delete_SPair_octra_edfc800af80047e0(uintptr_t arg1);
extern uintptr_t _wrap_new_IVector__SWIG_0_octra_edfc800af80047e0(void);
extern uintptr_t _wrap_new_IVector__SWIG_1_octra_edfc800af80047e0(swig_type_7 arg1);
extern uintptr_t _wrap_new_IVector__SWIG_2_octra_edfc800af80047e0(uintptr_t arg1);
extern swig_type_8 _wrap_IVector_size_octra_edfc800af80047e0(uintptr_t arg1);
extern swig_type_9 _wrap_IVector_capacity_octra_edfc800af80047e0(uintptr_t arg1);
extern void _wrap_IVector_reserve_octra_edfc800af80047e0(uintptr_t arg1, swig_type_10 arg2);
extern _Bool _wrap_IVector_isEmpty_octra_edfc800af80047e0(uintptr_t arg1);
extern void _wrap_IVector_clear_octra_edfc800af80047e0(uintptr_t arg1);
extern void _wrap_IVector_add_octra_edfc800af80047e0(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_IVector_get_octra_edfc800af80047e0(uintptr_t arg1, swig_intgo arg2);
extern void _wrap_IVector_set_octra_edfc800af80047e0(uintptr_t arg1, swig_intgo arg2, swig_intgo arg3);
extern void _wrap_delete_IVector_octra_edfc800af80047e0(uintptr_t arg1);
extern uintptr_t _wrap_new_DVector__SWIG_0_octra_edfc800af80047e0(void);
extern uintptr_t _wrap_new_DVector__SWIG_1_octra_edfc800af80047e0(swig_type_11 arg1);
extern uintptr_t _wrap_new_DVector__SWIG_2_octra_edfc800af80047e0(uintptr_t arg1);
extern swig_type_12 _wrap_DVector_size_octra_edfc800af80047e0(uintptr_t arg1);
extern swig_type_13 _wrap_DVector_capacity_octra_edfc800af80047e0(uintptr_t arg1);
extern void _wrap_DVector_reserve_octra_edfc800af80047e0(uintptr_t arg1, swig_type_14 arg2);
extern _Bool _wrap_DVector_isEmpty_octra_edfc800af80047e0(uintptr_t arg1);
extern void _wrap_DVector_clear_octra_edfc800af80047e0(uintptr_t arg1);
extern void _wrap_DVector_add_octra_edfc800af80047e0(uintptr_t arg1, double arg2);
extern double _wrap_DVector_get_octra_edfc800af80047e0(uintptr_t arg1, swig_intgo arg2);
extern void _wrap_DVector_set_octra_edfc800af80047e0(uintptr_t arg1, swig_intgo arg2, double arg3);
extern void _wrap_delete_DVector_octra_edfc800af80047e0(uintptr_t arg1);
extern uintptr_t _wrap_new_SizeVector__SWIG_0_octra_edfc800af80047e0(void);
extern uintptr_t _wrap_new_SizeVector__SWIG_1_octra_edfc800af80047e0(swig_type_15 arg1);
extern uintptr_t _wrap_new_SizeVector__SWIG_2_octra_edfc800af80047e0(uintptr_t arg1);
extern swig_type_16 _wrap_SizeVector_size_octra_edfc800af80047e0(uintptr_t arg1);
extern swig_type_17 _wrap_SizeVector_capacity_octra_edfc800af80047e0(uintptr_t arg1);
extern void _wrap_SizeVector_reserve_octra_edfc800af80047e0(uintptr_t arg1, swig_type_18 arg2);
extern _Bool _wrap_SizeVector_isEmpty_octra_edfc800af80047e0(uintptr_t arg1);
extern void _wrap_SizeVector_clear_octra_edfc800af80047e0(uintptr_t arg1);
extern void _wrap_SizeVector_add_octra_edfc800af80047e0(uintptr_t arg1, swig_type_19 arg2);
extern swig_type_20 _wrap_SizeVector_get_octra_edfc800af80047e0(uintptr_t arg1, swig_intgo arg2);
extern void _wrap_SizeVector_set_octra_edfc800af80047e0(uintptr_t arg1, swig_intgo arg2, swig_type_21 arg3);
extern void _wrap_delete_SizeVector_octra_edfc800af80047e0(uintptr_t arg1);
extern uintptr_t _wrap_new_SVector__SWIG_0_octra_edfc800af80047e0(void);
extern uintptr_t _wrap_new_SVector__SWIG_1_octra_edfc800af80047e0(swig_type_22 arg1);
extern uintptr_t _wrap_new_SVector__SWIG_2_octra_edfc800af80047e0(uintptr_t arg1);
extern swig_type_23 _wrap_SVector_size_octra_edfc800af80047e0(uintptr_t arg1);
extern swig_type_24 _wrap_SVector_capacity_octra_edfc800af80047e0(uintptr_t arg1);
extern void _wrap_SVector_reserve_octra_edfc800af80047e0(uintptr_t arg1, swig_type_25 arg2);
extern _Bool _wrap_SVector_isEmpty_octra_edfc800af80047e0(uintptr_t arg1);
extern void _wrap_SVector_clear_octra_edfc800af80047e0(uintptr_t arg1);
extern void _wrap_SVector_add_octra_edfc800af80047e0(uintptr_t arg1, swig_type_26 arg2);
extern swig_type_27 _wrap_SVector_get_octra_edfc800af80047e0(uintptr_t arg1, swig_intgo arg2);
extern void _wrap_SVector_set_octra_edfc800af80047e0(uintptr_t arg1, swig_intgo arg2, swig_type_28 arg3);
extern void _wrap_delete_SVector_octra_edfc800af80047e0(uintptr_t arg1);
extern void _wrap_hello_octra_edfc800af80047e0(void);
extern void _wrap_delete_Callback_octra_edfc800af80047e0(uintptr_t arg1);
extern double _wrap_Callback_call_octra_edfc800af80047e0(uintptr_t arg1, double arg2);
extern uintptr_t _wrap_new_Callback_octra_edfc800af80047e0(void);
extern double _wrap_call_with_callback_octra_edfc800af80047e0(double arg1, uintptr_t arg2);
extern uintptr_t _wrap_map_dvector_with_callback_octra_edfc800af80047e0(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_make_dvector_octra_edfc800af80047e0(double arg1, double arg2, double arg3);
extern double _wrap_sum_dvector_octra_edfc800af80047e0(uintptr_t arg1);
extern uintptr_t _wrap_make_dpair_octra_edfc800af80047e0(double arg1, double arg2);
extern double _wrap_sum_dpair_octra_edfc800af80047e0(uintptr_t arg1);
#undef intgo
*/
import "C"

import "unsafe"
import _ "runtime/cgo"
import "sync"


type _ unsafe.Pointer



var Swig_escape_always_false bool
var Swig_escape_val interface{}


type _swig_fnptr *byte
type _swig_memberptr *byte


func getSwigcptr(v interface { Swigcptr() uintptr }) uintptr {
	if v == nil {
		return 0
	}
	return v.Swigcptr()
}


type _ sync.Mutex

//export cgo_panic__octra_edfc800af80047e0
func cgo_panic__octra_edfc800af80047e0(p *byte) {
	s := (*[1024]byte)(unsafe.Pointer(p))[:]
	for i, b := range s {
		if b == 0 {
			panic(string(s[:i]))
		}
	}
	panic(string(s))
}


type swig_gostring struct { p uintptr; n int }
func swigCopyString(s string) string {
  p := *(*swig_gostring)(unsafe.Pointer(&s))
  r := string((*[0x7fffffff]byte)(unsafe.Pointer(p.p))[:p.n])
  Swig_free(p.p)
  return r
}

func Swig_free(arg1 uintptr) {
	_swig_i_0 := arg1
	C._wrap_Swig_free_octra_edfc800af80047e0(C.uintptr_t(_swig_i_0))
}

func Swig_malloc(arg1 int) (_swig_ret uintptr) {
	var swig_r uintptr
	_swig_i_0 := arg1
	swig_r = (uintptr)(C._wrap_Swig_malloc_octra_edfc800af80047e0(C.swig_intgo(_swig_i_0)))
	return swig_r
}

type SwigcptrIPair uintptr

func (p SwigcptrIPair) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrIPair) SwigIsIPair() {
}

func NewIPair__SWIG_0() (_swig_ret IPair) {
	var swig_r IPair
	swig_r = (IPair)(SwigcptrIPair(C._wrap_new_IPair__SWIG_0_octra_edfc800af80047e0()))
	return swig_r
}

func NewIPair__SWIG_1(arg1 int, arg2 int) (_swig_ret IPair) {
	var swig_r IPair
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (IPair)(SwigcptrIPair(C._wrap_new_IPair__SWIG_1_octra_edfc800af80047e0(C.swig_intgo(_swig_i_0), C.swig_intgo(_swig_i_1))))
	return swig_r
}

func NewIPair__SWIG_2(arg1 IPair) (_swig_ret IPair) {
	var swig_r IPair
	_swig_i_0 := getSwigcptr(arg1)
	swig_r = (IPair)(SwigcptrIPair(C._wrap_new_IPair__SWIG_2_octra_edfc800af80047e0(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func NewIPair(a ...interface{}) IPair {
	argc := len(a)
	if argc == 0 {
		return NewIPair__SWIG_0()
	}
	if argc == 1 {
		return NewIPair__SWIG_2(a[0].(IPair))
	}
	if argc == 2 {
		return NewIPair__SWIG_1(a[0].(int), a[1].(int))
	}
	panic("No match for overloaded function call")
}

func (arg1 SwigcptrIPair) SetFirst(arg2 int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_IPair_first_set_octra_edfc800af80047e0(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrIPair) GetFirst() (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_IPair_first_get_octra_edfc800af80047e0(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrIPair) SetSecond(arg2 int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_IPair_second_set_octra_edfc800af80047e0(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrIPair) GetSecond() (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_IPair_second_get_octra_edfc800af80047e0(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func DeleteIPair(arg1 IPair) {
	_swig_i_0 := getSwigcptr(arg1)
	C._wrap_delete_IPair_octra_edfc800af80047e0(C.uintptr_t(_swig_i_0))
}

type IPair interface {
	Swigcptr() uintptr
	SwigIsIPair()
	SetFirst(arg2 int)
	GetFirst() (_swig_ret int)
	SetSecond(arg2 int)
	GetSecond() (_swig_ret int)
}

type SwigcptrDPair uintptr

func (p SwigcptrDPair) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrDPair) SwigIsDPair() {
}

func NewDPair__SWIG_0() (_swig_ret DPair) {
	var swig_r DPair
	swig_r = (DPair)(SwigcptrDPair(C._wrap_new_DPair__SWIG_0_octra_edfc800af80047e0()))
	return swig_r
}

func NewDPair__SWIG_1(arg1 float64, arg2 float64) (_swig_ret DPair) {
	var swig_r DPair
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (DPair)(SwigcptrDPair(C._wrap_new_DPair__SWIG_1_octra_edfc800af80047e0(C.double(_swig_i_0), C.double(_swig_i_1))))
	return swig_r
}

func NewDPair__SWIG_2(arg1 DPair) (_swig_ret DPair) {
	var swig_r DPair
	_swig_i_0 := getSwigcptr(arg1)
	swig_r = (DPair)(SwigcptrDPair(C._wrap_new_DPair__SWIG_2_octra_edfc800af80047e0(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func NewDPair(a ...interface{}) DPair {
	argc := len(a)
	if argc == 0 {
		return NewDPair__SWIG_0()
	}
	if argc == 1 {
		return NewDPair__SWIG_2(a[0].(DPair))
	}
	if argc == 2 {
		return NewDPair__SWIG_1(a[0].(float64), a[1].(float64))
	}
	panic("No match for overloaded function call")
}

func (arg1 SwigcptrDPair) SetFirst(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_DPair_first_set_octra_edfc800af80047e0(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrDPair) GetFirst() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_DPair_first_get_octra_edfc800af80047e0(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrDPair) SetSecond(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_DPair_second_set_octra_edfc800af80047e0(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrDPair) GetSecond() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_DPair_second_get_octra_edfc800af80047e0(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func DeleteDPair(arg1 DPair) {
	_swig_i_0 := getSwigcptr(arg1)
	C._wrap_delete_DPair_octra_edfc800af80047e0(C.uintptr_t(_swig_i_0))
}

type DPair interface {
	Swigcptr() uintptr
	SwigIsDPair()
	SetFirst(arg2 float64)
	GetFirst() (_swig_ret float64)
	SetSecond(arg2 float64)
	GetSecond() (_swig_ret float64)
}

type SwigcptrSPair uintptr

func (p SwigcptrSPair) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrSPair) SwigIsSPair() {
}

func NewSPair__SWIG_0() (_swig_ret SPair) {
	var swig_r SPair
	swig_r = (SPair)(SwigcptrSPair(C._wrap_new_SPair__SWIG_0_octra_edfc800af80047e0()))
	return swig_r
}

func NewSPair__SWIG_1(arg1 string, arg2 string) (_swig_ret SPair) {
	var swig_r SPair
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (SPair)(SwigcptrSPair(C._wrap_new_SPair__SWIG_1_octra_edfc800af80047e0(*(*C.swig_type_1)(unsafe.Pointer(&_swig_i_0)), *(*C.swig_type_2)(unsafe.Pointer(&_swig_i_1)))))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func NewSPair__SWIG_2(arg1 SPair) (_swig_ret SPair) {
	var swig_r SPair
	_swig_i_0 := getSwigcptr(arg1)
	swig_r = (SPair)(SwigcptrSPair(C._wrap_new_SPair__SWIG_2_octra_edfc800af80047e0(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func NewSPair(a ...interface{}) SPair {
	argc := len(a)
	if argc == 0 {
		return NewSPair__SWIG_0()
	}
	if argc == 1 {
		return NewSPair__SWIG_2(a[0].(SPair))
	}
	if argc == 2 {
		return NewSPair__SWIG_1(a[0].(string), a[1].(string))
	}
	panic("No match for overloaded function call")
}

func (arg1 SwigcptrSPair) SetFirst(arg2 string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_SPair_first_set_octra_edfc800af80047e0(C.uintptr_t(_swig_i_0), *(*C.swig_type_3)(unsafe.Pointer(&_swig_i_1)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

func (arg1 SwigcptrSPair) GetFirst() (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	swig_r_p := C._wrap_SPair_first_get_octra_edfc800af80047e0(C.uintptr_t(_swig_i_0))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func (arg1 SwigcptrSPair) SetSecond(arg2 string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_SPair_second_set_octra_edfc800af80047e0(C.uintptr_t(_swig_i_0), *(*C.swig_type_5)(unsafe.Pointer(&_swig_i_1)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

func (arg1 SwigcptrSPair) GetSecond() (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	swig_r_p := C._wrap_SPair_second_get_octra_edfc800af80047e0(C.uintptr_t(_swig_i_0))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func DeleteSPair(arg1 SPair) {
	_swig_i_0 := getSwigcptr(arg1)
	C._wrap_delete_SPair_octra_edfc800af80047e0(C.uintptr_t(_swig_i_0))
}

type SPair interface {
	Swigcptr() uintptr
	SwigIsSPair()
	SetFirst(arg2 string)
	GetFirst() (_swig_ret string)
	SetSecond(arg2 string)
	GetSecond() (_swig_ret string)
}

type SwigcptrIVector uintptr

func (p SwigcptrIVector) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrIVector) SwigIsIVector() {
}

func NewIVector__SWIG_0() (_swig_ret IVector) {
	var swig_r IVector
	swig_r = (IVector)(SwigcptrIVector(C._wrap_new_IVector__SWIG_0_octra_edfc800af80047e0()))
	return swig_r
}

func NewIVector__SWIG_1(arg1 int64) (_swig_ret IVector) {
	var swig_r IVector
	_swig_i_0 := arg1
	swig_r = (IVector)(SwigcptrIVector(C._wrap_new_IVector__SWIG_1_octra_edfc800af80047e0(C.swig_type_7(_swig_i_0))))
	return swig_r
}

func NewIVector__SWIG_2(arg1 IVector) (_swig_ret IVector) {
	var swig_r IVector
	_swig_i_0 := getSwigcptr(arg1)
	swig_r = (IVector)(SwigcptrIVector(C._wrap_new_IVector__SWIG_2_octra_edfc800af80047e0(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func NewIVector(a ...interface{}) IVector {
	argc := len(a)
	if argc == 0 {
		return NewIVector__SWIG_0()
	}
	if argc == 1 {
		if _, ok := a[0].(int64); !ok {
			goto check_2
		}
		return NewIVector__SWIG_1(a[0].(int64))
	}
check_2:
	if argc == 1 {
		return NewIVector__SWIG_2(a[0].(IVector))
	}
	panic("No match for overloaded function call")
}

func (arg1 SwigcptrIVector) Size() (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1
	swig_r = (int64)(C._wrap_IVector_size_octra_edfc800af80047e0(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrIVector) Capacity() (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1
	swig_r = (int64)(C._wrap_IVector_capacity_octra_edfc800af80047e0(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrIVector) Reserve(arg2 int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_IVector_reserve_octra_edfc800af80047e0(C.uintptr_t(_swig_i_0), C.swig_type_10(_swig_i_1))
}

func (arg1 SwigcptrIVector) IsEmpty() (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1
	swig_r = (bool)(C._wrap_IVector_isEmpty_octra_edfc800af80047e0(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrIVector) Clear() {
	_swig_i_0 := arg1
	C._wrap_IVector_clear_octra_edfc800af80047e0(C.uintptr_t(_swig_i_0))
}

func (arg1 SwigcptrIVector) Add(arg2 int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_IVector_add_octra_edfc800af80047e0(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrIVector) Get(arg2 int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_IVector_get_octra_edfc800af80047e0(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1)))
	return swig_r
}

func (arg1 SwigcptrIVector) Set(arg2 int, arg3 int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	C._wrap_IVector_set_octra_edfc800af80047e0(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1), C.swig_intgo(_swig_i_2))
}

func DeleteIVector(arg1 IVector) {
	_swig_i_0 := getSwigcptr(arg1)
	C._wrap_delete_IVector_octra_edfc800af80047e0(C.uintptr_t(_swig_i_0))
}

type IVector interface {
	Swigcptr() uintptr
	SwigIsIVector()
	Size() (_swig_ret int64)
	Capacity() (_swig_ret int64)
	Reserve(arg2 int64)
	IsEmpty() (_swig_ret bool)
	Clear()
	Add(arg2 int)
	Get(arg2 int) (_swig_ret int)
	Set(arg2 int, arg3 int)
}

type SwigcptrDVector uintptr

func (p SwigcptrDVector) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrDVector) SwigIsDVector() {
}

func NewDVector__SWIG_0() (_swig_ret DVector) {
	var swig_r DVector
	swig_r = (DVector)(SwigcptrDVector(C._wrap_new_DVector__SWIG_0_octra_edfc800af80047e0()))
	return swig_r
}

func NewDVector__SWIG_1(arg1 int64) (_swig_ret DVector) {
	var swig_r DVector
	_swig_i_0 := arg1
	swig_r = (DVector)(SwigcptrDVector(C._wrap_new_DVector__SWIG_1_octra_edfc800af80047e0(C.swig_type_11(_swig_i_0))))
	return swig_r
}

func NewDVector__SWIG_2(arg1 DVector) (_swig_ret DVector) {
	var swig_r DVector
	_swig_i_0 := getSwigcptr(arg1)
	swig_r = (DVector)(SwigcptrDVector(C._wrap_new_DVector__SWIG_2_octra_edfc800af80047e0(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func NewDVector(a ...interface{}) DVector {
	argc := len(a)
	if argc == 0 {
		return NewDVector__SWIG_0()
	}
	if argc == 1 {
		if _, ok := a[0].(int64); !ok {
			goto check_2
		}
		return NewDVector__SWIG_1(a[0].(int64))
	}
check_2:
	if argc == 1 {
		return NewDVector__SWIG_2(a[0].(DVector))
	}
	panic("No match for overloaded function call")
}

func (arg1 SwigcptrDVector) Size() (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1
	swig_r = (int64)(C._wrap_DVector_size_octra_edfc800af80047e0(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrDVector) Capacity() (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1
	swig_r = (int64)(C._wrap_DVector_capacity_octra_edfc800af80047e0(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrDVector) Reserve(arg2 int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_DVector_reserve_octra_edfc800af80047e0(C.uintptr_t(_swig_i_0), C.swig_type_14(_swig_i_1))
}

func (arg1 SwigcptrDVector) IsEmpty() (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1
	swig_r = (bool)(C._wrap_DVector_isEmpty_octra_edfc800af80047e0(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrDVector) Clear() {
	_swig_i_0 := arg1
	C._wrap_DVector_clear_octra_edfc800af80047e0(C.uintptr_t(_swig_i_0))
}

func (arg1 SwigcptrDVector) Add(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_DVector_add_octra_edfc800af80047e0(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrDVector) Get(arg2 int) (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (float64)(C._wrap_DVector_get_octra_edfc800af80047e0(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1)))
	return swig_r
}

func (arg1 SwigcptrDVector) Set(arg2 int, arg3 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	C._wrap_DVector_set_octra_edfc800af80047e0(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1), C.double(_swig_i_2))
}

func DeleteDVector(arg1 DVector) {
	_swig_i_0 := getSwigcptr(arg1)
	C._wrap_delete_DVector_octra_edfc800af80047e0(C.uintptr_t(_swig_i_0))
}

type DVector interface {
	Swigcptr() uintptr
	SwigIsDVector()
	Size() (_swig_ret int64)
	Capacity() (_swig_ret int64)
	Reserve(arg2 int64)
	IsEmpty() (_swig_ret bool)
	Clear()
	Add(arg2 float64)
	Get(arg2 int) (_swig_ret float64)
	Set(arg2 int, arg3 float64)
}

type SwigcptrSizeVector uintptr

func (p SwigcptrSizeVector) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrSizeVector) SwigIsSizeVector() {
}

func NewSizeVector__SWIG_0() (_swig_ret SizeVector) {
	var swig_r SizeVector
	swig_r = (SizeVector)(SwigcptrSizeVector(C._wrap_new_SizeVector__SWIG_0_octra_edfc800af80047e0()))
	return swig_r
}

func NewSizeVector__SWIG_1(arg1 int64) (_swig_ret SizeVector) {
	var swig_r SizeVector
	_swig_i_0 := arg1
	swig_r = (SizeVector)(SwigcptrSizeVector(C._wrap_new_SizeVector__SWIG_1_octra_edfc800af80047e0(C.swig_type_15(_swig_i_0))))
	return swig_r
}

func NewSizeVector__SWIG_2(arg1 SizeVector) (_swig_ret SizeVector) {
	var swig_r SizeVector
	_swig_i_0 := getSwigcptr(arg1)
	swig_r = (SizeVector)(SwigcptrSizeVector(C._wrap_new_SizeVector__SWIG_2_octra_edfc800af80047e0(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func NewSizeVector(a ...interface{}) SizeVector {
	argc := len(a)
	if argc == 0 {
		return NewSizeVector__SWIG_0()
	}
	if argc == 1 {
		if _, ok := a[0].(int64); !ok {
			goto check_2
		}
		return NewSizeVector__SWIG_1(a[0].(int64))
	}
check_2:
	if argc == 1 {
		return NewSizeVector__SWIG_2(a[0].(SizeVector))
	}
	panic("No match for overloaded function call")
}

func (arg1 SwigcptrSizeVector) Size() (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1
	swig_r = (int64)(C._wrap_SizeVector_size_octra_edfc800af80047e0(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrSizeVector) Capacity() (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1
	swig_r = (int64)(C._wrap_SizeVector_capacity_octra_edfc800af80047e0(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrSizeVector) Reserve(arg2 int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_SizeVector_reserve_octra_edfc800af80047e0(C.uintptr_t(_swig_i_0), C.swig_type_18(_swig_i_1))
}

func (arg1 SwigcptrSizeVector) IsEmpty() (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1
	swig_r = (bool)(C._wrap_SizeVector_isEmpty_octra_edfc800af80047e0(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrSizeVector) Clear() {
	_swig_i_0 := arg1
	C._wrap_SizeVector_clear_octra_edfc800af80047e0(C.uintptr_t(_swig_i_0))
}

func (arg1 SwigcptrSizeVector) Add(arg2 int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_SizeVector_add_octra_edfc800af80047e0(C.uintptr_t(_swig_i_0), C.swig_type_19(_swig_i_1))
}

func (arg1 SwigcptrSizeVector) Get(arg2 int) (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (int64)(C._wrap_SizeVector_get_octra_edfc800af80047e0(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1)))
	return swig_r
}

func (arg1 SwigcptrSizeVector) Set(arg2 int, arg3 int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	C._wrap_SizeVector_set_octra_edfc800af80047e0(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1), C.swig_type_21(_swig_i_2))
}

func DeleteSizeVector(arg1 SizeVector) {
	_swig_i_0 := getSwigcptr(arg1)
	C._wrap_delete_SizeVector_octra_edfc800af80047e0(C.uintptr_t(_swig_i_0))
}

type SizeVector interface {
	Swigcptr() uintptr
	SwigIsSizeVector()
	Size() (_swig_ret int64)
	Capacity() (_swig_ret int64)
	Reserve(arg2 int64)
	IsEmpty() (_swig_ret bool)
	Clear()
	Add(arg2 int64)
	Get(arg2 int) (_swig_ret int64)
	Set(arg2 int, arg3 int64)
}

type SwigcptrSVector uintptr

func (p SwigcptrSVector) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrSVector) SwigIsSVector() {
}

func NewSVector__SWIG_0() (_swig_ret SVector) {
	var swig_r SVector
	swig_r = (SVector)(SwigcptrSVector(C._wrap_new_SVector__SWIG_0_octra_edfc800af80047e0()))
	return swig_r
}

func NewSVector__SWIG_1(arg1 int64) (_swig_ret SVector) {
	var swig_r SVector
	_swig_i_0 := arg1
	swig_r = (SVector)(SwigcptrSVector(C._wrap_new_SVector__SWIG_1_octra_edfc800af80047e0(C.swig_type_22(_swig_i_0))))
	return swig_r
}

func NewSVector__SWIG_2(arg1 SVector) (_swig_ret SVector) {
	var swig_r SVector
	_swig_i_0 := getSwigcptr(arg1)
	swig_r = (SVector)(SwigcptrSVector(C._wrap_new_SVector__SWIG_2_octra_edfc800af80047e0(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func NewSVector(a ...interface{}) SVector {
	argc := len(a)
	if argc == 0 {
		return NewSVector__SWIG_0()
	}
	if argc == 1 {
		if _, ok := a[0].(int64); !ok {
			goto check_2
		}
		return NewSVector__SWIG_1(a[0].(int64))
	}
check_2:
	if argc == 1 {
		return NewSVector__SWIG_2(a[0].(SVector))
	}
	panic("No match for overloaded function call")
}

func (arg1 SwigcptrSVector) Size() (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1
	swig_r = (int64)(C._wrap_SVector_size_octra_edfc800af80047e0(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrSVector) Capacity() (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1
	swig_r = (int64)(C._wrap_SVector_capacity_octra_edfc800af80047e0(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrSVector) Reserve(arg2 int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_SVector_reserve_octra_edfc800af80047e0(C.uintptr_t(_swig_i_0), C.swig_type_25(_swig_i_1))
}

func (arg1 SwigcptrSVector) IsEmpty() (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1
	swig_r = (bool)(C._wrap_SVector_isEmpty_octra_edfc800af80047e0(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrSVector) Clear() {
	_swig_i_0 := arg1
	C._wrap_SVector_clear_octra_edfc800af80047e0(C.uintptr_t(_swig_i_0))
}

func (arg1 SwigcptrSVector) Add(arg2 string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_SVector_add_octra_edfc800af80047e0(C.uintptr_t(_swig_i_0), *(*C.swig_type_26)(unsafe.Pointer(&_swig_i_1)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

func (arg1 SwigcptrSVector) Get(arg2 int) (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r_p := C._wrap_SVector_get_octra_edfc800af80047e0(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func (arg1 SwigcptrSVector) Set(arg2 int, arg3 string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	C._wrap_SVector_set_octra_edfc800af80047e0(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1), *(*C.swig_type_28)(unsafe.Pointer(&_swig_i_2)))
	if Swig_escape_always_false {
		Swig_escape_val = arg3
	}
}

func DeleteSVector(arg1 SVector) {
	_swig_i_0 := getSwigcptr(arg1)
	C._wrap_delete_SVector_octra_edfc800af80047e0(C.uintptr_t(_swig_i_0))
}

type SVector interface {
	Swigcptr() uintptr
	SwigIsSVector()
	Size() (_swig_ret int64)
	Capacity() (_swig_ret int64)
	Reserve(arg2 int64)
	IsEmpty() (_swig_ret bool)
	Clear()
	Add(arg2 string)
	Get(arg2 int) (_swig_ret string)
	Set(arg2 int, arg3 string)
}

func Hello() {
	C._wrap_hello_octra_edfc800af80047e0()
}

type SwigcptrCallback uintptr

func (p SwigcptrCallback) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrCallback) SwigIsCallback() {
}

func DeleteCallback(arg1 Callback) {
	_swig_i_0 := getSwigcptr(arg1)
	C._wrap_delete_Callback_octra_edfc800af80047e0(C.uintptr_t(_swig_i_0))
}

func (arg1 SwigcptrCallback) Call(arg2 float64) (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (float64)(C._wrap_Callback_call_octra_edfc800af80047e0(C.uintptr_t(_swig_i_0), C.double(_swig_i_1)))
	return swig_r
}

func NewCallback() (_swig_ret Callback) {
	var swig_r Callback
	swig_r = (Callback)(SwigcptrCallback(C._wrap_new_Callback_octra_edfc800af80047e0()))
	return swig_r
}

type Callback interface {
	Swigcptr() uintptr
	SwigIsCallback()
	Call(arg2 float64) (_swig_ret float64)
}

func Call_with_callback(arg1 float64, arg2 Callback) (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	_swig_i_1 := getSwigcptr(arg2)
	swig_r = (float64)(C._wrap_call_with_callback_octra_edfc800af80047e0(C.double(_swig_i_0), C.uintptr_t(_swig_i_1)))
	return swig_r
}

func Map_dvector_with_callback(arg1 DVector, arg2 Callback) (_swig_ret DVector) {
	var swig_r DVector
	_swig_i_0 := getSwigcptr(arg1)
	_swig_i_1 := getSwigcptr(arg2)
	swig_r = (DVector)(SwigcptrDVector(C._wrap_map_dvector_with_callback_octra_edfc800af80047e0(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))))
	return swig_r
}

func Make_dvector(arg1 float64, arg2 float64, arg3 float64) (_swig_ret DVector) {
	var swig_r DVector
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (DVector)(SwigcptrDVector(C._wrap_make_dvector_octra_edfc800af80047e0(C.double(_swig_i_0), C.double(_swig_i_1), C.double(_swig_i_2))))
	return swig_r
}

func Sum_dvector(arg1 DVector) (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := getSwigcptr(arg1)
	swig_r = (float64)(C._wrap_sum_dvector_octra_edfc800af80047e0(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func Make_dpair(arg1 float64, arg2 float64) (_swig_ret DPair) {
	var swig_r DPair
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (DPair)(SwigcptrDPair(C._wrap_make_dpair_octra_edfc800af80047e0(C.double(_swig_i_0), C.double(_swig_i_1))))
	return swig_r
}

func Sum_dpair(arg1 DPair) (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := getSwigcptr(arg1)
	swig_r = (float64)(C._wrap_sum_dpair_octra_edfc800af80047e0(C.uintptr_t(_swig_i_0)))
	return swig_r
}


