(* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ---------------------------------------------------------------------------- *)

open Swig
type c_enum_type = [ 
  `unknown
]
type c_enum_value = [ 
  `Int of int
]

type c_obj = c_enum_value c_obj_t
val module_name : string

exception BadArgs of string
exception BadMethodName of c_obj * string * string
exception NotObject of c_obj
exception NotEnumType of c_obj
exception LabelNotFromThisEnum of c_obj
exception InvalidDirectorCall of c_obj


    val array_to_vector : c_obj -> ('a -> c_obj) -> 'a array -> c_obj
    val vector_to_array : c_obj -> (c_obj -> 'a) -> 'a array -> c_obj

val new_DPair : c_obj -> c_obj
val _new_DPair : c_obj -> c_obj
val _delete_DPair : c_obj -> c_obj

val create_std_xxpair_xx_ldbrace_xx_lparendouble_xdouble_xx_rparen_xx_rdbrace_from_ptr : c_obj -> c_obj


val new_DVector : c_obj -> c_obj
val _new_DVector : c_obj -> c_obj
val _delete_DVector : c_obj -> c_obj

val create_std_xxvector_xx_ldbrace_xx_lparendouble_xx_rparen_xx_rdbrace_from_ptr : c_obj -> c_obj


val _hello : c_obj -> c_obj
val _delete_Callback : c_obj -> c_obj
val new_Callback : c_obj -> c_obj
val _new_Callback : c_obj -> c_obj

val create_octra_xxCallback_from_ptr : c_obj -> c_obj


val _call_with_callback : c_obj -> c_obj
val _map_dvector_with_callback : c_obj -> c_obj
val _make_dvector : c_obj -> c_obj
val _sum_dvector : c_obj -> c_obj
val _make_dpair : c_obj -> c_obj
val _sum_dpair : c_obj -> c_obj
val enum_to_int : c_enum_type -> c_obj -> Swig.c_obj
val int_to_enum : c_enum_type -> int -> c_obj

  val swig_val : c_enum_type -> c_obj -> Swig.c_obj

