/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG JSE (https://www.swig.org).
 * Version 5.0.6
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

declare const _SWIG_type_tag: unique symbol;

export const STD_STRINGS_BODY_SECTION: string;

export  class IPair {

  constructor();

  constructor(first: number, second: number);

  constructor(other: any);

  first: number;

  second: number;
}

export  class DPair {

  constructor();

  constructor(first: number, second: number);

  constructor(other: any);

  first: number;

  second: number;
}

export  class SPair {

  constructor();

  constructor(first: string, second: string);

  constructor(other: any);

  first: string;

  second: string;
}

export  class IVector {

  constructor();

  constructor(n: any);

  constructor(other: any);

  size(): any;

  capacity(): any;

  reserve(n: any): void;

  isEmpty(): boolean;

  clear(): void;

  add(x: any): void;

  get(i: number): any;

  set(i: number, val: any): void;
}

export  class DVector {

  constructor();

  constructor(n: any);

  constructor(other: any);

  size(): any;

  capacity(): any;

  reserve(n: any): void;

  isEmpty(): boolean;

  clear(): void;

  add(x: any): void;

  get(i: number): any;

  set(i: number, val: any): void;
}

export  class SizeVector {

  constructor();

  constructor(n: any);

  constructor(other: any);

  size(): any;

  capacity(): any;

  reserve(n: any): void;

  isEmpty(): boolean;

  clear(): void;

  add(x: any): void;

  get(i: number): any;

  set(i: number, val: any): void;
}

export  class SVector {

  constructor();

  constructor(n: any);

  constructor(other: any);

  size(): any;

  capacity(): any;

  reserve(n: any): void;

  isEmpty(): boolean;

  clear(): void;

  add(x: string): void;

  get(i: number): string;

  set(i: number, val: string): void;
}

export function hello(): void;


