/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG JSE (https://www.swig.org).
 * Version 5.0.6
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

#ifndef PHP_OCTRA_H
#define PHP_OCTRA_H

extern zend_module_entry octra_module_entry;
#define phpext_octra_ptr &octra_module_entry

#ifdef PHP_WIN32
# define PHP_OCTRA_API __declspec(dllexport)
#else
# define PHP_OCTRA_API
#endif

static PHP_METHOD(IPair,__construct);
static PHP_METHOD(IPair,first_set);
static PHP_METHOD(IPair,first_get);
static PHP_METHOD(IPair,second_set);
static PHP_METHOD(IPair,second_get);
PHP_METHOD(IPair,__set);
PHP_METHOD(IPair,__get);
PHP_METHOD(IPair,__isset);
static PHP_METHOD(DPair,__construct);
static PHP_METHOD(DPair,first_set);
static PHP_METHOD(DPair,first_get);
static PHP_METHOD(DPair,second_set);
static PHP_METHOD(DPair,second_get);
PHP_METHOD(DPair,__set);
PHP_METHOD(DPair,__get);
PHP_METHOD(DPair,__isset);
static PHP_METHOD(DVector,__construct);
static PHP_METHOD(DVector,size);
static PHP_METHOD(DVector,capacity);
static PHP_METHOD(DVector,reserve);
static PHP_METHOD(DVector,clear);
static PHP_METHOD(DVector,push);
static PHP_METHOD(DVector,is_empty);
static PHP_METHOD(DVector,pop);
static PHP_METHOD(DVector,get);
static PHP_METHOD(DVector,set);
PHP_METHOD(DVector,__set);
PHP_METHOD(DVector,__get);
PHP_METHOD(DVector,__isset);
static PHP_METHOD(IVector,__construct);
static PHP_METHOD(IVector,size);
static PHP_METHOD(IVector,capacity);
static PHP_METHOD(IVector,reserve);
static PHP_METHOD(IVector,clear);
static PHP_METHOD(IVector,push);
static PHP_METHOD(IVector,is_empty);
static PHP_METHOD(IVector,pop);
static PHP_METHOD(IVector,get);
static PHP_METHOD(IVector,set);
PHP_METHOD(IVector,__set);
PHP_METHOD(IVector,__get);
PHP_METHOD(IVector,__isset);
static PHP_METHOD(SizeVector,__construct);
static PHP_METHOD(SizeVector,size);
static PHP_METHOD(SizeVector,capacity);
static PHP_METHOD(SizeVector,reserve);
static PHP_METHOD(SizeVector,clear);
static PHP_METHOD(SizeVector,push);
static PHP_METHOD(SizeVector,is_empty);
static PHP_METHOD(SizeVector,pop);
static PHP_METHOD(SizeVector,get);
static PHP_METHOD(SizeVector,set);
PHP_METHOD(SizeVector,__set);
PHP_METHOD(SizeVector,__get);
PHP_METHOD(SizeVector,__isset);
static PHP_FUNCTION(hello);
PHP_MINIT_FUNCTION(octra);

#endif /* PHP_OCTRA_H */
