# This file was automatically generated by SWIG JSE (https://www.swig.org).
# Version 5.0.6
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

##   Generated via the command line invocation:
##	 swig -c++ -r -o ../src/octra_r_wrap.cpp -oh ../src/octra_r_wrap.h ../prebindings/octrar/src/octrar.i


#                         srun.swg                            #
#
# This is the basic code that is needed at run time within R to
# provide and define the relevant classes.  It is included
# automatically in the generated code by copying the contents of
# srun.swg into the newly created binding code.


# This could be provided as a separate run-time library but this
# approach allows the code to be included directly into the
# generated bindings and so removes the need to have and install an
# additional library.  We may however end up with multiple copies of
# this and some confusion at run-time as to which class to use. This
# is an issue when we use NAMESPACES as we may need to export certain
# classes.

######################################################################

if(length(getClassDef("RSWIGStruct")) == 0) 
  setClass("RSWIGStruct", representation("VIRTUAL"))



if(length(getClassDef("ExternalReference")) == 0) 
# Should be virtual but this means it loses its slots currently
#representation("VIRTUAL")
  setClass("ExternalReference", representation( ref = "externalptr"))



if(length(getClassDef("NativeRoutinePointer")) == 0) 
  setClass("NativeRoutinePointer", 
              representation(parameterTypes = "character",
                             returnType = "character",
                             "VIRTUAL"), 
              contains = "ExternalReference")

if(length(getClassDef("CRoutinePointer")) == 0) 
  setClass("CRoutinePointer", contains = "NativeRoutinePointer")


if(length(getClassDef("EnumerationValue")) == 0) 
  setClass("EnumerationValue", contains = "integer")


if(!isGeneric("copyToR")) 
 setGeneric("copyToR",
            function(value, obj = new(gsub("Ref$", "", class(value)))) 
               standardGeneric("copyToR"
           ))

setGeneric("delete", function(obj) standardGeneric("delete"))


SWIG_createNewRef = 
function(className, ..., append = TRUE)
{
  f = get(paste("new", className, sep = "_"), mode = "function")

  f(...)
}

if(!isGeneric("copyToC")) 
 setGeneric("copyToC", 
             function(value, obj = SWIG_createNewRef(class(value)))
              standardGeneric("copyToC"
            ))


# 
defineEnumeration =
function(name, .values, where = topenv(parent.frame()), suffix = "Value")
{
   # Mirror the class definitions via the E analogous to .__C__
  defName = paste(".__E__", name, sep = "")
  delayedAssign(defName,  .values, assign.env = where)

  if(nchar(suffix))
    name = paste(name, suffix, sep = "")

  setClass(name, contains = "EnumerationValue", where = where)
}

enumToInteger <- function(name,type)
{
   if (is.character(name)) {
   ans <- as.integer(get(paste(".__E__", type, sep = ""))[name])
   if (is.na(ans)) {warning("enum not found ", name, " ", type)}
   ans
   } 
}

enumFromInteger =
function(i,type)
{
  itemlist <- get(paste(".__E__", type, sep=""))
  names(itemlist)[match(i, itemlist)]
}

coerceIfNotSubclass =
function(obj, type) 
{
    if(!is(obj, type)) {as(obj, type)} else obj
}


setClass("SWIGArray", representation(dims = "integer"), contains = "ExternalReference")

setMethod("length", "SWIGArray", function(x) x@dims[1])


defineEnumeration("SCopyReferences",
                   .values = c( "FALSE" = 0, "TRUE" = 1, "DEEP" = 2))

assert = 
function(condition, message = "")
{
  if(!condition)
    stop(message)

  TRUE
}


if(FALSE) {
print.SWIGFunction =
function(x, ...)
 {
 }
}


#######################################################################

R_SWIG_getCallbackFunctionStack =
function()
{
    # No PACKAGE argument as we don't know what the DLL is.
  .Call("R_SWIG_debug_getCallbackFunctionData")
}

R_SWIG_addCallbackFunctionStack =
function(fun, userData = NULL)
{
    # No PACKAGE argument as we don't know what the DLL is.
  .Call("R_SWIG_R_pushCallbackFunctionData", fun, userData)
}


#######################################################################



setClass('C++Reference', contains = 'ExternalReference')
setClass('_p_std__pairT_int_int_t', contains = 'C++Reference')
setClass("std::pair<(int,int)>",
    representation(
        first = "integer",
        second = "integer"),
        contains = "RSWIGStruct")


# End class std::pair<(int,int)>

setClass('_p_std__pairT_double_double_t', contains = 'C++Reference')
setClass("std::pair<(double,double)>",
    representation(
        first = "numeric",
        second = "numeric"),
        contains = "RSWIGStruct")


# End class std::pair<(double,double)>

setClass('_p_std__vectorT_int_t', contains = 'C++Reference')
setClass('_p_std__vectorT_double_t', contains = 'C++Reference')
setClass('_p_std__vectorT_size_t_t', contains = 'C++Reference')
setClass('_p_octra__Callback', contains = 'C++Reference')



setMethod('[', "ExternalReference",
function(x,i,j, ..., drop=TRUE) 
if (!is.null(x$"__getitem__")) 
sapply(i, function(n) x$"__getitem__"(i=as.integer(n-1))))

setMethod('[<-' , "ExternalReference",
function(x,i,j, ..., value) 
if (!is.null(x$"__setitem__")) {
sapply(1:length(i), function(n) 
x$"__setitem__"(i=as.integer(i[n]-1), x=value[n]))
x
})

setAs('ExternalReference', 'character',
function(from) {if (!is.null(from$"__str__")) from$"__str__"()})

suppressMessages(suppressWarnings(setMethod('print', 'ExternalReference',
function(x) {print(as(x, "character"))})))

# Start of new_IPair

`IPair__SWIG_0` = function()
{
  ;ans = .Call('R_swig_new_IPair__SWIG_0', PACKAGE='octrar');
  ans <- if (is.null(ans)) ans
  else new("_p_std__pairT_int_int_t", ref=ans);
  
  reg.finalizer(ans@ref, delete_IPair);
  ans
  
}

attr(`IPair__SWIG_0`, 'returnType') = '_p_std__pairT_int_int_t'
class(`IPair__SWIG_0`) = c("SWIGFunction", class('IPair__SWIG_0'))

# Start of new_IPair

`IPair__SWIG_1` = function(first, second)
{
  first = as.integer(first);
  
  if(length(first) > 1) {
    warning("using only the first element of first");
  };
  
  second = as.integer(second);
  
  if(length(second) > 1) {
    warning("using only the first element of second");
  };
  
  ;ans = .Call('R_swig_new_IPair__SWIG_1', first, second, PACKAGE='octrar');
  ans <- if (is.null(ans)) ans
  else new("_p_std__pairT_int_int_t", ref=ans);
  
  reg.finalizer(ans@ref, delete_IPair);
  ans
  
}

attr(`IPair__SWIG_1`, 'returnType') = '_p_std__pairT_int_int_t'
attr(`IPair__SWIG_1`, "inputTypes") = c('integer', 'integer')
class(`IPair__SWIG_1`) = c("SWIGFunction", class('IPair__SWIG_1'))

# Start of new_IPair

`IPair__SWIG_2` = function(other)
{
  if (inherits(other, "ExternalReference")) other = slot(other,"ref"); 
  ;ans = .Call('R_swig_new_IPair__SWIG_2', other, PACKAGE='octrar');
  ans <- if (is.null(ans)) ans
  else new("_p_std__pairT_int_int_t", ref=ans);
  
  reg.finalizer(ans@ref, delete_IPair);
  ans
  
}

attr(`IPair__SWIG_2`, 'returnType') = '_p_std__pairT_int_int_t'
attr(`IPair__SWIG_2`, "inputTypes") = c('_p_std__pairT_int_int_t')
class(`IPair__SWIG_2`) = c("SWIGFunction", class('IPair__SWIG_2'))

`IPair` <- function(...) {
  argtypes <- mapply(class, list(...));
  argv <- list(...);
  argc <- length(argtypes);
  f <- NULL;
# dispatch functions 3
  if (argc == 0) {
    f <- IPair__SWIG_0; 
  } else if (argc == 1) {
    if ( extends(argtypes[1], '_p_std__pairT_int_int_t') && length(argv[[1]]) == 1 ) {
      f <- IPair__SWIG_2; 
    }
  } else if (argc == 2) {
    if (( (is.integer(argv[[1]]) || is.numeric(argv[[1]])) && length(argv[[1]]) == 1 ) && ( (is.integer(argv[[2]]) || is.numeric(argv[[2]])) && length(argv[[2]]) == 1 )) {
      f <- IPair__SWIG_1; 
    }
  };
  if (is.null(f)) {
    stop("cannot find overloaded function for IPair with argtypes (",toString(argtypes),")");
  };
  f(...);
}

# Dispatch function
# Start of IPair_first_set

`IPair_first_set` = function(self, s_first)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref"); 
  s_first = as.integer(s_first);
  
  if(length(s_first) > 1) {
    warning("using only the first element of s_first");
  };
  
  ;.Call('R_swig_IPair_first_set', self, s_first, PACKAGE='octrar');
  
}

attr(`IPair_first_set`, 'returnType') = 'void'
attr(`IPair_first_set`, "inputTypes") = c('_p_std__pairT_int_int_t', 'integer')
class(`IPair_first_set`) = c("SWIGFunction", class('IPair_first_set'))

# Start of IPair_first_get

`IPair_first_get` = function(self, .copy = FALSE)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref"); 
  ;.Call('R_swig_IPair_first_get', self, as.logical(.copy), PACKAGE='octrar');
  
}

attr(`IPair_first_get`, 'returnType') = 'integer'
attr(`IPair_first_get`, "inputTypes") = c('_p_std__pairT_int_int_t')
class(`IPair_first_get`) = c("SWIGFunction", class('IPair_first_get'))

# Start of IPair_second_set

`IPair_second_set` = function(self, s_second)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref"); 
  s_second = as.integer(s_second);
  
  if(length(s_second) > 1) {
    warning("using only the first element of s_second");
  };
  
  ;.Call('R_swig_IPair_second_set', self, s_second, PACKAGE='octrar');
  
}

attr(`IPair_second_set`, 'returnType') = 'void'
attr(`IPair_second_set`, "inputTypes") = c('_p_std__pairT_int_int_t', 'integer')
class(`IPair_second_set`) = c("SWIGFunction", class('IPair_second_set'))

# Start of IPair_second_get

`IPair_second_get` = function(self, .copy = FALSE)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref"); 
  ;.Call('R_swig_IPair_second_get', self, as.logical(.copy), PACKAGE='octrar');
  
}

attr(`IPair_second_get`, 'returnType') = 'integer'
attr(`IPair_second_get`, "inputTypes") = c('_p_std__pairT_int_int_t')
class(`IPair_second_get`) = c("SWIGFunction", class('IPair_second_get'))

# Start of delete_IPair

`delete_IPair` = function(self)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref"); 
  ;.Call('R_swig_delete_IPair', self, PACKAGE='octrar');
  
}

attr(`delete_IPair`, 'returnType') = 'void'
attr(`delete_IPair`, "inputTypes") = c('_p_std__pairT_int_int_t')
class(`delete_IPair`) = c("SWIGFunction", class('delete_IPair'))

# Start of accessor method for std::pair< int,int >
setMethod('$', '_p_std__pairT_int_int_t', function(x, name)

{
  accessorFuns = list('first' = IPair_first_get, 'second' = IPair_second_get);
  vaccessors = c('first', 'second');
  ;        idx = pmatch(name, names(accessorFuns));
  if(is.na(idx)) 
  return(callNextMethod(x, name));
  f = accessorFuns[[idx]];
  if (is.na(match(name, vaccessors))) function(...){
    f(x, ...)
  } else f(x);
}


);
# end of accessor method for std::pair< int,int >
# Start of accessor method for std::pair< int,int >
setMethod('$<-', '_p_std__pairT_int_int_t', function(x, name, value)

{
  accessorFuns = list('first' = IPair_first_set, 'second' = IPair_second_set);
  ;        idx = pmatch(name, names(accessorFuns));
  if(is.na(idx)) 
  return(callNextMethod(x, name, value));
  f = accessorFuns[[idx]];
  f(x, value);
  x;
}


);
setMethod('[[<-', c('_p_std__pairT_int_int_t', 'character'),function(x, i, j, ..., value)

{
  name = i;
  accessorFuns = list('first' = IPair_first_set, 'second' = IPair_second_set);
  ;        idx = pmatch(name, names(accessorFuns));
  if(is.na(idx)) 
  return(callNextMethod(x, name, value));
  f = accessorFuns[[idx]];
  f(x, value);
  x;
}


);
# end of accessor method for std::pair< int,int >
setMethod('delete', '_p_std__pairT_int_int_t', function(obj) {delete_std__pairT_int_int_t(obj)})
# Start definition of copy functions & methods for std::pair<(int,int)>
CopyToR_std__pairT_int_int_t = function(value, obj = new("std::pair<(int,int)>"))
{
  obj@first = value$first;
  obj@second = value$second;
  obj;
}



CopyToC_std__pairT_int_int_t = function(value, obj)
{
  obj$first = value@first;
  obj$second = value@second;
  obj
}



# Start definition of copy methods for std::pair<(int,int)>
setMethod('copyToR', '_p_std__pairT_int_int_t', CopyToR_std__pairT_int_int_t);
setMethod('copyToC', 'std::pair<(int,int)>', CopyToC_std__pairT_int_int_t);

# End definition of copy methods for std::pair<(int,int)>
# End definition of copy functions & methods for std::pair<(int,int)>
# Start of new_DPair

`DPair__SWIG_0` = function()
{
  ;ans = .Call('R_swig_new_DPair__SWIG_0', PACKAGE='octrar');
  ans <- if (is.null(ans)) ans
  else new("_p_std__pairT_double_double_t", ref=ans);
  
  reg.finalizer(ans@ref, delete_DPair);
  ans
  
}

attr(`DPair__SWIG_0`, 'returnType') = '_p_std__pairT_double_double_t'
class(`DPair__SWIG_0`) = c("SWIGFunction", class('DPair__SWIG_0'))

# Start of new_DPair

`DPair__SWIG_1` = function(first, second)
{
  ;ans = .Call('R_swig_new_DPair__SWIG_1', first, second, PACKAGE='octrar');
  ans <- if (is.null(ans)) ans
  else new("_p_std__pairT_double_double_t", ref=ans);
  
  reg.finalizer(ans@ref, delete_DPair);
  ans
  
}

attr(`DPair__SWIG_1`, 'returnType') = '_p_std__pairT_double_double_t'
attr(`DPair__SWIG_1`, "inputTypes") = c('numeric', 'numeric')
class(`DPair__SWIG_1`) = c("SWIGFunction", class('DPair__SWIG_1'))

# Start of new_DPair

`DPair__SWIG_2` = function(other)
{
  if (inherits(other, "ExternalReference")) other = slot(other,"ref"); 
  ;ans = .Call('R_swig_new_DPair__SWIG_2', other, PACKAGE='octrar');
  ans <- if (is.null(ans)) ans
  else new("_p_std__pairT_double_double_t", ref=ans);
  
  reg.finalizer(ans@ref, delete_DPair);
  ans
  
}

attr(`DPair__SWIG_2`, 'returnType') = '_p_std__pairT_double_double_t'
attr(`DPair__SWIG_2`, "inputTypes") = c('_p_std__pairT_double_double_t')
class(`DPair__SWIG_2`) = c("SWIGFunction", class('DPair__SWIG_2'))

`DPair` <- function(...) {
  argtypes <- mapply(class, list(...));
  argv <- list(...);
  argc <- length(argtypes);
  f <- NULL;
# dispatch functions 3
  if (argc == 0) {
    f <- DPair__SWIG_0; 
  } else if (argc == 1) {
    if ( extends(argtypes[1], '_p_std__pairT_double_double_t') && length(argv[[1]]) == 1 ) {
      f <- DPair__SWIG_2; 
    }
  } else if (argc == 2) {
    if (( is.numeric(argv[[1]]) && length(argv[[1]]) == 1 ) && ( is.numeric(argv[[2]]) && length(argv[[2]]) == 1 )) {
      f <- DPair__SWIG_1; 
    }
  };
  if (is.null(f)) {
    stop("cannot find overloaded function for DPair with argtypes (",toString(argtypes),")");
  };
  f(...);
}

# Dispatch function
# Start of DPair_first_set

`DPair_first_set` = function(self, s_first)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref"); 
  
  ;.Call('R_swig_DPair_first_set', self, s_first, PACKAGE='octrar');
  
}

attr(`DPair_first_set`, 'returnType') = 'void'
attr(`DPair_first_set`, "inputTypes") = c('_p_std__pairT_double_double_t', 'numeric')
class(`DPair_first_set`) = c("SWIGFunction", class('DPair_first_set'))

# Start of DPair_first_get

`DPair_first_get` = function(self, .copy = FALSE)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref"); 
  ;.Call('R_swig_DPair_first_get', self, as.logical(.copy), PACKAGE='octrar');
  
}

attr(`DPair_first_get`, 'returnType') = 'numeric'
attr(`DPair_first_get`, "inputTypes") = c('_p_std__pairT_double_double_t')
class(`DPair_first_get`) = c("SWIGFunction", class('DPair_first_get'))

# Start of DPair_second_set

`DPair_second_set` = function(self, s_second)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref"); 
  
  ;.Call('R_swig_DPair_second_set', self, s_second, PACKAGE='octrar');
  
}

attr(`DPair_second_set`, 'returnType') = 'void'
attr(`DPair_second_set`, "inputTypes") = c('_p_std__pairT_double_double_t', 'numeric')
class(`DPair_second_set`) = c("SWIGFunction", class('DPair_second_set'))

# Start of DPair_second_get

`DPair_second_get` = function(self, .copy = FALSE)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref"); 
  ;.Call('R_swig_DPair_second_get', self, as.logical(.copy), PACKAGE='octrar');
  
}

attr(`DPair_second_get`, 'returnType') = 'numeric'
attr(`DPair_second_get`, "inputTypes") = c('_p_std__pairT_double_double_t')
class(`DPair_second_get`) = c("SWIGFunction", class('DPair_second_get'))

# Start of delete_DPair

`delete_DPair` = function(self)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref"); 
  ;.Call('R_swig_delete_DPair', self, PACKAGE='octrar');
  
}

attr(`delete_DPair`, 'returnType') = 'void'
attr(`delete_DPair`, "inputTypes") = c('_p_std__pairT_double_double_t')
class(`delete_DPair`) = c("SWIGFunction", class('delete_DPair'))

# Start of accessor method for std::pair< double,double >
setMethod('$', '_p_std__pairT_double_double_t', function(x, name)

{
  accessorFuns = list('first' = DPair_first_get, 'second' = DPair_second_get);
  vaccessors = c('first', 'second');
  ;        idx = pmatch(name, names(accessorFuns));
  if(is.na(idx)) 
  return(callNextMethod(x, name));
  f = accessorFuns[[idx]];
  if (is.na(match(name, vaccessors))) function(...){
    f(x, ...)
  } else f(x);
}


);
# end of accessor method for std::pair< double,double >
# Start of accessor method for std::pair< double,double >
setMethod('$<-', '_p_std__pairT_double_double_t', function(x, name, value)

{
  accessorFuns = list('first' = DPair_first_set, 'second' = DPair_second_set);
  ;        idx = pmatch(name, names(accessorFuns));
  if(is.na(idx)) 
  return(callNextMethod(x, name, value));
  f = accessorFuns[[idx]];
  f(x, value);
  x;
}


);
setMethod('[[<-', c('_p_std__pairT_double_double_t', 'character'),function(x, i, j, ..., value)

{
  name = i;
  accessorFuns = list('first' = DPair_first_set, 'second' = DPair_second_set);
  ;        idx = pmatch(name, names(accessorFuns));
  if(is.na(idx)) 
  return(callNextMethod(x, name, value));
  f = accessorFuns[[idx]];
  f(x, value);
  x;
}


);
# end of accessor method for std::pair< double,double >
setMethod('delete', '_p_std__pairT_double_double_t', function(obj) {delete_std__pairT_double_double_t(obj)})
# Start definition of copy functions & methods for std::pair<(double,double)>
CopyToR_std__pairT_double_double_t = function(value, obj = new("std::pair<(double,double)>"))
{
  obj@first = value$first;
  obj@second = value$second;
  obj;
}



CopyToC_std__pairT_double_double_t = function(value, obj)
{
  obj$first = value@first;
  obj$second = value@second;
  obj
}



# Start definition of copy methods for std::pair<(double,double)>
setMethod('copyToR', '_p_std__pairT_double_double_t', CopyToR_std__pairT_double_double_t);
setMethod('copyToC', 'std::pair<(double,double)>', CopyToC_std__pairT_double_double_t);

# End definition of copy methods for std::pair<(double,double)>
# End definition of copy functions & methods for std::pair<(double,double)>
# Start of IVector___nonzero__

`IVector___nonzero__` = function(self, .copy = FALSE)
{
  self = as.integer(self);
  ;.Call('R_swig_IVector___nonzero__', self, as.logical(.copy), PACKAGE='octrar');
  
}

attr(`IVector___nonzero__`, 'returnType') = 'logical'
attr(`IVector___nonzero__`, "inputTypes") = c('_p_std__vectorT_int_t')
class(`IVector___nonzero__`) = c("SWIGFunction", class('IVector___nonzero__'))

# Start of IVector___len__

`IVector___len__` = function(self, .copy = FALSE)
{
  self = as.integer(self);
  ;.Call('R_swig_IVector___len__', self, as.logical(.copy), PACKAGE='octrar');
  
}

attr(`IVector___len__`, 'returnType') = 'integer'
attr(`IVector___len__`, "inputTypes") = c('_p_std__vectorT_int_t')
class(`IVector___len__`) = c("SWIGFunction", class('IVector___len__'))

# Start of IVector_pop

`IVector_pop` = function(self, .copy = FALSE)
{
  self = as.integer(self);
  ;.Call('R_swig_IVector_pop', self, as.logical(.copy), PACKAGE='octrar');
  
}

attr(`IVector_pop`, 'returnType') = 'integer'
attr(`IVector_pop`, "inputTypes") = c('_p_std__vectorT_int_t')
class(`IVector_pop`) = c("SWIGFunction", class('IVector_pop'))

# Start of IVector___getslice__

`IVector___getslice__` = function(self, i, j)
{
  self = as.integer(self);
  i = as.integer(i);
  
  if(length(i) > 1) {
    warning("using only the first element of i");
  };
  
  j = as.integer(j);
  
  if(length(j) > 1) {
    warning("using only the first element of j");
  };
  
  ;.Call('R_swig_IVector___getslice__', self, i, j, PACKAGE='octrar');
  
}

attr(`IVector___getslice__`, 'returnType') = '_p_std__vectorT_int_t'
attr(`IVector___getslice__`, "inputTypes") = c('_p_std__vectorT_int_t', 'integer', 'integer')
class(`IVector___getslice__`) = c("SWIGFunction", class('IVector___getslice__'))

# Start of IVector___setslice__

`IVector___setslice__` = function(self, i, j, is)
{
  self = as.integer(self);
  i = as.integer(i);
  
  if(length(i) > 1) {
    warning("using only the first element of i");
  };
  
  j = as.integer(j);
  
  if(length(j) > 1) {
    warning("using only the first element of j");
  };
  
  is = as.integer(is);
  ;.Call('R_swig_IVector___setslice__', self, i, j, is, PACKAGE='octrar');
  
}

attr(`IVector___setslice__`, 'returnType') = 'void'
attr(`IVector___setslice__`, "inputTypes") = c('_p_std__vectorT_int_t', 'integer', 'integer', '_p_std__vectorT_int_t')
class(`IVector___setslice__`) = c("SWIGFunction", class('IVector___setslice__'))

# Start of IVector___delslice__

`IVector___delslice__` = function(self, i, j)
{
  self = as.integer(self);
  i = as.integer(i);
  
  if(length(i) > 1) {
    warning("using only the first element of i");
  };
  
  j = as.integer(j);
  
  if(length(j) > 1) {
    warning("using only the first element of j");
  };
  
  ;.Call('R_swig_IVector___delslice__', self, i, j, PACKAGE='octrar');
  
}

attr(`IVector___delslice__`, 'returnType') = 'void'
attr(`IVector___delslice__`, "inputTypes") = c('_p_std__vectorT_int_t', 'integer', 'integer')
class(`IVector___delslice__`) = c("SWIGFunction", class('IVector___delslice__'))

# Start of IVector___delitem__

`IVector___delitem__` = function(self, i)
{
  self = as.integer(self);
  i = as.integer(i);
  
  if(length(i) > 1) {
    warning("using only the first element of i");
  };
  
  ;.Call('R_swig_IVector___delitem__', self, i, PACKAGE='octrar');
  
}

attr(`IVector___delitem__`, 'returnType') = 'void'
attr(`IVector___delitem__`, "inputTypes") = c('_p_std__vectorT_int_t', 'integer')
class(`IVector___delitem__`) = c("SWIGFunction", class('IVector___delitem__'))

# Start of IVector___getitem__

`IVector___getitem__` = function(self, i, .copy = FALSE)
{
  self = as.integer(self);
  i = as.integer(i);
  
  if(length(i) > 1) {
    warning("using only the first element of i");
  };
  
  ;.Call('R_swig_IVector___getitem__', self, i, as.logical(.copy), PACKAGE='octrar');
  
}

attr(`IVector___getitem__`, 'returnType') = 'integer'
attr(`IVector___getitem__`, "inputTypes") = c('_p_std__vectorT_int_t', 'integer')
class(`IVector___getitem__`) = c("SWIGFunction", class('IVector___getitem__'))

# Start of IVector___setitem__

`IVector___setitem__` = function(self, i, x)
{
  self = as.integer(self);
  i = as.integer(i);
  
  if(length(i) > 1) {
    warning("using only the first element of i");
  };
  
  x = as.integer(x);
  ;.Call('R_swig_IVector___setitem__', self, i, x, PACKAGE='octrar');
  
}

attr(`IVector___setitem__`, 'returnType') = 'void'
attr(`IVector___setitem__`, "inputTypes") = c('_p_std__vectorT_int_t', 'integer', 'integer')
class(`IVector___setitem__`) = c("SWIGFunction", class('IVector___setitem__'))

# Start of IVector_append

`IVector_append` = function(self, x)
{
  self = as.integer(self);
  x = as.integer(x);
  ;.Call('R_swig_IVector_append', self, x, PACKAGE='octrar');
  
}

attr(`IVector_append`, 'returnType') = 'void'
attr(`IVector_append`, "inputTypes") = c('_p_std__vectorT_int_t', 'integer')
class(`IVector_append`) = c("SWIGFunction", class('IVector_append'))

# Start of new_IVector

`IVector__SWIG_0` = function()
{
  ;.Call('R_swig_new_IVector__SWIG_0', PACKAGE='octrar');
  
}

attr(`IVector__SWIG_0`, 'returnType') = '_p_std__vectorT_int_t'
class(`IVector__SWIG_0`) = c("SWIGFunction", class('IVector__SWIG_0'))

# Start of new_IVector

`IVector__SWIG_1` = function(other)
{
  other = as.integer(other);
  ;.Call('R_swig_new_IVector__SWIG_1', other, PACKAGE='octrar');
  
}

attr(`IVector__SWIG_1`, 'returnType') = '_p_std__vectorT_int_t'
attr(`IVector__SWIG_1`, "inputTypes") = c('_p_std__vectorT_int_t')
class(`IVector__SWIG_1`) = c("SWIGFunction", class('IVector__SWIG_1'))

# Start of IVector_empty

`IVector_empty` = function(self, .copy = FALSE)
{
  self = as.integer(self);
  ;.Call('R_swig_IVector_empty', self, as.logical(.copy), PACKAGE='octrar');
  
}

attr(`IVector_empty`, 'returnType') = 'logical'
attr(`IVector_empty`, "inputTypes") = c('_p_std__vectorT_int_t')
class(`IVector_empty`) = c("SWIGFunction", class('IVector_empty'))

# Start of IVector_size

`IVector_size` = function(self, .copy = FALSE)
{
  self = as.integer(self);
  ;.Call('R_swig_IVector_size', self, as.logical(.copy), PACKAGE='octrar');
  
}

attr(`IVector_size`, 'returnType') = 'integer'
attr(`IVector_size`, "inputTypes") = c('_p_std__vectorT_int_t')
class(`IVector_size`) = c("SWIGFunction", class('IVector_size'))

# Start of IVector_swap

`IVector_swap` = function(self, v)
{
  self = as.integer(self);
  v = as.integer(v);
  ;.Call('R_swig_IVector_swap', self, v, PACKAGE='octrar');
  
}

attr(`IVector_swap`, 'returnType') = 'void'
attr(`IVector_swap`, "inputTypes") = c('_p_std__vectorT_int_t', '_p_std__vectorT_int_t')
class(`IVector_swap`) = c("SWIGFunction", class('IVector_swap'))

# Start of IVector_clear

`IVector_clear` = function(self)
{
  self = as.integer(self);
  ;.Call('R_swig_IVector_clear', self, PACKAGE='octrar');
  
}

attr(`IVector_clear`, 'returnType') = 'void'
attr(`IVector_clear`, "inputTypes") = c('_p_std__vectorT_int_t')
class(`IVector_clear`) = c("SWIGFunction", class('IVector_clear'))

# Start of IVector_get_allocator

`IVector_get_allocator` = function(self, .copy = FALSE)
{
  self = as.integer(self);
  ;ans = .Call('R_swig_IVector_get_allocator', self, as.logical(.copy), PACKAGE='octrar');
  ans <- if (is.null(ans)) ans
  else new("_p_std__allocatorT_int_t", ref=ans);
  
  ans
  
}

attr(`IVector_get_allocator`, 'returnType') = '_p_std__allocatorT_int_t'
attr(`IVector_get_allocator`, "inputTypes") = c('_p_std__vectorT_int_t')
class(`IVector_get_allocator`) = c("SWIGFunction", class('IVector_get_allocator'))

# Start of new_IVector

`IVector__SWIG_2` = function(size)
{
  size = as.integer(size);
  
  if(length(size) > 1) {
    warning("using only the first element of size");
  };
  
  ;.Call('R_swig_new_IVector__SWIG_2', size, PACKAGE='octrar');
  
}

attr(`IVector__SWIG_2`, 'returnType') = '_p_std__vectorT_int_t'
attr(`IVector__SWIG_2`, "inputTypes") = c('integer')
class(`IVector__SWIG_2`) = c("SWIGFunction", class('IVector__SWIG_2'))

# Start of IVector_pop_back

`IVector_pop_back` = function(self)
{
  self = as.integer(self);
  ;.Call('R_swig_IVector_pop_back', self, PACKAGE='octrar');
  
}

attr(`IVector_pop_back`, 'returnType') = 'void'
attr(`IVector_pop_back`, "inputTypes") = c('_p_std__vectorT_int_t')
class(`IVector_pop_back`) = c("SWIGFunction", class('IVector_pop_back'))

# Start of IVector_resize

`IVector_resize__SWIG_0` = function(self, new_size)
{
  self = as.integer(self);
  new_size = as.integer(new_size);
  
  if(length(new_size) > 1) {
    warning("using only the first element of new_size");
  };
  
  ;.Call('R_swig_IVector_resize__SWIG_0', self, new_size, PACKAGE='octrar');
  
}

attr(`IVector_resize__SWIG_0`, 'returnType') = 'void'
attr(`IVector_resize__SWIG_0`, "inputTypes") = c('_p_std__vectorT_int_t', 'integer')
class(`IVector_resize__SWIG_0`) = c("SWIGFunction", class('IVector_resize__SWIG_0'))

# Start of new_IVector

`IVector__SWIG_3` = function(size, value)
{
  size = as.integer(size);
  
  if(length(size) > 1) {
    warning("using only the first element of size");
  };
  
  value = as.integer(value);
  ;.Call('R_swig_new_IVector__SWIG_3', size, value, PACKAGE='octrar');
  
}

attr(`IVector__SWIG_3`, 'returnType') = '_p_std__vectorT_int_t'
attr(`IVector__SWIG_3`, "inputTypes") = c('integer', 'integer')
class(`IVector__SWIG_3`) = c("SWIGFunction", class('IVector__SWIG_3'))

`IVector` <- function(...) {
  argtypes <- mapply(class, list(...));
  argv <- list(...);
  argc <- length(argtypes);
  f <- NULL;
# dispatch functions 4
  if (argc == 0) {
    f <- IVector__SWIG_0; 
  } else if (argc == 1) {
    if ( (is.integer(argv[[1]]) || is.numeric(argv[[1]])) && length(argv[[1]]) == 1 ) {
      f <- IVector__SWIG_2; 
    }
    else if ( is.integer(argv[[1]]) || is.numeric(argv[[1]]) ) {
      f <- IVector__SWIG_1; 
    }
  } else if (argc == 2) {
    if (( (is.integer(argv[[1]]) || is.numeric(argv[[1]])) && length(argv[[1]]) == 1 ) && ( (is.integer(argv[[2]]) || is.numeric(argv[[2]])) && length(argv[[2]]) == 1 )) {
      f <- IVector__SWIG_3; 
    }
  };
  if (is.null(f)) {
    stop("cannot find overloaded function for IVector with argtypes (",toString(argtypes),")");
  };
  f(...);
}

# Dispatch function
# Start of IVector_push_back

`IVector_push_back` = function(self, x)
{
  self = as.integer(self);
  x = as.integer(x);
  ;.Call('R_swig_IVector_push_back', self, x, PACKAGE='octrar');
  
}

attr(`IVector_push_back`, 'returnType') = 'void'
attr(`IVector_push_back`, "inputTypes") = c('_p_std__vectorT_int_t', 'integer')
class(`IVector_push_back`) = c("SWIGFunction", class('IVector_push_back'))

# Start of IVector_front

`IVector_front` = function(self, .copy = FALSE)
{
  self = as.integer(self);
  ;.Call('R_swig_IVector_front', self, as.logical(.copy), PACKAGE='octrar');
  
}

attr(`IVector_front`, 'returnType') = 'integer'
attr(`IVector_front`, "inputTypes") = c('_p_std__vectorT_int_t')
class(`IVector_front`) = c("SWIGFunction", class('IVector_front'))

# Start of IVector_back

`IVector_back` = function(self, .copy = FALSE)
{
  self = as.integer(self);
  ;.Call('R_swig_IVector_back', self, as.logical(.copy), PACKAGE='octrar');
  
}

attr(`IVector_back`, 'returnType') = 'integer'
attr(`IVector_back`, "inputTypes") = c('_p_std__vectorT_int_t')
class(`IVector_back`) = c("SWIGFunction", class('IVector_back'))

# Start of IVector_assign

`IVector_assign` = function(self, n, x)
{
  self = as.integer(self);
  n = as.integer(n);
  
  if(length(n) > 1) {
    warning("using only the first element of n");
  };
  
  x = as.integer(x);
  ;.Call('R_swig_IVector_assign', self, n, x, PACKAGE='octrar');
  
}

attr(`IVector_assign`, 'returnType') = 'void'
attr(`IVector_assign`, "inputTypes") = c('_p_std__vectorT_int_t', 'integer', 'integer')
class(`IVector_assign`) = c("SWIGFunction", class('IVector_assign'))

# Start of IVector_resize

`IVector_resize__SWIG_1` = function(self, new_size, x)
{
  self = as.integer(self);
  new_size = as.integer(new_size);
  
  if(length(new_size) > 1) {
    warning("using only the first element of new_size");
  };
  
  x = as.integer(x);
  ;.Call('R_swig_IVector_resize__SWIG_1', self, new_size, x, PACKAGE='octrar');
  
}

attr(`IVector_resize__SWIG_1`, 'returnType') = 'void'
attr(`IVector_resize__SWIG_1`, "inputTypes") = c('_p_std__vectorT_int_t', 'integer', 'integer')
class(`IVector_resize__SWIG_1`) = c("SWIGFunction", class('IVector_resize__SWIG_1'))

`IVector_resize` <- function(...) {
  argtypes <- mapply(class, list(...));
  argv <- list(...);
  argc <- length(argtypes);
  f <- NULL;
# dispatch functions 2
  if (argc == 2) {
    if (( is.integer(argv[[1]]) || is.numeric(argv[[1]]) ) && ( (is.integer(argv[[2]]) || is.numeric(argv[[2]])) && length(argv[[2]]) == 1 )) {
      f <- IVector_resize__SWIG_0; 
    }
  } else if (argc == 3) {
    if (( is.integer(argv[[1]]) || is.numeric(argv[[1]]) ) && ( (is.integer(argv[[2]]) || is.numeric(argv[[2]])) && length(argv[[2]]) == 1 ) && ( (is.integer(argv[[3]]) || is.numeric(argv[[3]])) && length(argv[[3]]) == 1 )) {
      f <- IVector_resize__SWIG_1; 
    }
  };
  if (is.null(f)) {
    stop("cannot find overloaded function for IVector_resize with argtypes (",toString(argtypes),")");
  };
  f(...);
}

# Dispatch function
# Start of IVector_reserve

`IVector_reserve` = function(self, n)
{
  self = as.integer(self);
  n = as.integer(n);
  
  if(length(n) > 1) {
    warning("using only the first element of n");
  };
  
  ;.Call('R_swig_IVector_reserve', self, n, PACKAGE='octrar');
  
}

attr(`IVector_reserve`, 'returnType') = 'void'
attr(`IVector_reserve`, "inputTypes") = c('_p_std__vectorT_int_t', 'integer')
class(`IVector_reserve`) = c("SWIGFunction", class('IVector_reserve'))

# Start of IVector_capacity

`IVector_capacity` = function(self, .copy = FALSE)
{
  self = as.integer(self);
  ;.Call('R_swig_IVector_capacity', self, as.logical(.copy), PACKAGE='octrar');
  
}

attr(`IVector_capacity`, 'returnType') = 'integer'
attr(`IVector_capacity`, "inputTypes") = c('_p_std__vectorT_int_t')
class(`IVector_capacity`) = c("SWIGFunction", class('IVector_capacity'))

# Start of delete_IVector

`delete_IVector` = function(self)
{
  self = as.integer(self);
  ;.Call('R_swig_delete_IVector', self, PACKAGE='octrar');
  
}

attr(`delete_IVector`, 'returnType') = 'void'
attr(`delete_IVector`, "inputTypes") = c('_p_std__vectorT_int_t')
class(`delete_IVector`) = c("SWIGFunction", class('delete_IVector'))

# Start of accessor method for std::vector< int >
setMethod('$', '_p_std__vectorT_int_t', function(x, name)

{
  accessorFuns = list('__nonzero__' = IVector___nonzero__, '__len__' = IVector___len__, 'pop' = IVector_pop, '__getslice__' = IVector___getslice__, '__setslice__' = IVector___setslice__, '__delslice__' = IVector___delslice__, '__delitem__' = IVector___delitem__, '__getitem__' = IVector___getitem__, '__setitem__' = IVector___setitem__, 'append' = IVector_append, 'empty' = IVector_empty, 'size' = IVector_size, 'swap' = IVector_swap, 'clear' = IVector_clear, 'get_allocator' = IVector_get_allocator, 'pop_back' = IVector_pop_back, 'resize' = IVector_resize, 'push_back' = IVector_push_back, 'front' = IVector_front, 'back' = IVector_back, 'assign' = IVector_assign, 'reserve' = IVector_reserve, 'capacity' = IVector_capacity);
  ;        idx = pmatch(name, names(accessorFuns));
  if(is.na(idx)) 
  return(callNextMethod(x, name));
  f = accessorFuns[[idx]];
  function(...){
    f(x, ...)
  };
}


);
# end of accessor method for std::vector< int >
setMethod('delete', '_p_std__vectorT_int_t', function(obj) {delete_std__vectorT_int_t(obj)})
# Start of DVector___nonzero__

`DVector___nonzero__` = function(self, .copy = FALSE)
{
  self = as.numeric(self);
  ;.Call('R_swig_DVector___nonzero__', self, as.logical(.copy), PACKAGE='octrar');
  
}

attr(`DVector___nonzero__`, 'returnType') = 'logical'
attr(`DVector___nonzero__`, "inputTypes") = c('_p_std__vectorT_double_t')
class(`DVector___nonzero__`) = c("SWIGFunction", class('DVector___nonzero__'))

# Start of DVector___len__

`DVector___len__` = function(self, .copy = FALSE)
{
  self = as.numeric(self);
  ;.Call('R_swig_DVector___len__', self, as.logical(.copy), PACKAGE='octrar');
  
}

attr(`DVector___len__`, 'returnType') = 'integer'
attr(`DVector___len__`, "inputTypes") = c('_p_std__vectorT_double_t')
class(`DVector___len__`) = c("SWIGFunction", class('DVector___len__'))

# Start of DVector_pop

`DVector_pop` = function(self, .copy = FALSE)
{
  self = as.numeric(self);
  ;.Call('R_swig_DVector_pop', self, as.logical(.copy), PACKAGE='octrar');
  
}

attr(`DVector_pop`, 'returnType') = 'numeric'
attr(`DVector_pop`, "inputTypes") = c('_p_std__vectorT_double_t')
class(`DVector_pop`) = c("SWIGFunction", class('DVector_pop'))

# Start of DVector___getslice__

`DVector___getslice__` = function(self, i, j)
{
  self = as.numeric(self);
  i = as.integer(i);
  
  if(length(i) > 1) {
    warning("using only the first element of i");
  };
  
  j = as.integer(j);
  
  if(length(j) > 1) {
    warning("using only the first element of j");
  };
  
  ;.Call('R_swig_DVector___getslice__', self, i, j, PACKAGE='octrar');
  
}

attr(`DVector___getslice__`, 'returnType') = '_p_std__vectorT_double_t'
attr(`DVector___getslice__`, "inputTypes") = c('_p_std__vectorT_double_t', 'integer', 'integer')
class(`DVector___getslice__`) = c("SWIGFunction", class('DVector___getslice__'))

# Start of DVector___setslice__

`DVector___setslice__` = function(self, i, j, is)
{
  self = as.numeric(self);
  i = as.integer(i);
  
  if(length(i) > 1) {
    warning("using only the first element of i");
  };
  
  j = as.integer(j);
  
  if(length(j) > 1) {
    warning("using only the first element of j");
  };
  
  is = as.numeric(is);
  ;.Call('R_swig_DVector___setslice__', self, i, j, is, PACKAGE='octrar');
  
}

attr(`DVector___setslice__`, 'returnType') = 'void'
attr(`DVector___setslice__`, "inputTypes") = c('_p_std__vectorT_double_t', 'integer', 'integer', '_p_std__vectorT_double_t')
class(`DVector___setslice__`) = c("SWIGFunction", class('DVector___setslice__'))

# Start of DVector___delslice__

`DVector___delslice__` = function(self, i, j)
{
  self = as.numeric(self);
  i = as.integer(i);
  
  if(length(i) > 1) {
    warning("using only the first element of i");
  };
  
  j = as.integer(j);
  
  if(length(j) > 1) {
    warning("using only the first element of j");
  };
  
  ;.Call('R_swig_DVector___delslice__', self, i, j, PACKAGE='octrar');
  
}

attr(`DVector___delslice__`, 'returnType') = 'void'
attr(`DVector___delslice__`, "inputTypes") = c('_p_std__vectorT_double_t', 'integer', 'integer')
class(`DVector___delslice__`) = c("SWIGFunction", class('DVector___delslice__'))

# Start of DVector___delitem__

`DVector___delitem__` = function(self, i)
{
  self = as.numeric(self);
  i = as.integer(i);
  
  if(length(i) > 1) {
    warning("using only the first element of i");
  };
  
  ;.Call('R_swig_DVector___delitem__', self, i, PACKAGE='octrar');
  
}

attr(`DVector___delitem__`, 'returnType') = 'void'
attr(`DVector___delitem__`, "inputTypes") = c('_p_std__vectorT_double_t', 'integer')
class(`DVector___delitem__`) = c("SWIGFunction", class('DVector___delitem__'))

# Start of DVector___getitem__

`DVector___getitem__` = function(self, i, .copy = FALSE)
{
  self = as.numeric(self);
  i = as.integer(i);
  
  if(length(i) > 1) {
    warning("using only the first element of i");
  };
  
  ;.Call('R_swig_DVector___getitem__', self, i, as.logical(.copy), PACKAGE='octrar');
  
}

attr(`DVector___getitem__`, 'returnType') = 'numeric'
attr(`DVector___getitem__`, "inputTypes") = c('_p_std__vectorT_double_t', 'integer')
class(`DVector___getitem__`) = c("SWIGFunction", class('DVector___getitem__'))

# Start of DVector___setitem__

`DVector___setitem__` = function(self, i, x)
{
  self = as.numeric(self);
  i = as.integer(i);
  
  if(length(i) > 1) {
    warning("using only the first element of i");
  };
  
  
  ;.Call('R_swig_DVector___setitem__', self, i, x, PACKAGE='octrar');
  
}

attr(`DVector___setitem__`, 'returnType') = 'void'
attr(`DVector___setitem__`, "inputTypes") = c('_p_std__vectorT_double_t', 'integer', 'numeric')
class(`DVector___setitem__`) = c("SWIGFunction", class('DVector___setitem__'))

# Start of DVector_append

`DVector_append` = function(self, x)
{
  self = as.numeric(self);
  
  ;.Call('R_swig_DVector_append', self, x, PACKAGE='octrar');
  
}

attr(`DVector_append`, 'returnType') = 'void'
attr(`DVector_append`, "inputTypes") = c('_p_std__vectorT_double_t', 'numeric')
class(`DVector_append`) = c("SWIGFunction", class('DVector_append'))

# Start of new_DVector

`DVector__SWIG_0` = function()
{
  ;.Call('R_swig_new_DVector__SWIG_0', PACKAGE='octrar');
  
}

attr(`DVector__SWIG_0`, 'returnType') = '_p_std__vectorT_double_t'
class(`DVector__SWIG_0`) = c("SWIGFunction", class('DVector__SWIG_0'))

# Start of new_DVector

`DVector__SWIG_1` = function(other)
{
  other = as.numeric(other);
  ;.Call('R_swig_new_DVector__SWIG_1', other, PACKAGE='octrar');
  
}

attr(`DVector__SWIG_1`, 'returnType') = '_p_std__vectorT_double_t'
attr(`DVector__SWIG_1`, "inputTypes") = c('_p_std__vectorT_double_t')
class(`DVector__SWIG_1`) = c("SWIGFunction", class('DVector__SWIG_1'))

# Start of DVector_empty

`DVector_empty` = function(self, .copy = FALSE)
{
  self = as.numeric(self);
  ;.Call('R_swig_DVector_empty', self, as.logical(.copy), PACKAGE='octrar');
  
}

attr(`DVector_empty`, 'returnType') = 'logical'
attr(`DVector_empty`, "inputTypes") = c('_p_std__vectorT_double_t')
class(`DVector_empty`) = c("SWIGFunction", class('DVector_empty'))

# Start of DVector_size

`DVector_size` = function(self, .copy = FALSE)
{
  self = as.numeric(self);
  ;.Call('R_swig_DVector_size', self, as.logical(.copy), PACKAGE='octrar');
  
}

attr(`DVector_size`, 'returnType') = 'integer'
attr(`DVector_size`, "inputTypes") = c('_p_std__vectorT_double_t')
class(`DVector_size`) = c("SWIGFunction", class('DVector_size'))

# Start of DVector_swap

`DVector_swap` = function(self, v)
{
  self = as.numeric(self);
  v = as.numeric(v);
  ;.Call('R_swig_DVector_swap', self, v, PACKAGE='octrar');
  
}

attr(`DVector_swap`, 'returnType') = 'void'
attr(`DVector_swap`, "inputTypes") = c('_p_std__vectorT_double_t', '_p_std__vectorT_double_t')
class(`DVector_swap`) = c("SWIGFunction", class('DVector_swap'))

# Start of DVector_clear

`DVector_clear` = function(self)
{
  self = as.numeric(self);
  ;.Call('R_swig_DVector_clear', self, PACKAGE='octrar');
  
}

attr(`DVector_clear`, 'returnType') = 'void'
attr(`DVector_clear`, "inputTypes") = c('_p_std__vectorT_double_t')
class(`DVector_clear`) = c("SWIGFunction", class('DVector_clear'))

# Start of DVector_get_allocator

`DVector_get_allocator` = function(self, .copy = FALSE)
{
  self = as.numeric(self);
  ;ans = .Call('R_swig_DVector_get_allocator', self, as.logical(.copy), PACKAGE='octrar');
  ans <- if (is.null(ans)) ans
  else new("_p_std__allocatorT_double_t", ref=ans);
  
  ans
  
}

attr(`DVector_get_allocator`, 'returnType') = '_p_std__allocatorT_double_t'
attr(`DVector_get_allocator`, "inputTypes") = c('_p_std__vectorT_double_t')
class(`DVector_get_allocator`) = c("SWIGFunction", class('DVector_get_allocator'))

# Start of new_DVector

`DVector__SWIG_2` = function(size)
{
  size = as.integer(size);
  
  if(length(size) > 1) {
    warning("using only the first element of size");
  };
  
  ;.Call('R_swig_new_DVector__SWIG_2', size, PACKAGE='octrar');
  
}

attr(`DVector__SWIG_2`, 'returnType') = '_p_std__vectorT_double_t'
attr(`DVector__SWIG_2`, "inputTypes") = c('integer')
class(`DVector__SWIG_2`) = c("SWIGFunction", class('DVector__SWIG_2'))

# Start of DVector_pop_back

`DVector_pop_back` = function(self)
{
  self = as.numeric(self);
  ;.Call('R_swig_DVector_pop_back', self, PACKAGE='octrar');
  
}

attr(`DVector_pop_back`, 'returnType') = 'void'
attr(`DVector_pop_back`, "inputTypes") = c('_p_std__vectorT_double_t')
class(`DVector_pop_back`) = c("SWIGFunction", class('DVector_pop_back'))

# Start of DVector_resize

`DVector_resize__SWIG_0` = function(self, new_size)
{
  self = as.numeric(self);
  new_size = as.integer(new_size);
  
  if(length(new_size) > 1) {
    warning("using only the first element of new_size");
  };
  
  ;.Call('R_swig_DVector_resize__SWIG_0', self, new_size, PACKAGE='octrar');
  
}

attr(`DVector_resize__SWIG_0`, 'returnType') = 'void'
attr(`DVector_resize__SWIG_0`, "inputTypes") = c('_p_std__vectorT_double_t', 'integer')
class(`DVector_resize__SWIG_0`) = c("SWIGFunction", class('DVector_resize__SWIG_0'))

# Start of new_DVector

`DVector__SWIG_3` = function(size, value)
{
  size = as.integer(size);
  
  if(length(size) > 1) {
    warning("using only the first element of size");
  };
  
  
  ;.Call('R_swig_new_DVector__SWIG_3', size, value, PACKAGE='octrar');
  
}

attr(`DVector__SWIG_3`, 'returnType') = '_p_std__vectorT_double_t'
attr(`DVector__SWIG_3`, "inputTypes") = c('integer', 'numeric')
class(`DVector__SWIG_3`) = c("SWIGFunction", class('DVector__SWIG_3'))

`DVector` <- function(...) {
  argtypes <- mapply(class, list(...));
  argv <- list(...);
  argc <- length(argtypes);
  f <- NULL;
# dispatch functions 4
  if (argc == 0) {
    f <- DVector__SWIG_0; 
  } else if (argc == 1) {
    if ( (is.integer(argv[[1]]) || is.numeric(argv[[1]])) && length(argv[[1]]) == 1 ) {
      f <- DVector__SWIG_2; 
    }
    else if ( is.numeric(argv[[1]]) ) {
      f <- DVector__SWIG_1; 
    }
  } else if (argc == 2) {
    if (( (is.integer(argv[[1]]) || is.numeric(argv[[1]])) && length(argv[[1]]) == 1 ) && ( is.numeric(argv[[2]]) && length(argv[[2]]) == 1 )) {
      f <- DVector__SWIG_3; 
    }
  };
  if (is.null(f)) {
    stop("cannot find overloaded function for DVector with argtypes (",toString(argtypes),")");
  };
  f(...);
}

# Dispatch function
# Start of DVector_push_back

`DVector_push_back` = function(self, x)
{
  self = as.numeric(self);
  
  ;.Call('R_swig_DVector_push_back', self, x, PACKAGE='octrar');
  
}

attr(`DVector_push_back`, 'returnType') = 'void'
attr(`DVector_push_back`, "inputTypes") = c('_p_std__vectorT_double_t', 'numeric')
class(`DVector_push_back`) = c("SWIGFunction", class('DVector_push_back'))

# Start of DVector_front

`DVector_front` = function(self, .copy = FALSE)
{
  self = as.numeric(self);
  ;.Call('R_swig_DVector_front', self, as.logical(.copy), PACKAGE='octrar');
  
}

attr(`DVector_front`, 'returnType') = 'numeric'
attr(`DVector_front`, "inputTypes") = c('_p_std__vectorT_double_t')
class(`DVector_front`) = c("SWIGFunction", class('DVector_front'))

# Start of DVector_back

`DVector_back` = function(self, .copy = FALSE)
{
  self = as.numeric(self);
  ;.Call('R_swig_DVector_back', self, as.logical(.copy), PACKAGE='octrar');
  
}

attr(`DVector_back`, 'returnType') = 'numeric'
attr(`DVector_back`, "inputTypes") = c('_p_std__vectorT_double_t')
class(`DVector_back`) = c("SWIGFunction", class('DVector_back'))

# Start of DVector_assign

`DVector_assign` = function(self, n, x)
{
  self = as.numeric(self);
  n = as.integer(n);
  
  if(length(n) > 1) {
    warning("using only the first element of n");
  };
  
  
  ;.Call('R_swig_DVector_assign', self, n, x, PACKAGE='octrar');
  
}

attr(`DVector_assign`, 'returnType') = 'void'
attr(`DVector_assign`, "inputTypes") = c('_p_std__vectorT_double_t', 'integer', 'numeric')
class(`DVector_assign`) = c("SWIGFunction", class('DVector_assign'))

# Start of DVector_resize

`DVector_resize__SWIG_1` = function(self, new_size, x)
{
  self = as.numeric(self);
  new_size = as.integer(new_size);
  
  if(length(new_size) > 1) {
    warning("using only the first element of new_size");
  };
  
  
  ;.Call('R_swig_DVector_resize__SWIG_1', self, new_size, x, PACKAGE='octrar');
  
}

attr(`DVector_resize__SWIG_1`, 'returnType') = 'void'
attr(`DVector_resize__SWIG_1`, "inputTypes") = c('_p_std__vectorT_double_t', 'integer', 'numeric')
class(`DVector_resize__SWIG_1`) = c("SWIGFunction", class('DVector_resize__SWIG_1'))

`DVector_resize` <- function(...) {
  argtypes <- mapply(class, list(...));
  argv <- list(...);
  argc <- length(argtypes);
  f <- NULL;
# dispatch functions 2
  if (argc == 2) {
    if (( is.numeric(argv[[1]]) ) && ( (is.integer(argv[[2]]) || is.numeric(argv[[2]])) && length(argv[[2]]) == 1 )) {
      f <- DVector_resize__SWIG_0; 
    }
  } else if (argc == 3) {
    if (( is.numeric(argv[[1]]) ) && ( (is.integer(argv[[2]]) || is.numeric(argv[[2]])) && length(argv[[2]]) == 1 ) && ( is.numeric(argv[[3]]) && length(argv[[3]]) == 1 )) {
      f <- DVector_resize__SWIG_1; 
    }
  };
  if (is.null(f)) {
    stop("cannot find overloaded function for DVector_resize with argtypes (",toString(argtypes),")");
  };
  f(...);
}

# Dispatch function
# Start of DVector_reserve

`DVector_reserve` = function(self, n)
{
  self = as.numeric(self);
  n = as.integer(n);
  
  if(length(n) > 1) {
    warning("using only the first element of n");
  };
  
  ;.Call('R_swig_DVector_reserve', self, n, PACKAGE='octrar');
  
}

attr(`DVector_reserve`, 'returnType') = 'void'
attr(`DVector_reserve`, "inputTypes") = c('_p_std__vectorT_double_t', 'integer')
class(`DVector_reserve`) = c("SWIGFunction", class('DVector_reserve'))

# Start of DVector_capacity

`DVector_capacity` = function(self, .copy = FALSE)
{
  self = as.numeric(self);
  ;.Call('R_swig_DVector_capacity', self, as.logical(.copy), PACKAGE='octrar');
  
}

attr(`DVector_capacity`, 'returnType') = 'integer'
attr(`DVector_capacity`, "inputTypes") = c('_p_std__vectorT_double_t')
class(`DVector_capacity`) = c("SWIGFunction", class('DVector_capacity'))

# Start of delete_DVector

`delete_DVector` = function(self)
{
  self = as.numeric(self);
  ;.Call('R_swig_delete_DVector', self, PACKAGE='octrar');
  
}

attr(`delete_DVector`, 'returnType') = 'void'
attr(`delete_DVector`, "inputTypes") = c('_p_std__vectorT_double_t')
class(`delete_DVector`) = c("SWIGFunction", class('delete_DVector'))

# Start of accessor method for std::vector< double >
setMethod('$', '_p_std__vectorT_double_t', function(x, name)

{
  accessorFuns = list('__nonzero__' = DVector___nonzero__, '__len__' = DVector___len__, 'pop' = DVector_pop, '__getslice__' = DVector___getslice__, '__setslice__' = DVector___setslice__, '__delslice__' = DVector___delslice__, '__delitem__' = DVector___delitem__, '__getitem__' = DVector___getitem__, '__setitem__' = DVector___setitem__, 'append' = DVector_append, 'empty' = DVector_empty, 'size' = DVector_size, 'swap' = DVector_swap, 'clear' = DVector_clear, 'get_allocator' = DVector_get_allocator, 'pop_back' = DVector_pop_back, 'resize' = DVector_resize, 'push_back' = DVector_push_back, 'front' = DVector_front, 'back' = DVector_back, 'assign' = DVector_assign, 'reserve' = DVector_reserve, 'capacity' = DVector_capacity);
  ;        idx = pmatch(name, names(accessorFuns));
  if(is.na(idx)) 
  return(callNextMethod(x, name));
  f = accessorFuns[[idx]];
  function(...){
    f(x, ...)
  };
}


);
# end of accessor method for std::vector< double >
setMethod('delete', '_p_std__vectorT_double_t', function(obj) {delete_std__vectorT_double_t(obj)})
# Start of SizeVector___nonzero__

`SizeVector___nonzero__` = function(self, .copy = FALSE)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref"); 
  ;.Call('R_swig_SizeVector___nonzero__', self, as.logical(.copy), PACKAGE='octrar');
  
}

attr(`SizeVector___nonzero__`, 'returnType') = 'logical'
attr(`SizeVector___nonzero__`, "inputTypes") = c('_p_std__vectorT_size_t_t')
class(`SizeVector___nonzero__`) = c("SWIGFunction", class('SizeVector___nonzero__'))

# Start of SizeVector___len__

`SizeVector___len__` = function(self, .copy = FALSE)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref"); 
  ;.Call('R_swig_SizeVector___len__', self, as.logical(.copy), PACKAGE='octrar');
  
}

attr(`SizeVector___len__`, 'returnType') = 'integer'
attr(`SizeVector___len__`, "inputTypes") = c('_p_std__vectorT_size_t_t')
class(`SizeVector___len__`) = c("SWIGFunction", class('SizeVector___len__'))

# Start of SizeVector_pop

`SizeVector_pop` = function(self, .copy = FALSE)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref"); 
  ;.Call('R_swig_SizeVector_pop', self, as.logical(.copy), PACKAGE='octrar');
  
}

attr(`SizeVector_pop`, 'returnType') = 'integer'
attr(`SizeVector_pop`, "inputTypes") = c('_p_std__vectorT_size_t_t')
class(`SizeVector_pop`) = c("SWIGFunction", class('SizeVector_pop'))

# Start of SizeVector___getslice__

`SizeVector___getslice__` = function(self, i, j)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref"); 
  i = as.integer(i);
  
  if(length(i) > 1) {
    warning("using only the first element of i");
  };
  
  j = as.integer(j);
  
  if(length(j) > 1) {
    warning("using only the first element of j");
  };
  
  ;ans = .Call('R_swig_SizeVector___getslice__', self, i, j, PACKAGE='octrar');
  ans <- if (is.null(ans)) ans
  else new("_p_std__vectorT_size_t_t", ref=ans);
  
  ans
  
}

attr(`SizeVector___getslice__`, 'returnType') = '_p_std__vectorT_size_t_t'
attr(`SizeVector___getslice__`, "inputTypes") = c('_p_std__vectorT_size_t_t', 'integer', 'integer')
class(`SizeVector___getslice__`) = c("SWIGFunction", class('SizeVector___getslice__'))

# Start of SizeVector___setslice__

`SizeVector___setslice__` = function(self, i, j, is)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref"); 
  i = as.integer(i);
  
  if(length(i) > 1) {
    warning("using only the first element of i");
  };
  
  j = as.integer(j);
  
  if(length(j) > 1) {
    warning("using only the first element of j");
  };
  
  if (inherits(is, "ExternalReference")) is = slot(is,"ref"); 
  ;.Call('R_swig_SizeVector___setslice__', self, i, j, is, PACKAGE='octrar');
  
}

attr(`SizeVector___setslice__`, 'returnType') = 'void'
attr(`SizeVector___setslice__`, "inputTypes") = c('_p_std__vectorT_size_t_t', 'integer', 'integer', '_p_std__vectorT_size_t_t')
class(`SizeVector___setslice__`) = c("SWIGFunction", class('SizeVector___setslice__'))

# Start of SizeVector___delslice__

`SizeVector___delslice__` = function(self, i, j)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref"); 
  i = as.integer(i);
  
  if(length(i) > 1) {
    warning("using only the first element of i");
  };
  
  j = as.integer(j);
  
  if(length(j) > 1) {
    warning("using only the first element of j");
  };
  
  ;.Call('R_swig_SizeVector___delslice__', self, i, j, PACKAGE='octrar');
  
}

attr(`SizeVector___delslice__`, 'returnType') = 'void'
attr(`SizeVector___delslice__`, "inputTypes") = c('_p_std__vectorT_size_t_t', 'integer', 'integer')
class(`SizeVector___delslice__`) = c("SWIGFunction", class('SizeVector___delslice__'))

# Start of SizeVector___delitem__

`SizeVector___delitem__` = function(self, i)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref"); 
  i = as.integer(i);
  
  if(length(i) > 1) {
    warning("using only the first element of i");
  };
  
  ;.Call('R_swig_SizeVector___delitem__', self, i, PACKAGE='octrar');
  
}

attr(`SizeVector___delitem__`, 'returnType') = 'void'
attr(`SizeVector___delitem__`, "inputTypes") = c('_p_std__vectorT_size_t_t', 'integer')
class(`SizeVector___delitem__`) = c("SWIGFunction", class('SizeVector___delitem__'))

# Start of SizeVector___getitem__

`SizeVector___getitem__` = function(self, i, .copy = FALSE)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref"); 
  i = as.integer(i);
  
  if(length(i) > 1) {
    warning("using only the first element of i");
  };
  
  ;ans = .Call('R_swig_SizeVector___getitem__', self, i, as.logical(.copy), PACKAGE='octrar');
  ans <- if (is.null(ans)) ans
  else new("_p_size_t", ref=ans);
  
  ans
  
}

attr(`SizeVector___getitem__`, 'returnType') = '_p_size_t'
attr(`SizeVector___getitem__`, "inputTypes") = c('_p_std__vectorT_size_t_t', 'integer')
class(`SizeVector___getitem__`) = c("SWIGFunction", class('SizeVector___getitem__'))

# Start of SizeVector___setitem__

`SizeVector___setitem__` = function(self, i, x)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref"); 
  i = as.integer(i);
  
  if(length(i) > 1) {
    warning("using only the first element of i");
  };
  
  if (inherits(x, "ExternalReference")) x = slot(x,"ref"); 
  ;.Call('R_swig_SizeVector___setitem__', self, i, x, PACKAGE='octrar');
  
}

attr(`SizeVector___setitem__`, 'returnType') = 'void'
attr(`SizeVector___setitem__`, "inputTypes") = c('_p_std__vectorT_size_t_t', 'integer', '_p_size_t')
class(`SizeVector___setitem__`) = c("SWIGFunction", class('SizeVector___setitem__'))

# Start of SizeVector_append

`SizeVector_append` = function(self, x)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref"); 
  if (inherits(x, "ExternalReference")) x = slot(x,"ref"); 
  ;.Call('R_swig_SizeVector_append', self, x, PACKAGE='octrar');
  
}

attr(`SizeVector_append`, 'returnType') = 'void'
attr(`SizeVector_append`, "inputTypes") = c('_p_std__vectorT_size_t_t', '_p_size_t')
class(`SizeVector_append`) = c("SWIGFunction", class('SizeVector_append'))

# Start of new_SizeVector

`SizeVector__SWIG_0` = function()
{
  ;ans = .Call('R_swig_new_SizeVector__SWIG_0', PACKAGE='octrar');
  ans <- if (is.null(ans)) ans
  else new("_p_std__vectorT_size_t_t", ref=ans);
  
  reg.finalizer(ans@ref, delete_SizeVector);
  ans
  
}

attr(`SizeVector__SWIG_0`, 'returnType') = '_p_std__vectorT_size_t_t'
class(`SizeVector__SWIG_0`) = c("SWIGFunction", class('SizeVector__SWIG_0'))

# Start of new_SizeVector

`SizeVector__SWIG_1` = function(other)
{
  if (inherits(other, "ExternalReference")) other = slot(other,"ref"); 
  ;ans = .Call('R_swig_new_SizeVector__SWIG_1', other, PACKAGE='octrar');
  ans <- if (is.null(ans)) ans
  else new("_p_std__vectorT_size_t_t", ref=ans);
  
  reg.finalizer(ans@ref, delete_SizeVector);
  ans
  
}

attr(`SizeVector__SWIG_1`, 'returnType') = '_p_std__vectorT_size_t_t'
attr(`SizeVector__SWIG_1`, "inputTypes") = c('_p_std__vectorT_size_t_t')
class(`SizeVector__SWIG_1`) = c("SWIGFunction", class('SizeVector__SWIG_1'))

# Start of SizeVector_empty

`SizeVector_empty` = function(self, .copy = FALSE)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref"); 
  ;.Call('R_swig_SizeVector_empty', self, as.logical(.copy), PACKAGE='octrar');
  
}

attr(`SizeVector_empty`, 'returnType') = 'logical'
attr(`SizeVector_empty`, "inputTypes") = c('_p_std__vectorT_size_t_t')
class(`SizeVector_empty`) = c("SWIGFunction", class('SizeVector_empty'))

# Start of SizeVector_size

`SizeVector_size` = function(self, .copy = FALSE)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref"); 
  ;.Call('R_swig_SizeVector_size', self, as.logical(.copy), PACKAGE='octrar');
  
}

attr(`SizeVector_size`, 'returnType') = 'integer'
attr(`SizeVector_size`, "inputTypes") = c('_p_std__vectorT_size_t_t')
class(`SizeVector_size`) = c("SWIGFunction", class('SizeVector_size'))

# Start of SizeVector_swap

`SizeVector_swap` = function(self, v)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref"); 
  if (inherits(v, "ExternalReference")) v = slot(v,"ref"); 
  ;.Call('R_swig_SizeVector_swap', self, v, PACKAGE='octrar');
  
}

attr(`SizeVector_swap`, 'returnType') = 'void'
attr(`SizeVector_swap`, "inputTypes") = c('_p_std__vectorT_size_t_t', '_p_std__vectorT_size_t_t')
class(`SizeVector_swap`) = c("SWIGFunction", class('SizeVector_swap'))

# Start of SizeVector_clear

`SizeVector_clear` = function(self)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref"); 
  ;.Call('R_swig_SizeVector_clear', self, PACKAGE='octrar');
  
}

attr(`SizeVector_clear`, 'returnType') = 'void'
attr(`SizeVector_clear`, "inputTypes") = c('_p_std__vectorT_size_t_t')
class(`SizeVector_clear`) = c("SWIGFunction", class('SizeVector_clear'))

# Start of SizeVector_get_allocator

`SizeVector_get_allocator` = function(self, .copy = FALSE)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref"); 
  ;ans = .Call('R_swig_SizeVector_get_allocator', self, as.logical(.copy), PACKAGE='octrar');
  ans <- if (is.null(ans)) ans
  else new("_p_std__allocatorT_size_t_t", ref=ans);
  
  ans
  
}

attr(`SizeVector_get_allocator`, 'returnType') = '_p_std__allocatorT_size_t_t'
attr(`SizeVector_get_allocator`, "inputTypes") = c('_p_std__vectorT_size_t_t')
class(`SizeVector_get_allocator`) = c("SWIGFunction", class('SizeVector_get_allocator'))

# Start of new_SizeVector

`SizeVector__SWIG_2` = function(size)
{
  size = as.integer(size);
  
  if(length(size) > 1) {
    warning("using only the first element of size");
  };
  
  ;ans = .Call('R_swig_new_SizeVector__SWIG_2', size, PACKAGE='octrar');
  ans <- if (is.null(ans)) ans
  else new("_p_std__vectorT_size_t_t", ref=ans);
  
  reg.finalizer(ans@ref, delete_SizeVector);
  ans
  
}

attr(`SizeVector__SWIG_2`, 'returnType') = '_p_std__vectorT_size_t_t'
attr(`SizeVector__SWIG_2`, "inputTypes") = c('integer')
class(`SizeVector__SWIG_2`) = c("SWIGFunction", class('SizeVector__SWIG_2'))

# Start of SizeVector_pop_back

`SizeVector_pop_back` = function(self)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref"); 
  ;.Call('R_swig_SizeVector_pop_back', self, PACKAGE='octrar');
  
}

attr(`SizeVector_pop_back`, 'returnType') = 'void'
attr(`SizeVector_pop_back`, "inputTypes") = c('_p_std__vectorT_size_t_t')
class(`SizeVector_pop_back`) = c("SWIGFunction", class('SizeVector_pop_back'))

# Start of SizeVector_resize

`SizeVector_resize__SWIG_0` = function(self, new_size)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref"); 
  new_size = as.integer(new_size);
  
  if(length(new_size) > 1) {
    warning("using only the first element of new_size");
  };
  
  ;.Call('R_swig_SizeVector_resize__SWIG_0', self, new_size, PACKAGE='octrar');
  
}

attr(`SizeVector_resize__SWIG_0`, 'returnType') = 'void'
attr(`SizeVector_resize__SWIG_0`, "inputTypes") = c('_p_std__vectorT_size_t_t', 'integer')
class(`SizeVector_resize__SWIG_0`) = c("SWIGFunction", class('SizeVector_resize__SWIG_0'))

# Start of new_SizeVector

`SizeVector__SWIG_3` = function(size, value)
{
  size = as.integer(size);
  
  if(length(size) > 1) {
    warning("using only the first element of size");
  };
  
  if (inherits(value, "ExternalReference")) value = slot(value,"ref"); 
  ;ans = .Call('R_swig_new_SizeVector__SWIG_3', size, value, PACKAGE='octrar');
  ans <- if (is.null(ans)) ans
  else new("_p_std__vectorT_size_t_t", ref=ans);
  
  reg.finalizer(ans@ref, delete_SizeVector);
  ans
  
}

attr(`SizeVector__SWIG_3`, 'returnType') = '_p_std__vectorT_size_t_t'
attr(`SizeVector__SWIG_3`, "inputTypes") = c('integer', '_p_size_t')
class(`SizeVector__SWIG_3`) = c("SWIGFunction", class('SizeVector__SWIG_3'))

`SizeVector` <- function(...) {
  argtypes <- mapply(class, list(...));
  argv <- list(...);
  argc <- length(argtypes);
  f <- NULL;
# dispatch functions 4
  if (argc == 0) {
    f <- SizeVector__SWIG_0; 
  } else if (argc == 1) {
    if ( (is.integer(argv[[1]]) || is.numeric(argv[[1]])) && length(argv[[1]]) == 1 ) {
      f <- SizeVector__SWIG_2; 
    }
    else if ( extends(argtypes[1], '_p_std__vectorT_size_t_t') && length(argv[[1]]) == 1 ) {
      f <- SizeVector__SWIG_1; 
    }
  } else if (argc == 2) {
    if (( (is.integer(argv[[1]]) || is.numeric(argv[[1]])) && length(argv[[1]]) == 1 ) && ( extends(argtypes[2], '_p_size_t') && length(argv[[2]]) == 1 )) {
      f <- SizeVector__SWIG_3; 
    }
  };
  if (is.null(f)) {
    stop("cannot find overloaded function for SizeVector with argtypes (",toString(argtypes),")");
  };
  f(...);
}

# Dispatch function
# Start of SizeVector_push_back

`SizeVector_push_back` = function(self, x)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref"); 
  if (inherits(x, "ExternalReference")) x = slot(x,"ref"); 
  ;.Call('R_swig_SizeVector_push_back', self, x, PACKAGE='octrar');
  
}

attr(`SizeVector_push_back`, 'returnType') = 'void'
attr(`SizeVector_push_back`, "inputTypes") = c('_p_std__vectorT_size_t_t', '_p_size_t')
class(`SizeVector_push_back`) = c("SWIGFunction", class('SizeVector_push_back'))

# Start of SizeVector_front

`SizeVector_front` = function(self, .copy = FALSE)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref"); 
  ;ans = .Call('R_swig_SizeVector_front', self, as.logical(.copy), PACKAGE='octrar');
  ans <- if (is.null(ans)) ans
  else new("_p_size_t", ref=ans);
  
  ans
  
}

attr(`SizeVector_front`, 'returnType') = '_p_size_t'
attr(`SizeVector_front`, "inputTypes") = c('_p_std__vectorT_size_t_t')
class(`SizeVector_front`) = c("SWIGFunction", class('SizeVector_front'))

# Start of SizeVector_back

`SizeVector_back` = function(self, .copy = FALSE)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref"); 
  ;ans = .Call('R_swig_SizeVector_back', self, as.logical(.copy), PACKAGE='octrar');
  ans <- if (is.null(ans)) ans
  else new("_p_size_t", ref=ans);
  
  ans
  
}

attr(`SizeVector_back`, 'returnType') = '_p_size_t'
attr(`SizeVector_back`, "inputTypes") = c('_p_std__vectorT_size_t_t')
class(`SizeVector_back`) = c("SWIGFunction", class('SizeVector_back'))

# Start of SizeVector_assign

`SizeVector_assign` = function(self, n, x)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref"); 
  n = as.integer(n);
  
  if(length(n) > 1) {
    warning("using only the first element of n");
  };
  
  if (inherits(x, "ExternalReference")) x = slot(x,"ref"); 
  ;.Call('R_swig_SizeVector_assign', self, n, x, PACKAGE='octrar');
  
}

attr(`SizeVector_assign`, 'returnType') = 'void'
attr(`SizeVector_assign`, "inputTypes") = c('_p_std__vectorT_size_t_t', 'integer', '_p_size_t')
class(`SizeVector_assign`) = c("SWIGFunction", class('SizeVector_assign'))

# Start of SizeVector_resize

`SizeVector_resize__SWIG_1` = function(self, new_size, x)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref"); 
  new_size = as.integer(new_size);
  
  if(length(new_size) > 1) {
    warning("using only the first element of new_size");
  };
  
  if (inherits(x, "ExternalReference")) x = slot(x,"ref"); 
  ;.Call('R_swig_SizeVector_resize__SWIG_1', self, new_size, x, PACKAGE='octrar');
  
}

attr(`SizeVector_resize__SWIG_1`, 'returnType') = 'void'
attr(`SizeVector_resize__SWIG_1`, "inputTypes") = c('_p_std__vectorT_size_t_t', 'integer', '_p_size_t')
class(`SizeVector_resize__SWIG_1`) = c("SWIGFunction", class('SizeVector_resize__SWIG_1'))

`SizeVector_resize` <- function(...) {
  argtypes <- mapply(class, list(...));
  argv <- list(...);
  argc <- length(argtypes);
  f <- NULL;
# dispatch functions 2
  if (argc == 2) {
    if (( extends(argtypes[1], '_p_std__vectorT_size_t_t') || is.null(argv[[1]]) ) && ( (is.integer(argv[[2]]) || is.numeric(argv[[2]])) && length(argv[[2]]) == 1 )) {
      f <- SizeVector_resize__SWIG_0; 
    }
  } else if (argc == 3) {
    if (( extends(argtypes[1], '_p_std__vectorT_size_t_t') || is.null(argv[[1]]) ) && ( (is.integer(argv[[2]]) || is.numeric(argv[[2]])) && length(argv[[2]]) == 1 ) && ( extends(argtypes[3], '_p_size_t') && length(argv[[3]]) == 1 )) {
      f <- SizeVector_resize__SWIG_1; 
    }
  };
  if (is.null(f)) {
    stop("cannot find overloaded function for SizeVector_resize with argtypes (",toString(argtypes),")");
  };
  f(...);
}

# Dispatch function
# Start of SizeVector_reserve

`SizeVector_reserve` = function(self, n)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref"); 
  n = as.integer(n);
  
  if(length(n) > 1) {
    warning("using only the first element of n");
  };
  
  ;.Call('R_swig_SizeVector_reserve', self, n, PACKAGE='octrar');
  
}

attr(`SizeVector_reserve`, 'returnType') = 'void'
attr(`SizeVector_reserve`, "inputTypes") = c('_p_std__vectorT_size_t_t', 'integer')
class(`SizeVector_reserve`) = c("SWIGFunction", class('SizeVector_reserve'))

# Start of SizeVector_capacity

`SizeVector_capacity` = function(self, .copy = FALSE)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref"); 
  ;.Call('R_swig_SizeVector_capacity', self, as.logical(.copy), PACKAGE='octrar');
  
}

attr(`SizeVector_capacity`, 'returnType') = 'integer'
attr(`SizeVector_capacity`, "inputTypes") = c('_p_std__vectorT_size_t_t')
class(`SizeVector_capacity`) = c("SWIGFunction", class('SizeVector_capacity'))

# Start of delete_SizeVector

`delete_SizeVector` = function(self)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref"); 
  ;.Call('R_swig_delete_SizeVector', self, PACKAGE='octrar');
  
}

attr(`delete_SizeVector`, 'returnType') = 'void'
attr(`delete_SizeVector`, "inputTypes") = c('_p_std__vectorT_size_t_t')
class(`delete_SizeVector`) = c("SWIGFunction", class('delete_SizeVector'))

# Start of accessor method for std::vector< size_t >
setMethod('$', '_p_std__vectorT_size_t_t', function(x, name)

{
  accessorFuns = list('__nonzero__' = SizeVector___nonzero__, '__len__' = SizeVector___len__, 'pop' = SizeVector_pop, '__getslice__' = SizeVector___getslice__, '__setslice__' = SizeVector___setslice__, '__delslice__' = SizeVector___delslice__, '__delitem__' = SizeVector___delitem__, '__getitem__' = SizeVector___getitem__, '__setitem__' = SizeVector___setitem__, 'append' = SizeVector_append, 'empty' = SizeVector_empty, 'size' = SizeVector_size, 'swap' = SizeVector_swap, 'clear' = SizeVector_clear, 'get_allocator' = SizeVector_get_allocator, 'pop_back' = SizeVector_pop_back, 'resize' = SizeVector_resize, 'push_back' = SizeVector_push_back, 'front' = SizeVector_front, 'back' = SizeVector_back, 'assign' = SizeVector_assign, 'reserve' = SizeVector_reserve, 'capacity' = SizeVector_capacity);
  ;        idx = pmatch(name, names(accessorFuns));
  if(is.na(idx)) 
  return(callNextMethod(x, name));
  f = accessorFuns[[idx]];
  function(...){
    f(x, ...)
  };
}


);
# end of accessor method for std::vector< size_t >
setMethod('delete', '_p_std__vectorT_size_t_t', function(obj) {delete_std__vectorT_size_t_t(obj)})
# Start of hello

`hello` = function()
{
  ;.Call('R_swig_hello', PACKAGE='octrar');
  
}

attr(`hello`, 'returnType') = 'void'
class(`hello`) = c("SWIGFunction", class('hello'))

# Start of delete_Callback

`delete_Callback` = function(self)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref"); 
  ;.Call('R_swig_delete_Callback', self, PACKAGE='octrar');
  
}

attr(`delete_Callback`, 'returnType') = 'void'
attr(`delete_Callback`, "inputTypes") = c('_p_octra__Callback')
class(`delete_Callback`) = c("SWIGFunction", class('delete_Callback'))

# Start of Callback_call

`Callback_call` = function(self, x, .copy = FALSE)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref"); 
  
  ;.Call('R_swig_Callback_call', self, x, as.logical(.copy), PACKAGE='octrar');
  
}

attr(`Callback_call`, 'returnType') = 'numeric'
attr(`Callback_call`, "inputTypes") = c('_p_octra__Callback', 'numeric')
class(`Callback_call`) = c("SWIGFunction", class('Callback_call'))

# Start of new_Callback

`Callback` = function()
{
  ;ans = .Call('R_swig_new_Callback', PACKAGE='octrar');
  ans <- if (is.null(ans)) ans
  else new("_p_octra__Callback", ref=ans);
  
  reg.finalizer(ans@ref, delete_Callback);
  ans
  
}

attr(`Callback`, 'returnType') = '_p_octra__Callback'
class(`Callback`) = c("SWIGFunction", class('Callback'))

# Start of accessor method for octra::Callback
setMethod('$', '_p_octra__Callback', function(x, name)

{
  accessorFuns = list('call' = Callback_call);
  ;        idx = pmatch(name, names(accessorFuns));
  if(is.na(idx)) 
  return(callNextMethod(x, name));
  f = accessorFuns[[idx]];
  function(...){
    f(x, ...)
  };
}


);
# end of accessor method for octra::Callback
setMethod('delete', '_p_octra__Callback', function(obj) {delete_octra__Callback(obj)})
# Start of call_with_callback

`call_with_callback` = function(x, cb, .copy = FALSE)
{
  if (inherits(cb, "ExternalReference")) cb = slot(cb,"ref"); 
  ;.Call('R_swig_call_with_callback', x, cb, as.logical(.copy), PACKAGE='octrar');
  
}

attr(`call_with_callback`, 'returnType') = 'numeric'
attr(`call_with_callback`, "inputTypes") = c('numeric', '_p_octra__Callback')
class(`call_with_callback`) = c("SWIGFunction", class('call_with_callback'))

# Start of map_dvector_with_callback

`map_dvector_with_callback` = function(values, cb, .copy = FALSE)
{
  values = as.numeric(values);
  if (inherits(cb, "ExternalReference")) cb = slot(cb,"ref"); 
  ;.Call('R_swig_map_dvector_with_callback', values, cb, as.logical(.copy), PACKAGE='octrar');
  
}

attr(`map_dvector_with_callback`, 'returnType') = 'numeric'
attr(`map_dvector_with_callback`, "inputTypes") = c('_p_std__vectorT_double_t', '_p_octra__Callback')
class(`map_dvector_with_callback`) = c("SWIGFunction", class('map_dvector_with_callback'))

# Start of make_dvector

`make_dvector` = function(a, b, c, .copy = FALSE)
{
  ;.Call('R_swig_make_dvector', a, b, c, as.logical(.copy), PACKAGE='octrar');
  
}

attr(`make_dvector`, 'returnType') = 'numeric'
attr(`make_dvector`, "inputTypes") = c('numeric', 'numeric', 'numeric')
class(`make_dvector`) = c("SWIGFunction", class('make_dvector'))

# Start of sum_dvector

`sum_dvector` = function(values, .copy = FALSE)
{
  values = as.numeric(values);
  ;.Call('R_swig_sum_dvector', values, as.logical(.copy), PACKAGE='octrar');
  
}

attr(`sum_dvector`, 'returnType') = 'numeric'
attr(`sum_dvector`, "inputTypes") = c('_p_std__vectorT_double_t')
class(`sum_dvector`) = c("SWIGFunction", class('sum_dvector'))

# Start of make_dpair

`make_dpair` = function(a, b, .copy = FALSE)
{
  ;ans = .Call('R_swig_make_dpair', a, b, as.logical(.copy), PACKAGE='octrar');
  ans <- if (is.null(ans)) ans
  else new("_p_std__pairT_double_double_t", ref=ans);
  
  ans
  
}

attr(`make_dpair`, 'returnType') = '_p_std__pairT_double_double_t'
attr(`make_dpair`, "inputTypes") = c('numeric', 'numeric')
class(`make_dpair`) = c("SWIGFunction", class('make_dpair'))

# Start of sum_dpair

`sum_dpair` = function(values, .copy = FALSE)
{
  if (inherits(values, "ExternalReference")) values = slot(values,"ref"); 
  ;.Call('R_swig_sum_dpair', values, as.logical(.copy), PACKAGE='octrar');
  
}

attr(`sum_dpair`, 'returnType') = 'numeric'
attr(`sum_dpair`, "inputTypes") = c('_p_std__pairT_double_double_t')
class(`sum_dpair`) = c("SWIGFunction", class('sum_dpair'))



