# This file was automatically generated by SWIG JSE (https://www.swig.org).
# Version 5.0.6
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

package Octra;
use base qw(Exporter);
use base qw(DynaLoader);
package Octrac;
bootstrap Octra;
package Octra;
@EXPORT = qw();

# ---------- BASE METHODS -------------

package Octra;

sub TIEHASH {
    my ($classname,$obj) = @_;
    return bless $obj, $classname;
}

sub CLEAR { }

sub FIRSTKEY { }

sub NEXTKEY { }

sub FETCH {
    my ($self,$field) = @_;
    my $member_func = "swig_${field}_get";
    $self->$member_func();
}

sub STORE {
    my ($self,$field,$newval) = @_;
    my $member_func = "swig_${field}_set";
    $self->$member_func($newval);
}

sub this {
    my $ptr = shift;
    return tied(%$ptr);
}


# ------- FUNCTION WRAPPERS --------

package Octra;

*splitmix64_next = *Octrac::splitmix64_next;
*splitmix64_runif = *Octrac::splitmix64_runif;
*fill_runif = *Octrac::fill_runif;
*splitmix64_runif_seeded = *Octrac::splitmix64_runif_seeded;
*hello = *Octrac::hello;
*call_with_callback = *Octrac::call_with_callback;
*map_dvector_with_callback = *Octrac::map_dvector_with_callback;
*make_dvector = *Octrac::make_dvector;
*sum_dvector = *Octrac::sum_dvector;
*make_dpair = *Octrac::make_dpair;
*sum_dpair = *Octrac::sum_dpair;

############# Class : Octra::IPair ##############

package Octra::IPair;
use vars qw(@ISA %OWNER %ITERATORS %BLESSEDMEMBERS);
@ISA = qw( Octra );
%OWNER = ();
%ITERATORS = ();
sub new {
    my $pkg = shift;
    my $self = Octrac::new_IPair(@_);
    bless $self, $pkg if defined($self);
}

*swig_first_get = *Octrac::IPair_first_get;
*swig_first_set = *Octrac::IPair_first_set;
*swig_second_get = *Octrac::IPair_second_get;
*swig_second_set = *Octrac::IPair_second_set;
sub DESTROY {
    return unless $_[0]->isa('HASH');
    my $self = tied(%{$_[0]});
    return unless defined $self;
    delete $ITERATORS{$self};
    if (exists $OWNER{$self}) {
        Octrac::delete_IPair($self);
        delete $OWNER{$self};
    }
}

sub DISOWN {
    my $self = shift;
    my $ptr = tied(%$self);
    delete $OWNER{$ptr};
}

sub ACQUIRE {
    my $self = shift;
    my $ptr = tied(%$self);
    $OWNER{$ptr} = 1;
}


############# Class : Octra::DPair ##############

package Octra::DPair;
use vars qw(@ISA %OWNER %ITERATORS %BLESSEDMEMBERS);
@ISA = qw( Octra );
%OWNER = ();
%ITERATORS = ();
sub new {
    my $pkg = shift;
    my $self = Octrac::new_DPair(@_);
    bless $self, $pkg if defined($self);
}

*swig_first_get = *Octrac::DPair_first_get;
*swig_first_set = *Octrac::DPair_first_set;
*swig_second_get = *Octrac::DPair_second_get;
*swig_second_set = *Octrac::DPair_second_set;
sub DESTROY {
    return unless $_[0]->isa('HASH');
    my $self = tied(%{$_[0]});
    return unless defined $self;
    delete $ITERATORS{$self};
    if (exists $OWNER{$self}) {
        Octrac::delete_DPair($self);
        delete $OWNER{$self};
    }
}

sub DISOWN {
    my $self = shift;
    my $ptr = tied(%$self);
    delete $OWNER{$ptr};
}

sub ACQUIRE {
    my $self = shift;
    my $ptr = tied(%$self);
    $OWNER{$ptr} = 1;
}


############# Class : Octra::SPair ##############

package Octra::SPair;
use vars qw(@ISA %OWNER %ITERATORS %BLESSEDMEMBERS);
@ISA = qw( Octra );
%OWNER = ();
%ITERATORS = ();
sub new {
    my $pkg = shift;
    my $self = Octrac::new_SPair(@_);
    bless $self, $pkg if defined($self);
}

*swig_first_get = *Octrac::SPair_first_get;
*swig_first_set = *Octrac::SPair_first_set;
*swig_second_get = *Octrac::SPair_second_get;
*swig_second_set = *Octrac::SPair_second_set;
sub DESTROY {
    return unless $_[0]->isa('HASH');
    my $self = tied(%{$_[0]});
    return unless defined $self;
    delete $ITERATORS{$self};
    if (exists $OWNER{$self}) {
        Octrac::delete_SPair($self);
        delete $OWNER{$self};
    }
}

sub DISOWN {
    my $self = shift;
    my $ptr = tied(%$self);
    delete $OWNER{$ptr};
}

sub ACQUIRE {
    my $self = shift;
    my $ptr = tied(%$self);
    $OWNER{$ptr} = 1;
}


############# Class : Octra::IVector ##############

package Octra::IVector;
use vars qw(@ISA %OWNER %ITERATORS %BLESSEDMEMBERS);
@ISA = qw( Octra );
%OWNER = ();
%ITERATORS = ();
sub new {
    my $pkg = shift;
    my $self = Octrac::new_IVector(@_);
    bless $self, $pkg if defined($self);
}

*size = *Octrac::IVector_size;
*empty = *Octrac::IVector_empty;
*clear = *Octrac::IVector_clear;
*push = *Octrac::IVector_push;
*pop = *Octrac::IVector_pop;
*get = *Octrac::IVector_get;
*set = *Octrac::IVector_set;
sub DESTROY {
    return unless $_[0]->isa('HASH');
    my $self = tied(%{$_[0]});
    return unless defined $self;
    delete $ITERATORS{$self};
    if (exists $OWNER{$self}) {
        Octrac::delete_IVector($self);
        delete $OWNER{$self};
    }
}

sub DISOWN {
    my $self = shift;
    my $ptr = tied(%$self);
    delete $OWNER{$ptr};
}

sub ACQUIRE {
    my $self = shift;
    my $ptr = tied(%$self);
    $OWNER{$ptr} = 1;
}


############# Class : Octra::DVector ##############

package Octra::DVector;
use vars qw(@ISA %OWNER %ITERATORS %BLESSEDMEMBERS);
@ISA = qw( Octra );
%OWNER = ();
%ITERATORS = ();
sub new {
    my $pkg = shift;
    my $self = Octrac::new_DVector(@_);
    bless $self, $pkg if defined($self);
}

*size = *Octrac::DVector_size;
*empty = *Octrac::DVector_empty;
*clear = *Octrac::DVector_clear;
*push = *Octrac::DVector_push;
*pop = *Octrac::DVector_pop;
*get = *Octrac::DVector_get;
*set = *Octrac::DVector_set;
sub DESTROY {
    return unless $_[0]->isa('HASH');
    my $self = tied(%{$_[0]});
    return unless defined $self;
    delete $ITERATORS{$self};
    if (exists $OWNER{$self}) {
        Octrac::delete_DVector($self);
        delete $OWNER{$self};
    }
}

sub DISOWN {
    my $self = shift;
    my $ptr = tied(%$self);
    delete $OWNER{$ptr};
}

sub ACQUIRE {
    my $self = shift;
    my $ptr = tied(%$self);
    $OWNER{$ptr} = 1;
}


############# Class : Octra::SizeVector ##############

package Octra::SizeVector;
use vars qw(@ISA %OWNER %ITERATORS %BLESSEDMEMBERS);
@ISA = qw( Octra );
%OWNER = ();
%ITERATORS = ();
sub new {
    my $pkg = shift;
    my $self = Octrac::new_SizeVector(@_);
    bless $self, $pkg if defined($self);
}

*size = *Octrac::SizeVector_size;
*empty = *Octrac::SizeVector_empty;
*clear = *Octrac::SizeVector_clear;
*push = *Octrac::SizeVector_push;
*pop = *Octrac::SizeVector_pop;
*get = *Octrac::SizeVector_get;
*set = *Octrac::SizeVector_set;
sub DESTROY {
    return unless $_[0]->isa('HASH');
    my $self = tied(%{$_[0]});
    return unless defined $self;
    delete $ITERATORS{$self};
    if (exists $OWNER{$self}) {
        Octrac::delete_SizeVector($self);
        delete $OWNER{$self};
    }
}

sub DISOWN {
    my $self = shift;
    my $ptr = tied(%$self);
    delete $OWNER{$ptr};
}

sub ACQUIRE {
    my $self = shift;
    my $ptr = tied(%$self);
    $OWNER{$ptr} = 1;
}


############# Class : Octra::SVector ##############

package Octra::SVector;
use vars qw(@ISA %OWNER %ITERATORS %BLESSEDMEMBERS);
@ISA = qw( Octra );
%OWNER = ();
%ITERATORS = ();
sub new {
    my $pkg = shift;
    my $self = Octrac::new_SVector(@_);
    bless $self, $pkg if defined($self);
}

*size = *Octrac::SVector_size;
*empty = *Octrac::SVector_empty;
*clear = *Octrac::SVector_clear;
*push = *Octrac::SVector_push;
*pop = *Octrac::SVector_pop;
*get = *Octrac::SVector_get;
*set = *Octrac::SVector_set;
sub DESTROY {
    return unless $_[0]->isa('HASH');
    my $self = tied(%{$_[0]});
    return unless defined $self;
    delete $ITERATORS{$self};
    if (exists $OWNER{$self}) {
        Octrac::delete_SVector($self);
        delete $OWNER{$self};
    }
}

sub DISOWN {
    my $self = shift;
    my $ptr = tied(%$self);
    delete $OWNER{$ptr};
}

sub ACQUIRE {
    my $self = shift;
    my $ptr = tied(%$self);
    $OWNER{$ptr} = 1;
}


############# Class : Octra::Callback ##############

package Octra::Callback;
use vars qw(@ISA %OWNER %ITERATORS %BLESSEDMEMBERS);
@ISA = qw( Octra );
%OWNER = ();
%ITERATORS = ();
sub DESTROY {
    return unless $_[0]->isa('HASH');
    my $self = tied(%{$_[0]});
    return unless defined $self;
    delete $ITERATORS{$self};
    if (exists $OWNER{$self}) {
        Octrac::delete_Callback($self);
        delete $OWNER{$self};
    }
}

*call = *Octrac::Callback_call;
sub new {
    my $pkg = $_[0];
    my $self = Octrac::new_Callback(@_);
    bless $self, $pkg if defined($self);
}

sub DISOWN {
    my $self = shift;
    Octrac::disown_Callback($self);
    my $ptr = tied(%$self);
    delete $OWNER{$ptr};
}

sub ACQUIRE {
    my $self = shift;
    my $ptr = tied(%$self);
    $OWNER{$ptr} = 1;
}

sub FETCH {
    my ($self,$field) = @_;
    my $member_func = "swig_${field}_get";
    if (not $self->can($member_func)) {
        my $h = Octrac::swig_get_attr_Callback($self);
        return $h->{$field} if $h;
    }
    return $self->$member_func;
}

sub STORE {
    my ($self,$field,$newval) = @_;
    my $member_func = "swig_${field}_set";
    if (not $self->can($member_func)) {
        my $h = Octrac::swig_get_attr_Callback($self);
        return $h->{$field} = $newval if $h;
    }
    return $self->$member_func($newval);
}

# ------- VARIABLE STUBS --------

package Octra;

*STD_STRINGS_BODY_SECTION = *Octrac::STD_STRINGS_BODY_SECTION;
1;
