/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

module octra_im;
static import core.stdc.config;

static import std.conv;

static import std.conv;
static import std.string;


private {
  version(linux) {
    version = Nix;
  } else version(darwin) {
    version = Nix;
  } else version(OSX) {
    version = Nix;
  } else version(FreeBSD) {
    version = Nix;
    version = freebsd;
  } else version(freebsd) {
    version = Nix;
  } else version(Unix) {
    version = Nix;
  } else version(Posix) {
    version = Nix;
  }

  version(Tango) {
    static import tango.stdc.string;
    static import tango.stdc.stringz;

    version (PhobosCompatibility) {
    } else {
      alias char[] string;
      alias wchar[] wstring;
      alias dchar[] dstring;
    }
  } else {
    version(D_Version2) {
      static import std.conv;
    } else {
      static import std.c.string;
    }
    static import std.string;
  }

  version(D_Version2) {
    mixin("alias const(char)* CCPTR;");
  } else {
    alias char* CCPTR;
  }

  CCPTR swigToCString(string str) {
    version(Tango) {
      return tango.stdc.stringz.toStringz(str);
    } else {
      return std.string.toStringz(str);
    }
  }

  string swigToDString(CCPTR cstr) {
    version(Tango) {
      return tango.stdc.stringz.fromStringz(cstr);
    } else {
      version(D_Version2) {
        mixin("return std.conv.to!string(cstr);");
      } else {
        return std.c.string.toString(cstr);
      }
    }
  }
}

class SwigSwigSharedLibLoadException : Exception {
  this(in string[] libNames, in string[] reasons) {
    string msg = "Failed to load one or more shared libraries:";
    foreach(i, n; libNames) {
      msg ~= "\n\t" ~ n ~ " - ";
      if(i < reasons.length)
        msg ~= reasons[i];
      else
        msg ~= "Unknown";
    }
    super(msg);
  }
}

class SwigSymbolLoadException : Exception {
  this(string SwigSharedLibName, string symbolName) {
    super("Failed to load symbol " ~ symbolName ~ " from shared library " ~ SwigSharedLibName);
    _symbolName = symbolName;
  }

  string symbolName() {
    return _symbolName;
  }

private:
  string _symbolName;
}

private {
  version(Nix) {
    version(freebsd) {
      // the dl* functions are in libc on FreeBSD
    }
    else {
      pragma(lib, "dl");
    }

    version(Tango) {
      import tango.sys.Common;
    } else version(linux) {
      import core.sys.posix.dlfcn;
    } else {
      extern(C) {
        const RTLD_NOW = 2;

        void *dlopen(CCPTR file, int mode);
        int dlclose(void* handle);
        void *dlsym(void* handle, CCPTR name);
        CCPTR dlerror();
      }
    }

    alias void* SwigSharedLibHandle;

    SwigSharedLibHandle swigLoadSharedLib(string libName) {
      return dlopen(swigToCString(libName), RTLD_NOW);
    }

    void swigUnloadSharedLib(SwigSharedLibHandle hlib) {
      dlclose(hlib);
    }

    void* swigGetSymbol(SwigSharedLibHandle hlib, string symbolName) {
      return dlsym(hlib, swigToCString(symbolName));
    }

    string swigGetErrorStr() {
      CCPTR err = dlerror();
      if (err is null) {
        return "Unknown Error";
      }
      return swigToDString(err);
    }
  } else version(Windows) {
    alias ushort WORD;
    alias uint DWORD;
    alias CCPTR LPCSTR;
    alias void* HMODULE;
    alias void* HLOCAL;
    alias int function() FARPROC;
    struct VA_LIST {}

    extern (Windows) {
      HMODULE LoadLibraryA(LPCSTR);
      FARPROC GetProcAddress(HMODULE, LPCSTR);
      void FreeLibrary(HMODULE);
      DWORD GetLastError();
      DWORD FormatMessageA(DWORD, in void*, DWORD, DWORD, LPCSTR, DWORD, VA_LIST*);
      HLOCAL LocalFree(HLOCAL);
    }

    DWORD MAKELANGID(WORD p, WORD s) {
      return (((cast(WORD)s) << 10) | cast(WORD)p);
    }

    enum {
      LANG_NEUTRAL                    = 0,
      SUBLANG_DEFAULT                 = 1,
      FORMAT_MESSAGE_ALLOCATE_BUFFER  = 256,
      FORMAT_MESSAGE_IGNORE_INSERTS   = 512,
      FORMAT_MESSAGE_FROM_SYSTEM      = 4096
    }

    alias HMODULE SwigSharedLibHandle;

    SwigSharedLibHandle swigLoadSharedLib(string libName) {
      return LoadLibraryA(swigToCString(libName));
    }

    void swigUnloadSharedLib(SwigSharedLibHandle hlib) {
      FreeLibrary(hlib);
    }

    void* swigGetSymbol(SwigSharedLibHandle hlib, string symbolName) {
      return GetProcAddress(hlib, swigToCString(symbolName));
    }

    string swigGetErrorStr() {
      DWORD errcode = GetLastError();

      LPCSTR msgBuf;
      DWORD i = FormatMessageA(
        FORMAT_MESSAGE_ALLOCATE_BUFFER |
        FORMAT_MESSAGE_FROM_SYSTEM |
        FORMAT_MESSAGE_IGNORE_INSERTS,
        null,
        errcode,
        MAKELANGID(LANG_NEUTRAL, SUBLANG_DEFAULT),
        cast(LPCSTR)&msgBuf,
        0,
        null);

      string text = swigToDString(msgBuf);
      LocalFree(cast(HLOCAL)msgBuf);

      if (i >= 2) {
        i -= 2;
      }
      return text[0 .. i];
    }
  } else {
    static assert(0, "Operating system not supported by the wrapper loading code.");
  }

  final class SwigSharedLib {
    void load(string[] names) {
      if (_hlib !is null) return;

      string[] failedLibs;
      string[] reasons;

      foreach(n; names) {
        _hlib = swigLoadSharedLib(n);
        if (_hlib is null) {
          failedLibs ~= n;
          reasons ~= swigGetErrorStr();
          continue;
        }
        _name = n;
        break;
      }

      if (_hlib is null) {
        throw new SwigSwigSharedLibLoadException(failedLibs, reasons);
      }
    }

    void* loadSymbol(string symbolName, bool doThrow = true) {
      void* sym = swigGetSymbol(_hlib, symbolName);
      if(doThrow && (sym is null)) {
        throw new SwigSymbolLoadException(_name, symbolName);
      }
      return sym;
    }

    void unload() {
      if(_hlib !is null) {
        swigUnloadSharedLib(_hlib);
        _hlib = null;
      }
    }

  private:
    string _name;
    SwigSharedLibHandle _hlib;
  }
}

static this() {
  string[] possibleFileNames;
  version (Posix) {
    version (OSX) {
      possibleFileNames ~= ["liboctra_wrap.dylib", "liboctra_wrap.bundle"];
    }
    possibleFileNames ~= ["liboctra_wrap.so"];
  } else version (Windows) {
    possibleFileNames ~= ["octra_wrap.dll", "liboctra_wrap.so"];
  } else {
    static assert(false, "Operating system not supported by the wrapper loading code.");
  }

  auto library = new SwigSharedLib;
  library.load(possibleFileNames);

  string bindCode(string functionPointer, string symbol) {
    return functionPointer ~ " = cast(typeof(" ~ functionPointer ~
      "))library.loadSymbol(`" ~ symbol ~ "`);";
  }

  mixin(bindCode("swigRegisterExceptionCallbacksoctra", "SWIGRegisterExceptionCallbacks_octra"));
  mixin(bindCode("swigRegisterStringCallbackoctra", "SWIGRegisterStringCallback_octra"));
  
  mixin(bindCode("new_DPair__SWIG_0", "D_new_DPair__SWIG_0"));
  mixin(bindCode("new_DPair__SWIG_1", "D_new_DPair__SWIG_1"));
  mixin(bindCode("new_DPair__SWIG_2", "D_new_DPair__SWIG_2"));
  mixin(bindCode("DPair_first_set", "D_DPair_first_set"));
  mixin(bindCode("DPair_first_get", "D_DPair_first_get"));
  mixin(bindCode("DPair_second_set", "D_DPair_second_set"));
  mixin(bindCode("DPair_second_get", "D_DPair_second_get"));
  mixin(bindCode("delete_DPair", "D_delete_DPair"));
  mixin(bindCode("DVector_empty", "D_DVector_empty"));
  mixin(bindCode("DVector_clear", "D_DVector_clear"));
  mixin(bindCode("DVector_push_back", "D_DVector_push_back"));
  mixin(bindCode("DVector_pop_back", "D_DVector_pop_back"));
  mixin(bindCode("DVector_size", "D_DVector_size"));
  mixin(bindCode("DVector_capacity", "D_DVector_capacity"));
  mixin(bindCode("DVector_reserve", "D_DVector_reserve"));
  mixin(bindCode("new_DVector__SWIG_0", "D_new_DVector__SWIG_0"));
  mixin(bindCode("new_DVector__SWIG_1", "D_new_DVector__SWIG_1"));
  mixin(bindCode("new_DVector__SWIG_2", "D_new_DVector__SWIG_2"));
  mixin(bindCode("DVector_remove__SWIG_0", "D_DVector_remove__SWIG_0"));
  mixin(bindCode("DVector_remove__SWIG_1", "D_DVector_remove__SWIG_1"));
  mixin(bindCode("DVector_removeBack", "D_DVector_removeBack"));
  mixin(bindCode("DVector_linearRemove", "D_DVector_linearRemove"));
  mixin(bindCode("DVector_insertAt", "D_DVector_insertAt"));
  mixin(bindCode("DVector_getElement", "D_DVector_getElement"));
  mixin(bindCode("DVector_setElement", "D_DVector_setElement"));
  mixin(bindCode("delete_DVector", "D_delete_DVector"));
  mixin(bindCode("hello", "D_hello"));
  mixin(bindCode("make_dvector", "D_make_dvector"));
  mixin(bindCode("sum_dvector", "D_sum_dvector"));
  mixin(bindCode("make_dpair", "D_make_dpair"));
  mixin(bindCode("sum_dpair", "D_sum_dpair"));
}

extern(C) void function(
  SwigExceptionCallback exceptionCallback,
  SwigExceptionCallback illegalArgumentCallback,
  SwigExceptionCallback illegalElementCallback,
  SwigExceptionCallback ioCallback,
  SwigExceptionCallback noSuchElementCallback,
  SwigExceptionCallback nullReferenceCallback) swigRegisterExceptionCallbacksoctra;

extern(C) void function(SwigStringCallback callback) swigRegisterStringCallbackoctra;


mixin template SwigOperatorDefinitions() {
  public override bool opEquals(Object o) {
    if (auto rhs = cast(typeof(this))o) {
      if (swigCPtr == rhs.swigCPtr) return true;
      static if (is(typeof(swigOpEquals(rhs)))) {
        return swigOpEquals(rhs);
      } else {
        return false; 
      }
    }
    return super.opEquals(o);
  }

  
  public override int opCmp(Object o) {
    static if (__traits(compiles, swigOpLt(typeof(this).init) &&
        swigOpEquals(typeof(this).init))) {
      if (auto rhs = cast(typeof(this))o) {
        if (swigOpLt(rhs)) {
          return -1;
        } else if (swigOpEquals(rhs)) {
          return 0;
        } else {
          return 1;
        }
      }
    }
    return super.opCmp(o);
  }

  private template swigOpBinary(string operator, string name) {
    enum swigOpBinary = `public void opOpAssign(string op, T)(T rhs) if (op == "` ~ operator ~
      `" && __traits(compiles, swigOp` ~ name ~ `Assign(rhs))) { swigOp` ~ name ~ `Assign(rhs);}` ~
      `public auto opBinary(string op, T)(T rhs) if (op == "` ~ operator ~
      `" && __traits(compiles, swigOp` ~ name ~ `(rhs))) { return swigOp` ~ name ~ `(rhs);}`;
  }
  mixin(swigOpBinary!("+", "Add"));
  mixin(swigOpBinary!("-", "Sub"));
  mixin(swigOpBinary!("*", "Mul"));
  mixin(swigOpBinary!("/", "Div"));
  mixin(swigOpBinary!("%", "Mod"));
  mixin(swigOpBinary!("&", "And"));
  mixin(swigOpBinary!("|", "Or"));
  mixin(swigOpBinary!("^", "Xor"));
  mixin(swigOpBinary!("<<", "Shl"));
  mixin(swigOpBinary!(">>", "Shr"));
  
  private template swigOpUnary(string operator, string name) {
    enum swigOpUnary = `public auto opUnary(string op)() if (op == "` ~ operator ~
      `" && __traits(compiles, swigOp` ~ name ~ `())) { return swigOp` ~ name ~ `();}`;   
  }
  mixin(swigOpUnary!("+", "Pos"));
  mixin(swigOpUnary!("-", "Neg"));
  mixin(swigOpUnary!("~", "Com"));
  mixin(swigOpUnary!("++", "Inc"));
  mixin(swigOpUnary!("--", "Dec"));


}


private class SwigExceptionHelper {
  static this() {
	// The D1/Tango version maps C++ exceptions to multiple exception types.
    swigRegisterExceptionCallbacksoctra(
      &setException,
      &setException,
      &setException,
      &setException,
      &setException,
      &setException
    );
  }

  static void setException(const char* message) {
    auto exception = new object.Exception(std.conv.to!string(message));
    SwigPendingException.set(exception);
  }
}

public class SwigPendingException {
public:
  static this() {
    m_sPendingException = null;
  }

  static bool isPending() {
    return m_sPendingException !is null;
  }

  static void set(object.Exception e) {
    if (m_sPendingException !is null) {
      e.next = m_sPendingException;
      throw new object.Exception("FATAL: An earlier pending exception from C/C++ code " ~
        "was missed and thus not thrown (" ~ m_sPendingException.classinfo.name ~
        ": " ~ m_sPendingException.msg ~ ")!", e);
    }

    m_sPendingException = e;
  }

  static object.Exception retrieve() {
    auto e = m_sPendingException;
    m_sPendingException = null;
    return e;
  }

private:
  // The reference to the pending exception (if any) is stored thread-local.
  static object.Exception m_sPendingException;
}
alias void function(const char* message) SwigExceptionCallback;


private class SwigStringHelper {
  static this() {
    swigRegisterStringCallbackoctra(&createString);
  }

  static const(char)* createString(const(char*) cString) {
    // We are effectively dup'ing the string here.
    // TODO: Is this correct for D2/Phobos?
    return std.string.toStringz(std.conv.to!string(cString));
  }
}
alias const(char)* function(const(char*) cString) SwigStringCallback;


template SwigExternC(T) if (is(typeof(*(T.init)) P == function)) {
  static if (is(typeof(*(T.init)) R == return)) {
    static if (is(typeof(*(T.init)) P == function)) {
      alias extern(C) R function(P) SwigExternC;
    }
  }
}

SwigExternC!(void* function()) new_DPair__SWIG_0;
SwigExternC!(void* function(double jarg1, double jarg2)) new_DPair__SWIG_1;
SwigExternC!(void* function(void* jarg1)) new_DPair__SWIG_2;
SwigExternC!(void function(void* jarg1, double jarg2)) DPair_first_set;
SwigExternC!(double function(void* jarg1)) DPair_first_get;
SwigExternC!(void function(void* jarg1, double jarg2)) DPair_second_set;
SwigExternC!(double function(void* jarg1)) DPair_second_get;
SwigExternC!(void function(void* jarg1)) delete_DPair;
SwigExternC!(uint function(void* jarg1)) DVector_empty;
SwigExternC!(void function(void* jarg1)) DVector_clear;
SwigExternC!(void function(void* jarg1, double jarg2)) DVector_push_back;
SwigExternC!(void function(void* jarg1)) DVector_pop_back;
SwigExternC!(size_t function(void* jarg1)) DVector_size;
SwigExternC!(size_t function(void* jarg1)) DVector_capacity;
SwigExternC!(void function(void* jarg1, size_t jarg2)) DVector_reserve;
SwigExternC!(void* function()) new_DVector__SWIG_0;
SwigExternC!(void* function(void* jarg1)) new_DVector__SWIG_1;
SwigExternC!(void* function(size_t jarg1)) new_DVector__SWIG_2;
SwigExternC!(double function(void* jarg1)) DVector_remove__SWIG_0;
SwigExternC!(double function(void* jarg1, size_t jarg2)) DVector_remove__SWIG_1;
SwigExternC!(void function(void* jarg1, size_t jarg2)) DVector_removeBack;
SwigExternC!(void function(void* jarg1, size_t jarg2, size_t jarg3)) DVector_linearRemove;
SwigExternC!(void function(void* jarg1, size_t jarg2, double jarg3)) DVector_insertAt;
SwigExternC!(double function(void* jarg1, size_t jarg2)) DVector_getElement;
SwigExternC!(void function(void* jarg1, size_t jarg2, double jarg3)) DVector_setElement;
SwigExternC!(void function(void* jarg1)) delete_DVector;
SwigExternC!(void function()) hello;
SwigExternC!(void* function(double jarg1, double jarg2, double jarg3)) make_dvector;
SwigExternC!(double function(void* jarg1)) sum_dvector;
SwigExternC!(void* function(double jarg1, double jarg2)) make_dpair;
SwigExternC!(double function(void* jarg1)) sum_dpair;
