/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

module octra;

static import octra_im;
static import core.stdc.config;

static import std.conv;
static import std.string;

static import std.algorithm;
static import std.exception;
static import std.range;
static import std.traits;


class DPair {
  private void* swigCPtr;
  protected bool swigCMemOwn;

  public this(void* cObject, bool ownCObject) {
    swigCPtr = cObject;
    swigCMemOwn = ownCObject;
  }

  public static void* swigGetCPtr(typeof(this) obj) {
    return (obj is null) ? null : obj.swigCPtr;
  }

  public static void* swigRelease(typeof(this) obj) {
    if (obj !is null) {
      if (!obj.swigCMemOwn)
        throw new Exception("Cannot release ownership as memory is not owned");
      void* ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.dispose();
      return ptr;
    } else {
      return null;
    }
  }

  mixin octra_im.SwigOperatorDefinitions;

  ~this() {
    dispose();
  }

  public void dispose() {
    synchronized(this) {
      if (swigCPtr !is null) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          octra_im.delete_DPair(cast(void*)swigCPtr);
        }
        swigCPtr = null;
      }
    }
  }

  public this() {
    this(octra_im.new_DPair__SWIG_0(), true);
  }

  public this(double first, double second) {
    this(octra_im.new_DPair__SWIG_1(first, second), true);
  }

  public this(DPair other) {
    this(octra_im.new_DPair__SWIG_2(DPair.swigGetCPtr(other)), true);
    if (octra_im.SwigPendingException.isPending) throw octra_im.SwigPendingException.retrieve();
  }

  public void first(double value) @property {
    octra_im.DPair_first_set(cast(void*)swigCPtr, value);
  }

  public double first() @property const {
    auto ret = octra_im.DPair_first_get(cast(void*)swigCPtr);
    return ret;
  }

  public void second(double value) @property {
    octra_im.DPair_second_set(cast(void*)swigCPtr, value);
  }

  public double second() @property const {
    auto ret = octra_im.DPair_second_get(cast(void*)swigCPtr);
    return ret;
  }
}

class DVector {
  private void* swigCPtr;
  protected bool swigCMemOwn;

  public this(void* cObject, bool ownCObject) {
    swigCPtr = cObject;
    swigCMemOwn = ownCObject;
  }

  public static void* swigGetCPtr(typeof(this) obj) {
    return (obj is null) ? null : obj.swigCPtr;
  }

  public static void* swigRelease(typeof(this) obj) {
    if (obj !is null) {
      if (!obj.swigCMemOwn)
        throw new Exception("Cannot release ownership as memory is not owned");
      void* ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.dispose();
      return ptr;
    } else {
      return null;
    }
  }

  mixin octra_im.SwigOperatorDefinitions;

  ~this() {
    dispose();
  }

  public void dispose() {
    synchronized(this) {
      if (swigCPtr !is null) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          octra_im.delete_DVector(cast(void*)swigCPtr);
        }
        swigCPtr = null;
      }
    }
  }

  alias size_t KeyType;
  alias double ValueType;

  this(ValueType[] values...) {
    this();
    reserve(values.length);
    foreach (e; values) {
      this ~= e;
    }
  }

  struct Range {
    private DVector _outer;
    private size_t _a, _b;

    this(DVector data, size_t a, size_t b) {
      _outer = data;
      _a = a;
      _b = b;
    }

    @property bool empty() const {
      assert((cast(DVector)_outer).length >= _b);
      return _a >= _b;
    }

    @property Range save() {
      return this;
    }

    @property ValueType front() {
      std.exception.enforce(!empty);
      return _outer[_a];
    }

    @property void front(ValueType value) {
      std.exception.enforce(!empty);
      _outer[_a] = std.algorithm.move(value);
    }

    void popFront() {
      std.exception.enforce(!empty);
      ++_a;
    }

    void opIndexAssign(ValueType value, size_t i) {
      i += _a;
      std.exception.enforce(i < _b && _b <= _outer.length);
      _outer[i] = value;
    }

    void opIndexOpAssign(string op)(ValueType value, size_t i) {
      std.exception.enforce(_outer && _a + i < _b && _b <= _outer.length);
      auto element = _outer[i];
      mixin("element "~op~"= value;");
      _outer[i] = element;
    }
  }

  // TODO: dup?

  Range opSlice() {
    return Range(this, 0, length);
  }

  Range opSlice(size_t a, size_t b) {
    std.exception.enforce(a <= b && b <= length);
    return Range(this, a, b);
  }

  size_t opDollar() const {
    return length;
  }

  @property ValueType front() {
    std.exception.enforce(!empty);
    return getElement(0);
  }

  @property void front(ValueType value) {
    std.exception.enforce(!empty);
    setElement(0, value);
  }

  @property ValueType back() {
    std.exception.enforce(!empty);
    return getElement(length - 1);
  }

  @property void back(ValueType value) {
    std.exception.enforce(!empty);
    setElement(length - 1, value);
  }

  ValueType opIndex(size_t i) {
    return getElement(i);
  }

  void opIndexAssign(ValueType value, size_t i) {
    setElement(i, value);
  }

  void opIndexOpAssign(string op)(ValueType value, size_t i) {
    auto element = this[i];
    mixin("element "~op~"= value;");
    this[i] = element;
  }

  ValueType[] opBinary(string op, Stuff)(Stuff stuff) if (op == "~") {
    ValueType[] result;
    result ~= this[];
    assert(result.length == length);
    result ~= stuff[];
    return result;
  }

  void opOpAssign(string op, Stuff)(Stuff stuff) if (op == "~") {
    static if (is(typeof(insertBack(stuff)))) {
      insertBack(stuff);
    } else if (is(typeof(insertBack(stuff[])))) {
      insertBack(stuff[]);
    } else {
      static assert(false, "Cannot append " ~ Stuff.stringof ~ " to " ~ typeof(this).stringof);
    }
  }

  alias size length;

  alias remove removeAny;
  alias removeAny stableRemoveAny;

  size_t insertBack(Stuff)(Stuff stuff)
  if (std.traits.isImplicitlyConvertible!(Stuff, ValueType)){
    push_back(stuff);
    return 1;
  }
  size_t insertBack(Stuff)(Stuff stuff)
  if (std.range.isInputRange!Stuff &&
      std.traits.isImplicitlyConvertible!(std.range.ElementType!Stuff, ValueType)) {
    size_t itemCount;
    foreach(item; stuff) {
      insertBack(item);
      ++itemCount;
    }
    return itemCount;
  }
  alias insertBack insert;

  alias pop_back removeBack;
  alias pop_back stableRemoveBack;

  size_t insertBefore(Stuff)(Range r, Stuff stuff)
  if (std.traits.isImplicitlyConvertible!(Stuff, ValueType)) {
    std.exception.enforce(r._outer.swigCPtr == swigCPtr && r._a < length);
    insertAt(r._a, stuff);
    return 1;
  }

  size_t insertBefore(Stuff)(Range r, Stuff stuff)
  if (std.range.isInputRange!Stuff && std.traits.isImplicitlyConvertible!(ElementType!Stuff, ValueType)) {
    std.exception.enforce(r._outer.swigCPtr == swigCPtr && r._a <= length);

    size_t insertCount;
    foreach(i, item; stuff) {
      insertAt(r._a + i, item);
      ++insertCount;
    }

    return insertCount;
  }

  size_t insertAfter(Stuff)(Range r, Stuff stuff) {
    // TODO: optimize
    immutable offset = r._a + r.length;
    std.exception.enforce(offset <= length);
    auto result = insertBack(stuff);
    std.algorithm.bringToFront(this[offset .. length - result],
      this[length - result .. length]);
    return result;
  }

  size_t replace(Stuff)(Range r, Stuff stuff)
  if (std.range.isInputRange!Stuff &&
      std.traits.isImplicitlyConvertible!(ElementType!Stuff, ValueType)) {
    immutable offset = r._a;
    std.exception.enforce(offset <= length);
    size_t result;
    for (; !stuff.empty; stuff.popFront()) {
      if (r.empty) {
        // append the rest
        return result + insertBack(stuff);
      }
      r.front = stuff.front;
      r.popFront();
      ++result;
    }
    // Remove remaining stuff in r
    remove(r);
    return result;
  }

  size_t replace(Stuff)(Range r, Stuff stuff)
  if (std.traits.isImplicitlyConvertible!(Stuff, ValueType))
  {
      if (r.empty)
      {
          insertBefore(r, stuff);
      }
      else
      {
          r.front = stuff;
          r.popFront();
          remove(r);
      }
      return 1;
  }

  Range linearRemove(Range r) {
    std.exception.enforce(r._a <= r._b && r._b <= length);
    immutable tailLength = length - r._b;
    linearRemove(r._a, r._b);
    return this[length - tailLength .. length];
  }
  alias remove stableLinearRemove;

  int opApply(int delegate(ref double value) dg) {
    int result;

    size_t currentSize = size();
    for (size_t i = 0; i < currentSize; ++i) {
      auto value = getElement(i);
      result = dg(value);
      setElement(i, value);
    }
    return result;
  }

  int opApply(int delegate(ref size_t index, ref double value) dg) {
    int result;

    size_t currentSize = size();
    for (size_t i = 0; i < currentSize; ++i) {
      auto value = getElement(i);

      // Workaround for http://d.puremagic.com/issues/show_bug.cgi?id=2443.
      auto index = i;

      result = dg(index, value);
      setElement(i, value);
    }
    return result;
  }

  public bool empty() const {
    bool ret = octra_im.DVector_empty(cast(void*)swigCPtr) ? true : false;
    return ret;
  }

  public void clear() {
    octra_im.DVector_clear(cast(void*)swigCPtr);
  }

  public void push_back(double x) {
    octra_im.DVector_push_back(cast(void*)swigCPtr, x);
  }

  public void pop_back() {
    octra_im.DVector_pop_back(cast(void*)swigCPtr);
  }

  public size_t size() const {
    auto ret = octra_im.DVector_size(cast(void*)swigCPtr);
    return ret;
  }

  public size_t capacity() const {
    auto ret = octra_im.DVector_capacity(cast(void*)swigCPtr);
    return ret;
  }

  public void reserve(size_t n) {
    octra_im.DVector_reserve(cast(void*)swigCPtr, n);
    if (octra_im.SwigPendingException.isPending) throw octra_im.SwigPendingException.retrieve();
  }

  public this() {
    this(octra_im.new_DVector__SWIG_0(), true);
  }

  public this(DVector other) {
    this(octra_im.new_DVector__SWIG_1(DVector.swigGetCPtr(other)), true);
    if (octra_im.SwigPendingException.isPending) throw octra_im.SwigPendingException.retrieve();
  }

  public this(size_t capacity) {
    this(octra_im.new_DVector__SWIG_2(capacity), true);
    if (octra_im.SwigPendingException.isPending) throw octra_im.SwigPendingException.retrieve();
  }

  public double remove() {
    auto ret = octra_im.DVector_remove__SWIG_0(cast(void*)swigCPtr);
    if (octra_im.SwigPendingException.isPending) throw octra_im.SwigPendingException.retrieve();
    return ret;
  }

  public double remove(size_t index) {
    auto ret = octra_im.DVector_remove__SWIG_1(cast(void*)swigCPtr, index);
    if (octra_im.SwigPendingException.isPending) throw octra_im.SwigPendingException.retrieve();
    return ret;
  }

  public void removeBack(size_t how_many) {
    octra_im.DVector_removeBack(cast(void*)swigCPtr, how_many);
    if (octra_im.SwigPendingException.isPending) throw octra_im.SwigPendingException.retrieve();
  }

  public void linearRemove(size_t start_index, size_t end_index) {
    octra_im.DVector_linearRemove(cast(void*)swigCPtr, start_index, end_index);
    if (octra_im.SwigPendingException.isPending) throw octra_im.SwigPendingException.retrieve();
  }

  public void insertAt(size_t index, double x) {
    octra_im.DVector_insertAt(cast(void*)swigCPtr, index, x);
    if (octra_im.SwigPendingException.isPending) throw octra_im.SwigPendingException.retrieve();
  }

  public double getElement(size_t index) {
    auto ret = octra_im.DVector_getElement(cast(void*)swigCPtr, index);
    if (octra_im.SwigPendingException.isPending) throw octra_im.SwigPendingException.retrieve();
    return ret;
  }

  public void setElement(size_t index, double val) {
    octra_im.DVector_setElement(cast(void*)swigCPtr, index, val);
    if (octra_im.SwigPendingException.isPending) throw octra_im.SwigPendingException.retrieve();
  }
}

void hello() {
  octra_im.hello();
}

class Callback {
  private void* swigCPtr;
  protected bool swigCMemOwn;

  public this(void* cObject, bool ownCObject) {
    swigCPtr = cObject;
    swigCMemOwn = ownCObject;
  }

  public static void* swigGetCPtr(typeof(this) obj) {
    return (obj is null) ? null : obj.swigCPtr;
  }

  public static void* swigRelease(typeof(this) obj) {
    if (obj !is null) {
      if (!obj.swigCMemOwn)
        throw new Exception("Cannot release ownership as memory is not owned");
      void* ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.dispose();
      return ptr;
    } else {
      return null;
    }
  }

  mixin octra_im.SwigOperatorDefinitions;

  ~this() {
    dispose();
  }

  public void dispose() {
    synchronized(this) {
      if (swigCPtr !is null) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          octra_im.delete_Callback(cast(void*)swigCPtr);
        }
        swigCPtr = null;
      }
    }
  }

  public double call(double x) {
    auto ret = ((swigIsMethodOverridden!(double delegate(double), double function(double), call)()) ? octra_im.Callback_callSwigExplicitCallback(cast(void*)swigCPtr, x) : octra_im.Callback_call(cast(void*)swigCPtr, x));
    return ret;
  }

  public this() {
    this(octra_im.new_Callback(), true);
    swigDirectorConnect();
  }

  private void swigDirectorConnect() {
    octra_im.SwigDirector_Callback_Callback0 callback0;
    if (swigIsMethodOverridden!(double delegate(double), double function(double), call)()) {
      callback0 = &swigDirectorCallback_Callback_call;
    }

    octra_im.Callback_director_connect(cast(void*)swigCPtr, cast(void*)this, callback0);
  }

  private bool swigIsMethodOverridden(DelegateType, FunctionType, alias fn)() {
    DelegateType dg = &fn;
    return dg.funcptr != SwigNonVirtualAddressOf!(FunctionType, fn);
  }
  private bool swigIsMethodOverriddenConst(DelegateType, FunctionType, alias fn)() inout {
    DelegateType dg = &fn;
    return dg.funcptr != SwigNonVirtualAddressOf!(FunctionType, fn);
  }

  private static Function SwigNonVirtualAddressOf(Function, alias fn)() {
    return cast(Function) &fn;
  }
}

private extern(C) double swigDirectorCallback_Callback_call(void* dObject, double x) {
  return (cast(Callback)dObject).call(x);
}

double call_with_callback(double x, Callback cb) {
  auto ret = octra_im.call_with_callback(x, Callback.swigGetCPtr(cb));
  return ret;
}

DVector map_dvector_with_callback(DVector values, Callback cb) {
  DVector ret = new DVector(octra_im.map_dvector_with_callback(DVector.swigGetCPtr(values), Callback.swigGetCPtr(cb)), true);
  if (octra_im.SwigPendingException.isPending) throw octra_im.SwigPendingException.retrieve();
  return ret;
}

DVector make_dvector(double a, double b, double c) {
  DVector ret = new DVector(octra_im.make_dvector(a, b, c), true);
  return ret;
}

double sum_dvector(DVector values) {
  auto ret = octra_im.sum_dvector(DVector.swigGetCPtr(values));
  if (octra_im.SwigPendingException.isPending) throw octra_im.SwigPendingException.retrieve();
  return ret;
}

DPair make_dpair(double a, double b) {
  DPair ret = new DPair(octra_im.make_dpair(a, b), true);
  return ret;
}

double sum_dpair(DPair values) {
  auto ret = octra_im.sum_dpair(DPair.swigGetCPtr(values));
  if (octra_im.SwigPendingException.isPending) throw octra_im.SwigPendingException.retrieve();
  return ret;
}
